[톰캣 구현하기 1, 2단계] 로빈(임수빈) 미션 제출합니다.
woowacourse/java-http pull request #503
Opened 2024-09-05 05:59 UTC by robinjoon

안녕하세요! 리뷰 잘 부탁드립니다. HTTP 명세 중 이번 미션에 필요한 만큼만 구현했습니다. 

미션 진행 과정에서 클래스가 너무 크고 indent가 깊어져서 약간의 클래스 분리를 한 상태입니다. 더 분리가 필요하지만 다음 단계 요구사항이 리팩토링인 만큼 HTTP 요청과 응답을 표현하는 클래스 추가, HTTP 요청을 파싱하는 클래스 분리정도만 진행했습니다.

2024-09-07 11:56 UTC, takoyakimchi requested changes
.

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
세션 쿠키가 없어도 그냥 로그인 시키고 새로운 쿠키 발급해주는 건 어떨까요?

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11ContentTypeFinder.java
> +}
전체적으로 `ContentType` 내부 로직에 의존적이네요.
`ContentType` 클래스 안에서 처리하면 어떨까요?

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +
이미지가 깨져서 svg도 처리해주면 좋을 것 같아요
<img width="462" alt="image" src="https://github.com/user-attachments/assets/6395aeee-b45a-4ffe-870c-475fdd326a80">

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +        return new Http11Response(Http11StatusCode.OK, copyHeader, cookies, responseBody);
deep copy하는 이유가 무엇인가요??

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
`makeResponseBytes()`는 Response Body랑 합치는 부분인가요?
`toBytes()`에서 바로 byte 배열을 리턴할 줄 알았는데
메서드 분리가 되어 있어서 오히려 혼란스러웠어요.

2024-09-07 11:56 UTC, takoyakimchi commented on tomcat/src/test/java/org/apache/coyote/http11/request/Http11RequestCookieParserTest.java
> +    }
DisplayName이 조금 다르네요!

2024-09-07 11:56 UTC, takoyakimchi commented on study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java
> +        });
```suggestion
        WebContentInterceptor webContentInterceptor = new WebContentInterceptor();
        webContentInterceptor.addCacheMapping(CacheControl.noCache().cachePrivate(), "/");
        registry.addInterceptor(webContentInterceptor);
```

이렇게도 되더라구요

2024-09-07 11:56 UTC, takoyakimchi commented on study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java
> +                .setEtagGenerator(resource -> version.getVersion());
👍👍

2024-09-07 11:56 UTC, takoyakimchi commented on study/src/test/java/study/IOStreamTest.java
> +            }
👍

2024-09-07 12:52 UTC, robinjoon commented on study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java
> +        });
역시 스프링이 구현체를 만들어두었군요. 스프링 그는 대체..

2024-09-08 13:34 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java
> +        LinkedHashMap<String, String> body = REQUEST_PARSER.parseBody(rawRequest);
다른 요소들은 다 별도의 클래스로 만들어뒀는데, body는 컨텐츠 타입마다 요청의 body 형태가 달라질 것 같아서 고민하고 있었습니다.

2024-09-08 13:58 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +        return new Http11Response(Http11StatusCode.OK, copyHeader, cookies, responseBody);
> deep copy하는 이유가 무엇인가요??

정팩메를 호출한 클래스에서 생성한 헤더외에도 저 두 헤더는 필수적입니다. 따라서 누락되면 안되기에 저런 방식을 사용했습니다.

이 과정에서 외부에서 입력받은 데이터는 당연히 수정되지 않는 것이 좋다 판단했습니다. 어떻게 사용할지 모르니까요.

2024-09-08 14:00 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
> `makeResponseBytes()`는 Response Body랑 합치는 부분인가요? `toBytes()`에서 바로 byte 배열을 리턴할 줄 알았는데 메서드 분리가 되어 있어서 오히려 혼란스러웠어요.

이 부분은 취향차이라 생각됩니다. 결국 응답을 byte 배열로 내려줘야 하는데 이때 포함되어야 하는 데이터가 많아서 이를 모두 한 메서드에서 처리하면 그 길이가 매우 길어집니다. 그래서 분리했어요.

2024-09-08 14:35 UTC, robinjoon commented
안녕하세요 트레! 남겨주신 리뷰 대부분 반영했습니다! 파싱 로직 리팩토링 관련 부분은 다음 단계 진행하면서 구조 다시 잡고 천천히 생각해봐야 할 것 같아서 작업하지 않았습니다!

2024-09-09 04:29 UTC, takoyakimchi approved these changes
전체적으로 깔끔하네요.
이제 테스트도 다 통과되고 요구사항도 다 만족하는 것 같아서 approve할게요!
다음 단계에서 봐요.

2024-09-09 04:29 UTC, takoyakimchi commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
> +
오호 배우고갑니다

2024-09-09 04:30 UTC, merged