[1 -2단계 - Tomcat 구현하기] 콜리(김건우) 미션 제출합니다 🥦
woowacourse/java-http pull request #516
Opened 2024-09-06 05:40 UTC by coli-geonwoo

카키, 이야기한대로 2.2단계까지 구현 완료하여 리뷰 요청드립니다!

아마 file change가 많아 리뷰하기가 쉽지 않을 거에요. 몇가지 객체는 아직 사용하지 않고 있기도 하고요.
PR message를 작성할 여유가 많지 않아 6시 이후에 조금 더 친절한 메시지를 써보도록 할게요!

카키의 리뷰를 받게되어 영광입니다 😄

2024-09-07 12:59 UTC, hyeon0208 requested changes
콜리의 코드 리뷰를 맡게되어 영광입니다 😄😄
전체적으로 역할 부여를 깔끔하게 해주신 것 같아서 인상 깊었고 코드 리뷰하기 편했던 것 같아요 👍🏻
몇 가지 제안들 드리고 가요
답변 후 재 리뷰 요청 주세요 ! 😄

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/HandlerMapper.java
> +public enum HandlerMapper {
해당 URI를 매핑하는 컨트롤러를 찾고 반환해주는 코드가 아주 깔끔한 것 같에요 👍🏻

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +    private Map<String, String> resolveResponse(int statusCode, String viewUrl){
[제안]
여러 클래스마다 해당 로직이 중복되고 있는데
`ResponseEntity`와 같은 클래스로 중복을 제거해보는 것은 어떨까요 ?

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/error/ErrorHandlerMapper.java
> +    }
[제안]
이 클래스의 handlerError() 메서드 내에서 사용되고 있는
errorHandler 변수의 handleError() 메서드의 네이밍이 같아 재귀호출로 착각했던 것 같아요
errorHandler의 메서드 개행을 없애거나 네이밍이 중복되지 않도록 변경하는 것은 어떨까요 ?
```
                .errorHandler.handleError();
```

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/error/errorhandler/ErrorHandler.java
> +public interface ErrorHandler {
에러까지 유연하게 처리하셨네요 👍

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java
> +    }
[제안]
stream의 takeWhile문을 활용해 아래처럼 가독성이 좀 더 좋도록 작성할 수도 있을 꺼 같아요 😄
```suggestion
public static HttpHeaders readRequestHeader(BufferedReader bufferedReader) throws IOException {
        Map<String, String> headers = bufferedReader.lines()
                .takeWhile(line -> !line.isBlank())
                .map(line -> line.split(":", 2))
                .collect(Collectors.toMap(
                        split -> split[0].trim(),
                        split -> split[1].trim()
                ));

        return new HttpHeaders(headers);
     }
```

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            Optional<RequestBody> body = initializeBody(bufferedReader, requestLine, httpHeader);
Optional을 사용한 body의 null 처리 적절하네요 👍🏻

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    private final double version;
[제안]
Http의 Start Line 부가 아래와 같이 method, target, http version으로 이뤄져있는 것 처럼
`RequestLine`이 갖고 있는 상태들의 이름도 스펙에 맞춰 네이밍되면 좋을 것 같아요 😁
<img width="366" alt="image" src="https://github.com/user-attachments/assets/30d84d7b-1c3e-4b09-8fad-bf1b28813e78">

2024-09-07 12:59 UTC, hyeon0208 commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
>  class Http11ProcessorTest {
이전에 컨텐츠 길이가 계속 달라져서 Content-Legnth 값을 임의로 바꿔놓은 것 같은데
이제 코드를 잘 적용해서 원래 길이인 "Content-Legnt: 5564"로 바꿔도 되겠네요 👍🏻

2024-09-08 14:56 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private String makeResponse(HttpRequest httpRequest) throws IOException {
맞네요. HttpResponse 객체가 아직 없다보니 body나 컨텐츠 타입 추론 과 같은 역할이 산재되어 있는 느낌이에요. 이번 리뷰 때 HttpResponse를 만들면서 응집시켜 보았습니다!

2024-09-08 14:57 UTC, coli-geonwoo commented on tomcat/src/main/java/com/techcourse/model/UserInfo.java
> +        String[] elements = body.split("&");
파싱하는 데에만 집중해서 그런지 카키처럼 코드를 읽는 사람들을 충분히 배려하지 못한 것 같네요! 합리적인 이야기인 것 같아요 반영해주겠습니다!

2024-09-08 15:02 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +    private Map<String, String> resolveResponse(int statusCode, String viewUrl){
제가 느끼고 있는 기시감과 비슷한 불편함을 카키도 느꼈다는게 기뻐요! 이번에 ResponseEntity와 비슷한 HttpResponseBuilder객체를 만들어 Response 값을 지정해줄 수 있도록 했어요!

2024-09-08 15:06 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/error/ErrorHandlerMapper.java
> +    }
handleError() > handle로 메서드 네이밍을 바꾸어 주었습니다!

2024-09-08 15:09 UTC, coli-geonwoo commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
>  class Http11ProcessorTest {
오... 저는 index.html 파일이 5670으로 읽히는데 카키는 5564로 계속 읽혀지나요??  컨텐츠 길이가 계속 달라지기보다 계속 5670 bytes로 읽혀져서 수정을 하게 된 것 이거든요 😶

2024-09-08 15:12 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
지난 Lv2미션 때 로깅을 조금 소홀히 했다보니 이번 미션 때에도 로깅을 신경쓰지 못했네요. 

카키 리뷰를 받고 이런 저런 로깅 관련 reference 찾아보다가 로깅 레벨과 관련된 글이 있어서 읽어보았어요
![image](https://github.com/user-attachments/assets/854c091c-f70d-41ec-bbb2-1d6f4c5821f6)

IllegalArgumentException의 경우 예상치 못한 에러 이기에 저는 error 레벨이 맞다고 판단이 되었는데 다른 한편으로는 우리 측 잘못이라기보다 클라이언트 잘못인데 error 레벨이 맞는가? 라는 생각도 들어요. 카키는 클라이언트 오류를 어떤 레벨로 로깅하셨나요? 🤔

2024-09-08 15:14 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    private final double version;
RFC를 꼼꼼히 읽어보지 않았는데 카키는 역시 다르군요! Http version이란 값 객체를 통해 관리해주도록 했어요!

2024-09-08 15:43 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java
> +    }
stream에 takeWhile 문이 있는지 처음 알았어요!  맛있네요 🍗

2024-09-08 15:56 UTC, coli-geonwoo commented
카키 리뷰 재 요청 드립니다!

2.2 -2.4 단계의 구현 내용도 포함되어 아마 file change를 보기 힘드실 것 같아[ 지난 리뷰 이후의 커밋 내역](https://github.com/woowacourse/java-http/pull/516/files/3ad2b11b210a53e9b31e872d9243853cb37563ae..7bbbe17d28e3b5dd785e72d11901f1b5a0f8303f) 만 확인해주시면 편하실 것 같아 링크 남겨둡니다!

이번에 제가 신경쓴 지점은 다음과 같아요.
- 카키의 1차 리뷰 반영
    - UserInfo 객체의 Delimiter 네이밍
    - RFC 표준에 맞도록 필드 네이밍
    - takeWhile문을 활용한 Header 초기화 로직 작성
    - Response로 중복 로직 응집화

 -  2.2 -2.4 미션 내용 구현
     - Session 인증 : SessionRepository를 통해 구현
     - setCookie : Cookie 객체가 새로 생겼고 Header안에 Optional로 포함되어 있어요

- fluent API를 활용한 객체 생성
    - header와 response를 builder 패턴을 활용해 초기화하고 있어요.
    - header에 있는 값들과 response를 최대한 불변객체로 만들고 싶어 생성 책임을 따로 분리해주었습니다.
    - ResponseBuilder / HeaderBuilder 객체를 보면 어떤 로직이 있는지 확인가능합니다.

- 어댑터 패턴 도입 
    - 서블릿 컨테이너 내에 HandlerAdapter를 LoginController에 한해 도입해보았어요. 약간 부족한 부분이 있는 것 같긴 한데 개인적으론 확장성에 유리하다 생각해 만족하고 있어요

-  contorller 싱글톤 
    - 스프링 처럼 LoginController를 싱글톤으로 두었어요. 이후 UserController에도 도입해볼 예정입니다.


테스트를 더 작성하고 싶지만 여기까지 하려 해요. 카키도 알겠지만 제 리소스 비중은 프로젝트 6-7 / 미션 2-3이라 이후 시간이 나면 더 투자해보도록 하겠습니다

카키의 `맛있는 리뷰` 기다리고 있겠습니다 🥦 
시간 날 때 가볍게 확인 부탁해요!

2024-09-09 07:59 UTC, hyeon0208 approved these changes
리뷰 커밋 내역을 주셔서 리뷰 하기 편했습니다 감사해요 센스쟁이 콜리 🥦
1차 리뷰 반영 사항 깔끔하게 적용해주셨네요 !
추가로 구현한 내용들에 대해서도 인상 깊었고 훨씬 코드가 깔끔해진 것 같아요 👍 
이번 단계 미션 요구사항들은 충분히 만족한 것 같아서 이만 approve 드립니다.
이제 3, 4단계 미션만 남았네요 ~ 마지막 미션까지 화이팅 ! 😎

2024-09-09 07:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseBuilder.java
> +public class ResponseBuilder {
저도 학습하고 적용해봐야겠습니다 👍

2024-09-09 07:59 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/serdes/Serializer.java
> +public interface Serializer<T> {
직렬화가 필요한 클래스마다 해당 인터페이스를 구현해 사용하도록 한 부분이 인상 깊네요 👍

2024-09-09 07:59 UTC, merged

2024-09-09 15:55 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
저는 개인적으로 애플리케이션에 잠재적 오류나 치명적인 오류인 부분은 아니라 warn, error 보다 하위 레벨을 생각했어요
그렇다고 info레벨을 주기에는 애플리케이션의 실행 상태도 아니라
구체적인 문제를 분석하기 위한 debug나 trace 레벨을 생각했고 debug 레벨을 적용했는데
저도 적절할지는 모르겠네요 ! 개인적인 생각입니다 😀

2024-09-09 15:57 UTC, hyeon0208 commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
>  class Http11ProcessorTest {
저는 5564로 잘 나오던데 콜리가 다르게 나오는 이유는 같이 한번 확인해봐야겠네요 🤔