[STEP-1,2] 톰캣 구현하기 미션 제출합니다
woowacourse/java-http pull request #517
Opened 2024-09-06 05:45 UTC by ksk0605

땡이 안녕하세요~ 
즐겁게 리뷰 주고 받아요!

2024-09-07 04:11 UTC, J-I-H-O reviewed
테바 안녕하세요!
너무너무 깔끔하게 작성해주셨네요. 코드를 읽으면서 재밌다고 느낀 적은 처음인 것 같아요 ㅋㅋㅋ 
사소한 코멘트가 많아서 적당히 넘어가셔도 좋습니다! 정적 콘텐츠 응답 오류 부분만 확인 후 답변 부탁드릴게요!

2024-09-10 01:04 UTC, J-I-H-O requested changes
🫠

2024-09-10 16:36 UTC, ksk0605 commented on tomcat/src/main/java/org/apache/HttpResponse.java
> +    }
이유는 모르는데 개행문자를 저렇게 바꿔주지 않으면 ContentLength 가 정상적으로 계산되지 않아서 위 코드로 작성했었어요!

어..근데 저 분명히 문제가 있어서 바꿔주었었는데.. ㅋㅋㅋ 다시 해보니까 되네요..? ㅋㅋ큐ㅠㅠ
제시해주신 코드로 수정했습니다! 🥲

2024-09-10 16:38 UTC, ksk0605 commented on tomcat/src/main/java/org/apache/HttpRequest.java
> +    private static Map<String, String> parseQueryString(String body) {
감사합니다 생각해보면 위 private 메소드는 HttpBody 클래스로 분리할 수 있을 것 같네요! 
다음 단계에서 분리해봐야겠네요👍

2024-09-10 16:39 UTC, ksk0605 commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    }
디테일을 발견한 당신👍

2024-09-10 16:43 UTC, ksk0605 commented on tomcat/src/main/java/com/techcourse/ResponseResolver.java
> +        if (uri.equals("/")) {
오.. 그런 디테일이👍 전부 수정해주었습니다😀

2024-09-10 16:46 UTC, ksk0605 commented on tomcat/src/main/java/com/techcourse/Controller.java
> +    }
오오 나중에 해야지 하고 놓쳐버렸네요 체크해주셔서 고마워요!

2024-09-10 17:06 UTC, ksk0605 commented
안녕하세요 땡이!!
 리뷰 반영이 좀 늦어서 미안해요 ㅠㅠ

이번 반영된 커밋 내용들은 크게 아래와 같아요
**_1. 땡이 리뷰 적용_**
**_2. 과도한 책임의 RequestResolver 를 HandlerMapping 으로 개선_**

사실 객체를 분리하고 더 나은 코드를 작성할 부분이 많긴한데..🥲
rc 를 남겨주시거나 다음스텝으로 넘어가게 되면 그 때 더 고민해보도록 할게요!!
계속 달려보시죠!! 🏃

2024-09-11 01:46 UTC, ksk0605 commented on tomcat/src/main/java/com/techcourse/Controller.java
> +    }
TODO 의 필요성... 꼼꼼하게 리뷰해주셔서 고마워요 🥲

2024-09-11 07:27 UTC, J-I-H-O approved these changes
테바 안녕하세요 😎
더 깔끔해진 코드 잘 봤습니다! 다음 단계에서 더 많은 얘기 나눠봐요~

2024-09-11 07:27 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/StaticResourceRequestHandler.java
> +	}
Content-type으로 text/html 또는 text/css만 지정해주네요!

JS 파일도 text/html 로 지정되어 응답하는 것을 확인했는데요, 그럼에도 불구하고 브라우저에서 정상적으로 실행되는 것은 브라우저가 **Content Sniffing** 이라는 동작을 해주기 때문이라고 합니다.
Content-Type 헤더가 잘못되었더라도 브라우저가 파일 내용으로부터 적절한 Content-Type을 추론하는 것이라고 하네요.

모든 브라우저가 해당 기능을 제공하는 것이 아니고, 보안상 문제가 생길 수도 있다고 하니 정확한 Content-Type을 응답해주는게 좋을 것 같습니다 😎

응답 헤더에 `X-Content-Type-Options: nosniff` 를 추가하면 Content Sniffing을 비활성화 시킬 수 있습니다.
해당 헤더 추가해보시고 직접 확인해보시면 좋겠습니다!

2024-09-11 07:27 UTC, J-I-H-O commented on tomcat/src/test/java/org/apache/LoginRequestHandlerTest.java
> +	@DisplayName("로그인 POST 요청시 세션을 생성하여 Cookie header 에 전달한다.")
```suggestion
	@DisplayName("로그인 POST 요청시 잘못된 비밀번호를 입력하는 경우 401.html로 리다이렉트한다.")
```

2024-09-11 07:27 UTC, J-I-H-O commented on tomcat/src/test/java/org/apache/StaticResourceRequestHandlerTest.java
> +		assertThat(actual.toString().startsWith(expected)).isTrue();
```suggestion
		assertThat(actual.toString()).startsWith(expected);
```

2024-09-11 07:27 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/HttpRequest.java
>      public String getSessionIdFromCookie() {
이런 메서드들에도 전체적으로 테스트를 작성해주는건 어떨까요?

2024-09-11 07:28 UTC, merged