[톰캣 구현하기 1단계] 호기(조호연) 미션 제출합니다.
woowacourse/java-http pull request #527
Opened 2024-09-06 07:23 UTC by hoyeonyy

안녕하세요 명오! 호기입니다!

이번주에 일정이 너무 많이 겹쳐있어서 의도치 않게 1단계만 내게 되었습니다..😂

빠른시일내에 나머지 step도 제출하겠습니다! 잘부탁드립니다!

2024-09-06 09:01 UTC, HyungHoKim00 approved these changes
고생하셨습니다 호기. 코멘트를 남겨놓았지만, 아직 단계가 3개나 더 남아있고 3단계가 리팩터링이기 때문에 merge 하겠습니다.
다음 단계부턴 테스트도 작성해주세요~

질문: 제 환경에선 Content-length가 달라 index 테스트가 터지는데, 호기 환경에선 정상적으로 동작하나요?

2024-09-06 09:03 UTC, HyungHoKim00 requested changes
approve를 남기려 했으나, localhost로 실행해보니까 페이지가 뜨지 않네요. 확인 부탁드립니다.
아래는 에러 로그입니다.
![image](https://github.com/user-attachments/assets/f62244d1-c1eb-4d06-9715-87c5b6e733c2)

2024-09-10 08:14 UTC, hoyeonyy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpReader.java
> +    private RequestLine getRequestLine(String firstLine) {
저도 public 메서드의 순서에 따라 private 메서드 순서를 정의합니다!

급하게 제출 하느랴 신경 못쓴것 같아요 ㅠㅠ 수정해서 다시 요청하겠습니다!

2024-09-10 13:00 UTC, hoyeonyy commented
"/login" 경로 수정했습니다!

다음 제출 때 테스트까지 작성해서 제출하겠습니다!

2024-09-10 13:34 UTC, HyungHoKim00 approved these changes
고생하셨습니다 호기!! 리팩터링 관련 리뷰가 있던 이유가 다음 미션에 참고하시라는 마음이였는데, Approve가 RC로 바뀌면서 의도가 왜곡되었을 수 있다는 생각이 드네요. 급하셨을텐데 죄송합니다.
리뷰 잘 반영해주신거 확인했고, 요청도 정상 동작하는 것을 확인했습니다.

다만, 저번에 제가 남긴 질문을 못보신 것 같아 다시 남기겠습니다 ㅠㅠ.
질문: 제 환경에선 Content-length가 달라 index 테스트가 터지는데, 호기 환경에선 정상적으로 동작하나요? window라 content-length가 다른가 싶기도 하네요.

이만 머지하겠습니다!

2024-09-10 13:34 UTC, merged