[톰캣 구현하기 1단계] 초롱 미션 제출합니다
woowacourse/java-http pull request #535
Opened 2024-09-06 07:38 UTC by HoeSeong123

안녕하세요 짱수!! 레벨 3 동안 항상 함께 해왔는데 이렇게 또 인사를 드리게 됐네요ㅎㅎ

생각보다 프로젝트에 시간을 많이 투자하게 되어 우선은 1단계만 구현하여 리뷰요청을 드리게 되었습니다!!
미션 요구사항만 만족하는 최소한의 코드만 작성하였고, 책임 분리 등 리팩토링은 3단계에서 순차적으로 진행할 예정입니다!!
따끔한 리뷰 잘 부탁드립니다ㅎㅎ

2024-09-07 12:52 UTC, zangsu requested changes
안녕하세요, 초롱! 
우리 이번 주 굉장히 바빴죠...ㅎㅎ 그래서 이번에는 객체 분리와 같은 큰 리뷰는 우선 제외하고 사소한 요청사항만 남겨 보았어요.
 리뷰에서 요청드린 사항들은 다음 리뷰 요청까지 꼭 반영해 주지 않으셔도 괜찮을 것 같아요.

다만 지금은 제가 확인해 보았을 때는 학습테스트에서 하나, 미션에서 하나가 실패하고 있었는데요.
이 테스트들이 통과할 수 있도록 수정 후 다시 리뷰 요청 주세요!

2024-09-07 12:52 UTC, zangsu commented on study/src/test/java/study/IOStreamTest.java
> +//            System.out.println(outputStream.toString());
사용하지 않는 주석은 삭제해주세요!

2024-09-07 12:52 UTC, zangsu commented on study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java
> +        webContentInterceptor.addCacheMapping(cacheControl, "/**");
```suggestion
        WebContentInterceptor webContentInterceptor = new WebContentInterceptor();
        webContentInterceptor.addCacheMapping(CacheControl.noCache().cachePrivate(), "/**");
```
혹시 `cacheControl` 을 변수로 추출한 이유가 있었을까요?
개인적으론 설정 메서드와 그 메서드에 사용되는 설정값들은 한 곳에 모여 있어야 훨씬 파악이 쉽다고 생각해요. 
제안드린 변경안과 비교해보시고 마음에 드시는 쪽으로 선택하시면 좋을 듯 합니다!

2024-09-07 12:52 UTC, zangsu commented on study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java
> +    }
> 필터를 사용하여 /etag 경로만 ETag를 적용하자.

학습 테스트의 요구조건인데요. 
현재는 `\` 경로의 요청에도 ETag 가 적용되고 있는 것 같아요. 
어떻게 하면 특정 경로에서만 ETag 를 적용해 줄 수 있을까요?

2024-09-07 12:52 UTC, zangsu commented on study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java
> +                .addResolver(new VersionResourceResolver().addContentVersionStrategy("/**"));
오, 이 두개는 처음 보는 메서드이네요!
무엇을 위해서 추가해 준 설정인지 여쭤봐도 될까요??

2024-09-07 12:52 UTC, zangsu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
```suggestion
        try (final var inputStream = connection.getInputStream();
             BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
             final var outputStream = connection.getOutputStream()) {
```

`BufferedReader` 역시 `Closable` 을 구현하는 클래스입니다. 
자원 사용이 끝난 후 자원을 반납하는 것을 잊지 않도록 try-with-resource 안에 포함시켜 볼까요?

2024-09-07 12:52 UTC, zangsu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
감자의 PR 을 보고 훔쳐왔는데요 ㅋㅋ
[감자의 Htto11Processor.java](https://github.com/woowacourse/java-http/pull/509/files/b158638d433f99bafba6853c198710afd9a4abaf#diff-b79fe28366093de0f53b0788897a3fb39caa238ec160c526e14354f6c5036fa4)
파일의 MIME 타입을 얻기 위한 메서드로 `Files.probeContentType()` 메서드가 존재하더라구요!

한번 찾아보고 적용해 보면 훨씬 좋을 것 같습니다!

2024-09-09 05:07 UTC, HoeSeong123 commented on study/src/test/java/study/IOStreamTest.java
> +//            System.out.println(outputStream.toString());
학습용 코드이다보니 다른 방식들도 저장해놓고 싶어서 주석처리 했는데 혹시 괜찮을까요?

2024-09-09 05:09 UTC, HoeSeong123 commented on study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java
> +        webContentInterceptor.addCacheMapping(cacheControl, "/**");
변수로 추출한 별다른 이유는 없었습니다. 확실히 모여 있는 것이 파악하기 쉬운 것 같네요!!

2024-09-09 05:18 UTC, HoeSeong123 commented on study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java
> +    }
이것 때문에 테스트가 실패했던 거군요.. 감사합니다 짱수 😭

2024-09-09 05:23 UTC, HoeSeong123 commented on study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java
> +                .addResolver(new VersionResourceResolver().addContentVersionStrategy("/**"));
해당 코드는 요청된 리소스의 버전을 확인하여 버전과 일치하는 리소스를 제공하고, 만약 파일 내용이 변경되는 경우에는 새로운 버전을 자동으로 생성해주는 코드입니다.
테스트를 통과하기 위해서는 불필요한 코드이긴 한데, 꽤 유용한 코드인 것 같아서 학습용으로 같이 작성해두었습니다.

2024-09-09 05:24 UTC, HoeSeong123 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
오.. close 해야 한다는 것을 완전히 잊고 있었네요..
이래서 try-with-resource를 사용하는 것이군요!! 👍👍👍

2024-09-09 05:28 UTC, HoeSeong123 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
오 굉장히 유용해보이는 메서드네요!!!!😂
확인해보니 지금 코드에 당장 적용시키기는 어려울 것 같고, 2~3단계를 진행하면서 리팩토링을 통해 적용해보도록 하겠습니다!!
좋은 정보 감사합니다 짱수 🎸

2024-09-09 05:29 UTC, HoeSeong123 commented
안녕하세요 짱수!! 
좋은 피드백들 너무 감사합니다. 딱 지금 제 수준에서 필요한 피드백들이었던 것 같네요😁
테스트 코드도 모두 정상 동작하도록 수정하였습니다!!

2024-09-09 06:34 UTC, zangsu commented on study/src/test/java/study/IOStreamTest.java
> +//            System.out.println(outputStream.toString());
앗, 그렇다면 얼마든지요~

2024-09-09 06:35 UTC, zangsu commented on study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java
> +                .addResolver(new VersionResourceResolver().addContentVersionStrategy("/**"));
오, 초롱 덕분에 저도 좋은 메서드를 배워 가는군요!
고마워요 초롱~

2024-09-09 06:41 UTC, zangsu approved these changes
리뷰 반영 고생하셨습니다!
미션 머지 할테니 2단계도 파이팅입니다 🔥 

+) 
`Http11ProcessorTest.process()` 테스트가 실패하긴 하는데요, 아무 요청도 없이 `processor.process()` 메서드만 실행할 일은 없을 것 같아 그냥 무시하겠습니다!
다음 단계 리뷰시에 `@Disabled` 를 사용해 테스트를 무시해 주거나, `/` 요청에 대한 적절한 응답을 추가하고 테스트를 수정해도 좋겠네요!

2024-09-09 06:42 UTC, merged