[톰캣 - 1단계] 타칸(최원준) 미션 제출합니다.
woowacourse/java-http pull request #541
Opened 2024-09-06 07:59 UTC by jhon3242

안녕하세요 조조! 
시간이 없는 관계로 1단계 까지만 구현하고 PR 제출합니다!
2단계 구현 도중에 제출하게 되어서 레벨 2 커밋이 하나 있는데 무시하셔도 좋을 것 같아요! 여기를 통해 레벨 1 커밋만 확인해주시면 감사하겠습니다!

## 리뷰 받고 싶은 부분
- 리팩토링할 부분은 TODO로 작성해두었는데 주석 해둔 부분을 제외하고 리팩토링이 필요할 부분이 보인다면 언급해주면 좋을 것 같아요!
- 예외 처리를 추가적으로 해야하는 부분이 있다면 말해주면 감사하겠습니다!

2024-09-06 08:31 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
예외를 발생시키는 곳은 컨트롤러에서만 가능하도록 리팩터링 중입니다!

2024-09-06 13:36 UTC, eun-byeol requested changes
타칸 안녕하세요! 조조입니다.

예외처리나 추가 리팩토링 위주로 최대한 살펴봤는데, 특별한 점은 찾지 못했어요. 그외 제가 궁금한 몇가지 리뷰 남겼는데 확인부탁드립니다!

전반적으로, 클래스 분리를 잘 하셨네요💯 코드가 깔끔해요! 배워갈 점이 많네요..👍 꿀꺽하겠습니다.ㅎㅅㅎ

한 가지 부탁드리고 싶은 점이 있어요! 저는 직접 코드를 실행시켜서 코드리뷰하는 편인데, 작업중인 브랜치와 PR 커밋이 일치하지 않아서 여러 상황을 돌려보진 못했어요🥲 다음엔 맞춰주시면 더 정확한 리뷰 남길 수 있을 것 같습니다~

2024-09-06 13:36 UTC, eun-byeol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
[질문]
컨트롤러에서만 예외를 발생시키는 이유가 무엇인가요? 궁금해요!

2024-09-06 13:36 UTC, eun-byeol commented on tomcat/src/test/java/org/apache/coyote/http11/ContentTypeTest.java
> +}
EOL 발견!

2024-09-06 13:36 UTC, eun-byeol commented on tomcat/src/test/java/org/apache/coyote/http11/ContentTypeTest.java
> +class ContentTypeTest {
오.. 꼼꼼한 테스트👍

2024-09-06 13:36 UTC, eun-byeol commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java
> +        }
[제안]
여기 하나의 메서드도 더 분리할 수 있을것 같아요!
private 메서드로 나누거나 Headers, Body, Query 등 클래스를 분리하는건 어떤가요?

2024-09-08 06:17 UTC, jhon3242 reviewed
안녕하세요 조조! 
리뷰 해주신 부분을 반영했고 코멘트도 달아놨습니다 ㅎㅎ
그리고 이전에 못했던 레벨 2도 구현해보았어요!
전반적으로 구조를 개선해서 많은 변화가 있을텐데 궁금한 점이 있다면 언제든 DM이나 코멘트 남겨주세요! 즐거운 주말 보내세용😊

2024-09-09 01:21 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        FrontController.service(request);
우선 static 으로 하는 것이 가장 간편한 방법이라고 생각해서 활용했습니다!
static으로 구현하게 되면 확장에 용이하지 않다는 단점이 있죠. 외부에서 의존관계를 주입할 수 없으니까요.
그런데 지금 상황에서는 외부에서 의존관계를 주입해줄 필요성이 없는 정도의 요구사항이기 때문에 가장 빠르게 구현할 수 있는 static을 선택하게 되었습니다!😊

2024-09-09 01:27 UTC, eun-byeol commented on study/src/test/java/study/IOStreamTest.java
> +            }
그렇군요! 그럼 에러를 잡아주지 않는걸 의도하셨을까요?

2024-09-09 01:30 UTC, jhon3242 commented on study/src/test/java/study/IOStreamTest.java
> +            }
넹 굳이 체크 에러는 처리할 수 없는 에러이기도 해서 잡아주지 않도록 구현했습니다!

2024-09-09 13:01 UTC, jhon3242 commented on tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java
> +                    "GET /login?account=gugu&password=password HTTP/1.1 ");
미처 변경된 요구사항을 확인하지 못했었네요😇 변경해놓겠습니다!

2024-09-09 13:25 UTC, jhon3242 commented on tomcat/src/test/java/com/techcourse/service/SessionServiceTest.java
> +        void 존재하지_않는_세션을_확인할_수_없다() {
세션 ID를 임의의 값을 넣었을 때는 조회가 되면 안된다는 것을 명시적으로 나타내고 확인하고 싶어서 해당 테스트까지 구현했습니다!

2024-09-09 13:25 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/coyote/http11/query/Query.java
> +            }
아직까지의 요구사황에서는 쿼리 파라미터로 특수문자가 포함된 경우가 없어서 위와 같이 구현했습니다! 아마 특수 문자를 포함할 수 있도록 요구사항이 변경되면 맞춰서 위 정규표현식에도 변화가 생길 것 같아요! 😊

2024-09-09 13:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/controller/ControllerAdviser.java
> +        }
좋은 방식이네요! 다음 PR에서 반영해보겠습니다!😁

2024-09-09 13:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/controller/ControllerMapper.java
> +    FILE(null, new FileController()),
저도 Map 방식도 고려해보긴 했는데 어떤 URI에 어떤 컨트롤러가 매핑되는지 파악하기 쉬운 형태가 Enum이라고 생각했어서 Enum을 선택하게 되었어요! 
Map으로 구현하게 된다면 `findByPath` 메서드에서 파일 컨트로를 리턴해야하는 부분에서`return controllerMap.get("file")` 와 같은 형태로 될 것 같아요. 이 보다는 `return FILE.Controller` 같은 형태가 더 가독성이 좋다고 느껴졌던 것 같아요.
물론 조조가 말한대로 매핑할 컨트롤러가 많아진다면 성능상 Map을 고려해볼만 한 것 같네요!😊

2024-09-09 13:25 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/coyote/http11/query/Query.java
> +    public static Query create(String queries) {
이전까지 메서드명으로 어떤 값을 통해 객체가 생성되는지 알려주기 위해 `createBy...` 와 같은 형태로 메서드명을 지었는데 `createByString` 등 같은 메서드가 생기면서 그 의미가 많이 퇴색된 것 같았어요. 그래서 그럴바에는 `create` 라는 메서드 명으로 통일하자. 라고 생각하여 위와 같이 메셔드를 작성했었습니다(`from`, `of` 도 고려하긴 했지만 이 또한 메서드명을 통해 의미를 전달하지 못한다고 느껴졌습니다) . 앞으로 정적팩토리 메서드는 `create` 로 통일할 것 같습니다! 
이에 대해서 조조의 의견이 궁금하네요! 🧐

2024-09-09 13:31 UTC, merged

2024-09-09 13:42 UTC, eun-byeol commented on tomcat/src/main/java/org/apache/coyote/http11/query/Query.java
> +    public static Query create(String queries) {
저는 `of` 혹은 `from`를 그대로 사용할 것 같아요. `create`를 사용하지 않는 이유는, `create` 또한 정팩메 네이밍 컨벤션이라서 의도와는 맞지 않다고 생각해요. 혼동의 여지가 있어서 `gernerate` 혹은 `generateByQueries`은 어떠신가요? 물론 타칸의 생각 100% 존중합니다!

2024-09-10 07:31 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/coyote/http11/query/Query.java
> +    public static Query create(String queries) {
`create` 대신 `generate` 네이밍을 하면 혼동의 여지가 줄어드는 이유가 궁금해요!
 제 생각에는 `create` 나 `generate` 나 서로 비슷한 것 같아서요. 😭

2024-09-11 16:03 UTC, eun-byeol commented on tomcat/src/main/java/org/apache/coyote/http11/query/Query.java
> +    public static Query create(String queries) {
[정적 팩토리 메서드 네이밍 규칙(이펙티브자바)](https://mimah.tistory.com/entry/Effective-Java-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-Static-factory-method#%EC%A0%95%EC%A0%81%20%ED%8C%A9%ED%86%A0%EB%A6%AC%20%EB%A9%94%EC%84%9C%EB%93%9C%20%EB%84%A4%EC%9D%B4%EB%B0%8D%20%EA%B7%9C%EC%B9%99-1) 참고해보시면 좋을것 같아요! 

단어의 뜻은 비슷하지만, create은 굳어진 네이밍 컨벤션으로 사용하고 있어요.
> create : (매개변수를 받는다면) 매개변수로 명시한 매번 새로운 인스턴스를 생성해 반환함을 보장한다.

매개변수 타입의 인스턴스를 생성해주는게 컨벤션인데, 타칸이 사용한 create는 매개변수를 가공하여 인스턴스를 만들어주는 기능을 수행하고 있어요. 이 부분이 혼동의 여지가 있을 수 있겠다 싶었어요! 제가 다르게 이해한 부분이 있다면 말씀해주세요~!😊