[1 - 2 단계 Tomcat 구현하기] 제리(김민정) 미션 제출합니다.
woowacourse/java-http pull request #569
Opened 2024-09-06 08:47 UTC by mzeong

2024-09-07 17:01 UTC, shin-jisong reviewed
안녕하세요 제리!
깔끔하지 못한 코드라고 말씀해 주셨지만 2단계까지를 깔끔하게 잘 작성하셨다고 생각합니다 👍
말씀하신 보충 사안들 무리하지 마시고 완로 후 재요청 보내 주세요 🙇‍♂️

2024-09-08 15:18 UTC, shin-jisong requested changes
코멘트로 남겨 다시 리뷰 남깁니다!

2024-09-11 05:55 UTC, mzeong commented on tomcat/README.md
> +- [ ] Cookie에 JSESSIONID 값 저장하기
Cookie 클래스를 만들지 않아도 Cookie에 JSESSIONID 값을 저장할 수 있어서 진행하지 않았는데
리팩토링 과정에서 HttpCookies 클래스를 만들어줬습니다!

2024-09-11 05:56 UTC, mzeong commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java
> +        if (fields.containsKey("Content-Length")) {
HeaderKey 이넘을 생성해 하드코딩된 문자열을 개선했습니다!

2024-09-11 05:59 UTC, mzeong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                    UUID idValue = UUID.randomUUID();
Session 내에 ID를 랜덤으로 생성하여 세션을 만드는 정적 팩터리 메서드를 두었습니다 👍

2024-09-11 07:25 UTC, mzeong commented
안녕하세요 시소! 제리입니다
지난 description에서 설명했던 오류(유효한 JSESSIONID가 아니더라도 로그인 처리)는 해결되었습니다 

[지난 리뷰 요청 이후 변경사항만 모아보기](https://github.com/woowacourse/java-http/pull/569/files/24a75cee6deebb88af93e7b3da0222925676bbe5..130a967a703f9f2f4db44e18140a53048494bb74#diff-d0d76d5ed3a1ec1f94566237bfb55794c9d91b24bdbc9e35671c6042f35de476)

2024-09-11 09:37 UTC, shin-jisong commented
잘 반영해 주셔서 이만 머지합니다! 수고하셨어요 👍
바쁘셔서 그랬겠지만 테스트 코드가 없어서 여유가 되신다면 테스트 코드도 보강해 보면 어떨까 싶어요!

2024-09-11 09:37 UTC, merged