[1 - 2 단계 Tomcat 구현하기] 레디(최동근) 미션 제출합니다.
woowacourse/java-http pull request #570
Opened 2024-09-06 08:47 UTC by reddevilmidzy

안녕하세요 제제 리뷰이 레디입니다 :)

1,2 단계까지 구현하고 리뷰 요청드려요 

학습테스트도 같이 커밋되어 있어요. 요부분도 리뷰 남길 거 있다면 남겨주어도 좋아요! 

코드가 많이 너저분하지만 잘부탁드립니다 🙇‍♂️

2024-09-07 08:28 UTC, JINU-CHANG reviewed
레디 잘 구현해주셨네요 😊
저와 비슷하면서 다른 부분이 많아 코드 재밌게 읽었습니다.
읽으면서 궁금하거나 개선하면 좋을 부분들에 대해 리뷰 남겨두었으니 시간날때 확인해주세요 :)
수고많으셨습니다 ~

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java
> +    }
while문 탈출조건문을 더 깔끔하게 리팩토링해볼 수 있을 것 같아요! 🤔

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
requestLine이라는 네이밍은 어떤가요? RFC에 명시된 이름을 사용하면 이해하기 더 쉬울 것 같아요~
![image](https://github.com/user-attachments/assets/1d0572e9-6ec8-4b95-9fd7-83156009b0d8)

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
requestMethodAndUrl은 HttpHeaders 내부에 두지 않은 이유가 있을까요??

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
Response 객체를 사용하니 깔끔해지네요 👍👍

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private void redirectIndex(final Response response, final Path request, final String result) {
Index라는 단어를 사용한 이유가 있나요??

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        response.setLocation("index.html");
location까지 파라미터로 받으면 좋을 것 같아요!

2024-09-07 08:28 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private void generateOKResponse(final Response response, final Path request, final String result) {
생성자를 통해 Response객체를 생성할 수도, 지금처럼 Response를 생성한 후 set 메서드를 활용할 수도 있을텐데 현재 방식을 선택한 이유가 있나요??

2024-09-07 08:48 UTC, JINU-CHANG approved these changes

2024-09-07 08:50 UTC, JINU-CHANG requested changes
레디 잘 구현해주셨네요 😊
저와 비슷하면서 다른 부분이 많아 코드 재밌게 읽었습니다.
읽으면서 궁금하거나 개선하면 좋을 부분들에 대해 리뷰 남겨두었으니 시간날때 확인해주세요 :)
수고많으셨습니다 ~

2024-09-08 07:51 UTC, reddevilmidzy reviewed
제제 꼼꼼한 리뷰 감사합니당 ^!^
(_ _)

2024-09-08 07:51 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java
> +    }
우선 IOException 발생처리를 해당 메서드를 사용하는 메서드로 책임을 넘겼습니다. 그래서 try catch 문이 사라졌고 [밸덩](https://www.baeldung.com/java-buffered-reader#2-reading-line-by-line) 참고해서 리팩터링 하였습니다! 
확실히 간결해졌네요

2024-09-08 07:51 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
옷 좋습니다!!

2024-09-08 07:51 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private void generateOKResponse(final Response response, final Path request, final String result) {
Response의 필드가 많다보니 생성자로 한번에 초기화할 경우 타입 순서를 잘못작성하는 문제가 발생할 수 있을 것 같습니다. 그래서 생성자를 통한 객체 생성대신 setter를 열어주었지만 지금생각해보니 빌더패턴을 사용하여 해결할 수도 있을 것 같네요!

2024-09-08 07:51 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
(할까말까 하다가 그것까지 해버리면 3단계할 때 심심할 거 같아서 남겨두었습니다)

2024-09-08 07:51 UTC, reddevilmidzy commented on tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java
> +        final var user = new User(1L, "redddy", "password", "redddy@redddy.com");
우선 중복을 제거하여 코드가 간결해집니다! 
위 코드에서 var를 사용하지 않는다면 
```java
final User user = new User(1L, "redddy", "password", "redddy@redddy.com");
```
= 왼쪽에도 User 있고 오른쪽에도 User가 있어 타입이 두번 보이게 됩니다. 
하지만 var를 사용하면 이런 중복이 사라집니다 👍 

그리고 개인적으로 느꼈던 점은 네이밍을 할 때 좀 더 많은 고민을 하게 되는 것 같았습니다. 이전에 네이밍할 때에는 왼쪽에도 타입이 보이니 대애충 이름을 지었는데, var를 사용하니 타입이 안보여 어떤 이름을 지어야 명확해질까 하는 고민이 생겼었습니다. 이러면 더 좋은 이름을 지을 수 있는 연습이 될 거 같습니다!

2024-09-08 12:18 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java
> +    }
엄청나게 깔끔해졌네요 😮👍

2024-09-08 12:18 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
ㅋㅋㅋㅋㅋ 좋습니다~! 레벨3때 확인해볼게욧

2024-09-08 12:48 UTC, JINU-CHANG commented on tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java
> +        final var user = new User(1L, "redddy", "password", "redddy@redddy.com");
코드가 더 간결해진다고 말씀해주셨는데요, 저같은 경우 불편함이 더 크다 느꼈습니다 🥲
코드 리뷰를 하면서 타입이 적혀있지 않아 추론하며 읽는 것이 쉽지 않았습니다. 또한 왼쪽부터 코드를 읽게되는데 타입을 확인하기 위해 오른쪽으로 계속해서 시선을 왔다갔다하는 것도 쉽지 않았습니다. 오히려 왼쪽에 타입이 적혀있으면 더 빠르게 읽었을텐데 말이죠!

타입 선언에 익숙해져서 var 사용이 어색하다고 느껴지나 싶기도 한데,, 이에 대한 레디의 의견을 한 번 더 들어보고 싶습니다~

2024-09-08 12:50 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private void generateOKResponse(final Response response, final Path request, final String result) {
필드가 많아 setter를 사용했다는 이유가 합리적이라고 느껴지네요 👍
빌더패턴에 대해 살짝 언급해주셨는데, 어떤 부분을 해결하기 위해 필요하다고 생각하셨나요??

2024-09-08 12:56 UTC, JINU-CHANG requested changes
레디 깔끔하게 리팩토링해주셨네요 👍

마지막으로 살짝 궁금한 것들이 남아 RC 보냅니다!

2024-09-09 00:56 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private void generateOKResponse(final Response response, final Path request, final String result) {
프리코스 때부터 setter를 지양해야 한다고 배워 setter 사용 문제를 해결하기 위해 빌더 패턴이 떠올랐습니다!!

2024-09-09 01:04 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var requestMethodAndUrl = bufferedReader.readLine();
맡겨만주시라요

2024-09-09 05:54 UTC, reddevilmidzy commented on tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java
> +        final var user = new User(1L, "redddy", "password", "redddy@redddy.com");
오오오 재밌는 시선이군요 ㅎ.ㅎ
확실히 저도 코드 읽을 때에는 왼쪽부터 읽는 것 같아요

이번 미션에서 var를 사용하면서 느꼈던 장점이 자바도 간결하게 표현할 수 있구나!를 느꼈는데, 자바메타랑 살짝 안맞는 거 같기도 하네요 😂

코드 짜는 시간보다 읽는 시간이 더 길기 때문에 쓰기 편한 코드보다 읽기 편한 코드가 더 중요한거 같네요 3단계 리팩터링 때 var 걷어내겠습니다! 👍

2024-09-09 08:21 UTC, JINU-CHANG approved these changes
남겨준 코멘트 모두 확인했습니다!
모두 잘 반영해주신 것 같아 이번단계 머지합니다. 수고많으셨어요 🚀🚀🚀

2024-09-09 08:21 UTC, merged