[1 - 2 단계 Tomcat 구현하기] 테드(김규태) 미션 제출합니다.
woowacourse/java-http pull request #572
Opened 2024-09-06 08:48 UTC by Kimprodp

안녕하세요 타칸! 오랜만입니다.😊

미션 1-2 단계 구현 완료해서 리뷰 요청드립니다.

두 번째 학습(cache)은 시간이 부족하여 진행하지 못했습니다.

구현하면서 여러 책임이 합쳐지게 되어 나름대로 클래스를 분리하며 진행해봤습니다.
그래도 아직 개선할 부분이 많이 보이긴 하는데요. 편하게 리뷰 부탁드립니다!

2024-09-06 11:24 UTC, jhon3242 requested changes
안녕하세요 테드! 😁 오랜만이네요! 잘 지내고 있죠? ㅎㅎ
대부분 스프링의 구조를 따라서 확장가능하고 가독성 있게 코드를 너무 잘 작성하셨네요! 많이 배워갑니다! 😊
2단계까지 빠르게 구현하셨네요! 궁금한 부분은 `질문)`, 수정이 필요하다고 생각하는 부분은 `의견)` 키워드로 남겼어요! 확인 부탁드릴게요!!

2024-09-06 11:24 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +        for (String cookieParts : cookie.split(" ")) {
의견) 만약 "Cookie" 헤더가 없다면 NPE가 발생하지 않을까요??🧐

2024-09-06 11:24 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +        SessionManager sessionManager = new SessionManager();
질문) SessionManager 의 메서드들을 정적 메서드로 만들어서 호출하는 방식 대신  매번 `SessionManager` 객체를 생성해서 사용하는 이유가 궁금해요!😄

2024-09-09 04:32 UTC, Kimprodp commented on study/src/main/resources/application.yml
> +      min-spare: 2
이건 메인 브랜치 변경사항 받아오면서 생긴 부분인 것 같아요!

2024-09-09 11:29 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    }
이 부분은 어차피 body가 없으면 null을 넣기 위함이라 불필요한 조건이 추가되는 것 같아 NumberFormatException만 체크하면 될 것 같습니다!

2024-09-09 12:01 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    }
우선은 Http11Processor 에서 분리를 위한 목적으로만 했었는데요, HttpRequest에서 값을 분리하고, 예외 처리하는 책임이 없는 것이 맞을 것 같아 HttpRequestParser를 둬서 요청을 분리하는 책임을 나누는 것으로 변경했습니다.

2024-09-09 12:22 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/ViewController.java
> +    }
이렇게 하면 Http11ProcessorTest가 통과하지 못해서 그냥 두었었어요..

2024-09-09 12:33 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/ViewController.java
> +    }
우리가 실제로 구현을 할 때에도 컨트롤러에서 요청에 대한 응답 처리를 직접 설정하는 것과 같이 생각했어요. 음 당장 더 좋은 방법은 떠오르지 않는 것 같아요.

2024-09-09 13:19 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/ViewController.java
> +        }
현재 Accept 가 test/css 인 경우만 ContetnType을 처리하고 나머지는 모두 html로 설정하고 있습니다.

요청에서 css 파일을 제외한 다른 요청을은 모두 Accept=*/* 로 모든 타입을 수용하고 있어서 반환이 가능한 것으로 보입니다!

이 부분은 헷갈릴 수 있어 요청의 accept를 응답의 contentType에 그대로 적용하는 것으로 변경했습니다!

2024-09-09 13:32 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/AbstractController.java
> +    }
오 처리를 안해서 NPE가 발생하네요.. 404를 반환하도록 변경했습니다!

2024-09-09 13:45 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +public class LoginController extends AbstractController {
비즈니스 로직을 처리하는 클래스가 아파치에 있는 것이 이상하네요.. techcourse 패키지로 구조를 변경하였습니다!

2024-09-09 13:52 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +        }
예외가 발생할 경우 400을 응답하도록 catch 구문을 추가했습니다~

2024-09-09 13:56 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +        for (String cookieParts : cookie.split(" ")) {
꼼꼼하네요 👍 쿠키가 없으면 null을 반환하도록 변경했습니다~

2024-09-09 14:03 UTC, Kimprodp commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +        SessionManager sessionManager = new SessionManager();
세션 데이터가 하나로 관리되고, 매번 인스턴스를 생성할 필요가 없으므로 static 메서드로 활용하도록 변경했습니다!

2024-09-10 01:25 UTC, jhon3242 commented on tomcat/src/main/java/org/apache/catalina/controller/ViewController.java
> +    }
저는 그래서 그냥 테스트를 지웠습니다 ㅎㅎ 테드 편하신대로 하면 좋을 것 같아요!

2024-09-10 05:25 UTC, jhon3242 approved these changes
안녕하세요 테드! 타칸입니다!
전반적으로 많이 리팩터링 되었네요! 
가독성 있게 코드를 잘 작성하시고 구조가 실제 스프링과 유사한 구조로 구현하신 것 같아 많이 배웠습니다! 
몇가지 검증에 대한 커멘트 남겨두었는데 다음 PR때 반영해주시면 될 것 같아서 이만 merge 하겠습니다!
추가로 다음 PR에는 테스트 코드도 같이 추가해주시면 좋을 것 같습니다! 수고하셨습니다!😊

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/handler/RequestMapping.java
> +
제안) ViewController도 싱글톤으로 구현하는게 좋을 것 같아요!😊

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/session/SessionManager.java
> +    private static final Map<String, Session> SESSIONS = new HashMap<>();
의견) 지금은 동시성을 처리할 필요는 없지만 추후 동시성을 고려한다면 ConcurrentHashMap으로 바꿔주면 좋을 것 같네요!

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +    }
의견) 해당 메서드는 LoginController 보다는 SesseionManager의 책임이라고 느껴지는 것 같은데 테드의 생각이 궁금해요!🧐

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +            User user = new User(account, password, email);
의견) reqeustForm 에 account 가 없거나 email 이 없거나 등에 대한 검증은 추가해주면 좋을 것 같아요!

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +
불필요한 개행이네요😁

2024-09-10 05:25 UTC, jhon3242 commented on tomcat/src/main/java/com/techcourse/session/Session.java
> +    private final Map<String, Object> values = new HashMap<>();
👍👍 배워갑니다!

2024-09-10 05:27 UTC, merged

2024-09-13 04:27 UTC, Kimprodp commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +
3단계 하면서 공백도 다시 확인했습니다 👍

2024-09-13 04:39 UTC, Kimprodp commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +            User user = new User(account, password, email);
반영 완료 👍

2024-09-13 04:42 UTC, Kimprodp commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +    }
쿠키에서 JSessionId를 추출하는 책임을 쿠키가 가지고 있는 것이 맞는 것 같아서 조정했습니다