[1 - 2 단계 Tomcat 구현하기] 마크(김승현) 미션 제출합니다.
woowacourse/java-http pull request #580
Opened 2024-09-06 08:53 UTC by seunghye218

추후 작성하겠습니다....

2024-09-07 10:34 UTC, jongmee requested changes
안녕하세요 마크 !! 깔끔하게 구현해주셔서 코드를 이해하기 쉬웠어요 👍 몇 가지만 리뷰 달아 놓았습니다 😊

2024-09-07 10:34 UTC, jongmee commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                        .build();
유효하지 않은 세션이 있으면 로그인 페이지로 가는 군요 ! 디테일 👍

2024-09-07 10:34 UTC, jongmee commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        for (String data : body.split("&")) {
미디어 타입이 `application/x-www-form-urlencoded`이면(html form 태그) body가 쿼리 파라미터와 같은 형식으로 가는데 현재  `HttpRequest`에 존재하는 parameter 필드에 담아둬도 좋을 것 같아요 !

2024-09-07 10:34 UTC, jongmee commented on tomcat/src/main/java/com/techcourse/http/HttpResponse.java
> +    public String build() {
(의견) `HttpRequestParser`처럼 응답에 대해서도 parser가 있으면 파싱 로직과 기타 로직들을 분리할 수 있을 것 같아요 !

2024-09-07 10:34 UTC, jongmee commented on tomcat/src/main/java/com/techcourse/http/HttpResponse.java
> +    private String statusMessage;
상태 코드도 `MimeType` 처럼 enum으로 관리하면 모아서 보기 편할 것 같아요 !

2024-09-07 10:34 UTC, jongmee commented on tomcat/src/main/java/com/techcourse/http/MimeType.java
> +        return DEFAULT.mimeType;
디폴트도 지정해주셨군요 ! 배워갑니다 ☺️

> application/octet-stream is the default value for all other cases. An unknown file type should use this type.

2024-09-09 03:57 UTC, seunghye218 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                        .build();
아이디를 임의로 바꿔도 접속이 가능한게 신경쓰이더라고요😄

2024-09-09 04:40 UTC, seunghye218 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        for (String data : body.split("&")) {
스프링도 저 MIME 타입을 쿼리 파라미터로 처리하는 것 같네요! 저도 사용하기도 쉽게 parameter로 관리해봐야겠어요. 놓치고있던 URL디코드도 같이 적용해볼게요.

2024-09-09 05:09 UTC, seunghye218 commented on tomcat/src/main/java/com/techcourse/http/HttpResponse.java
> +    public String build() {
어떤 값을 파싱 해야할지 잘 모르겠어요...! 우선 리팩토링 해보고 다시 제출해볼게요.

2024-09-09 06:56 UTC, jongmee commented on tomcat/src/main/java/com/techcourse/http/HttpResponse.java
> +    public String build() {
빌더 패턴이 생각나서 `build()`메소드로 HttpResponse를 만들고 이 객체를 String으로 변환하는 util 클래스(HttpRequestParser의 역버전)를 만들면 어떨까 생각했습니다 ㅎㅎ! 개인적인 의견이니 다음 단계에서 선택적으로 반영해주세요 ☺️

2024-09-09 06:57 UTC, jongmee commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        for (String data : body.split("&")) {
오 URL 디코드까지!! 💯

2024-09-09 06:58 UTC, jongmee commented
리뷰 반영해주신거 모두 잘 확인했습니다 :) 더 디테일하고 깔끔해졌네요 ! 다음 단계에서 봬요 😊

2024-09-09 06:59 UTC, merged

2024-09-11 07:48 UTC, seunghye218 commented on tomcat/src/main/java/com/techcourse/http/HttpResponse.java
> +    public String build() {
확실히 `OutStream.write` 할 값을 반환하는 것은 `HttpResponse` 책임이라 하기에 애매하네요! 방법 잘 생각해서 적용해볼게요👍