[1 -2.2단계 - Tomcat 구현하기] 다온(조형익) 미션 제출합니다
woowacourse/java-http pull request #588
Opened 2024-09-06 08:59 UTC by ikjo39

안녕하세요 배키! 
배키와는 처음 리뷰를 나눠보네요! 
리뷰 잘 부탁드리겠습니다!! 🤭

# 진행상황
현재 미션은 2단계의 2. POST 방식으로 회원가입까지 구현하였습니다.
1단계를 구현한 후 각 책임 별 객체를 분리해보았습니다! 
몇몇 유틸 클래스가 있는데 해당 클래스는 어떻게 분리해야 할지 헷갈려 그대로 구현하게 되었습니다.

HTTP 활용하기 학습테스트의 마지막 단계만 오늘까지 수정하여 푸시하겠습니다!!

2024-09-06 14:29 UTC, ehBeak reviewed
안녕하세요 다온! 
리뷰어 배키입니다 🤭

클래스를 잘 나누어 주셔서 코드 읽기가 수월했습니다~ 고민의 흔적이 보이네요.. 하하
사소한 코멘트 남겼으니, 확인 부탁드려요! 확인 해보시고 반영하고 싶은 부분 반영 부탁드립니다 :)

리뷰하지만 많이 배우고 가요 특히, HttpResponseEntity는 제가 오히려 배우고 가는 것 같네요 👍
고생 많으셨어요~!

2024-09-06 14:29 UTC, ehBeak commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    private final T body;
제네릭 좋네요~!👍👍

2024-09-06 14:29 UTC, ehBeak commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
> +    @DisplayName("css 파일 요청을 보내면 적절한 Conte")
문장이 끊긴 것 같네요!

2024-09-06 14:29 UTC, ehBeak commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestLine.java
> +    }
이미 if문 내부에서 return을 하기 때문에 else if문을 사용하지 않아도 될 것 같아요!
```suggestion
        if (httpMethod.isGet()) {
            HttpResponse<?> httpResponse = requestUri.processParams(httpMethod);
            return requestUri.getHttpResponse(httpResponse);
        } 
        if (HttpMethod.POST.equals(httpMethod)) {
            HttpResponse<?> httpResponse = requestUri.processParams(httpMethod, bodies);
            return requestUri.getHttpResponse(httpResponse);
        }
        throw new UncheckedHttpException(new UnsupportedOperationException("지원하지 않는 기능입니다."));
    }
```

2024-09-06 14:29 UTC, ehBeak commented on tomcat/src/main/java/com/techcourse/controller/UserController.java
> +        Optional<User> user = InMemoryUserRepository.findByAccount(account);
만약 `Optional<User> `값에 `user`가 없다면 이후 `user.get()`을 할 때 예외가 발생할 것 같아요. 이에 대한 예외처리를 하면 어떨까요?

2024-09-06 14:33 UTC, ehBeak requested changes
.

2024-09-07 05:26 UTC, ikjo39 commented on tomcat/src/main/java/com/techcourse/controller/UserController.java
> +        Optional<User> user = InMemoryUserRepository.findByAccount(account);
`User` 가 `InMemoryRepository`에 존재하지 않는 경우를 말씀하신게 맞으실까요?
그렇다면 아래 if 분기에서 `Optional<User>`가 비어있는(`empty()`)일 경우 401을 응답하도록 처리해주고 있습니다!

2024-09-07 05:27 UTC, ikjo39 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestLine.java
> +    }
Early Return이기에 분기문 간 서로 간섭은 안하겠네요.
감사해요 배키!

2024-09-07 05:27 UTC, ikjo39 commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
> +    @DisplayName("css 파일 요청을 보내면 적절한 Conte")
이런 실수가 있었네요 😅 
반영하겠습니다!

2024-09-07 05:30 UTC, ikjo39 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java
> +    }
오오 커스텀 헤더로 정보를 주고 받을 수 있군요. 처음 알았네요 😃 
그래서 `org.springframework.http.HttpHeaders`가 클래스로 존재했던 거였네요 ㅋㅋㅋ
덕분에 의문도 함께 해소되었어요.

2024-09-07 05:46 UTC, ikjo39 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    private final Map<String, String> bodies;
POST 요청시 Http Request 본문에 형식에 따라 파싱이 안될 수 있으니 이를 고려해보란 말씀이시군요!
이 부분도 다시 설계해봐야겠네요 😅

감사합니다!

2024-09-07 05:57 UTC, ikjo39 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java
> +            String[] splitLine = line.split(": ");
헙.. 제가 생각 못한 적절한 예외 상황이네요. 
입력값은 믿을 수 없으니 배키의 말씀이 타당해보입니다!

\+ 배키 리뷰를 보고 테스트 해본 결과 헤더의 키에 `: `가 들어간다면 `String[] splitLine = line.split(": ", 2);` 로도 해결이 되지 않음을 확인했습니다!
저는 split의 개수에 대한 검증을 추가해보려 합니다! :)

2024-09-08 05:10 UTC, ehBeak commented on tomcat/src/main/java/com/techcourse/controller/UserController.java
> +        Optional<User> user = InMemoryUserRepository.findByAccount(account);
앗 그렇네요! 조건문에서 그 부분을 확인하지 못했군요..😅

2024-09-08 05:14 UTC, ehBeak approved these changes
안녕하세요! 다온!
리뷰 적극 반영해주신 내용 확인했습니다 :)

고생 많으셨어요~! 머지할게요 👍👍 다음 단계도 화이팅입니다~~

2024-09-08 05:15 UTC, merged