[3단계 톰캣 구현하기] 위브(김기범) 미션 제출합니다.
woowacourse/java-http pull request #603
Opened 2024-09-10 13:05 UTC by jimi567

커찬 안녕하세요. 
3이랑 4단계랑 내용이 다른 것 같아서 끊어서 리뷰 요청 드리게 됐습니다.

이번 단계에서는 lms 요구사항처럼 HttpServlet 형식으로 핸들러를 리팩터링 해봤습니다.
메서드나 클래스명은 기존 코드와 혼동이 올 수 있다 생각해서, 굳이 바꾸지는 않았습니다.
이번 단계 리뷰가 끝나면 바꿀 예정입니다.

was가 제공해야 되는 기능과 클래스 간의 책임이 적절한지 위주로 봐주시면 감사하겠습니다.

바쁜 와중에 리뷰에 시간 할애해주셔서 감사합니다^.^

2024-09-11 04:28 UTC, leegwichan requested changes
안녕하세요 위브! 커찬입니다.
코드 잘 봤습니다~ 제가 보았을 때, 전반적인 구조에서는 남길 코멘트가 없네요
궁금한 점 위주로 코멘트 남겼습니다! 반영 or 답변 주시고 리뷰 요청 주세요!

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/test/java/org/apache/coyote/http11/NotFoundHandlerTest.java
`NotFoundHandler`와 `NotFoundHandlerTest`가 같은 패키지에 있도록 바꿔보는 건 어떨까요?
(다른 핸들러들도 포합입니다~)

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/test/java/org/apache/coyote/http11/SignupRequestHandlerTest.java
이번에는 Handler 관련 테스트만 추가하셨네요~
어떤 기준으로 테스트를 작성하셨나요?

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java
> +            String cookieValue = cookiePair.split(COOKIE_NAME_VALUE_DELIMITER)[COOKIE_VALUE_INDEX];
이번 기회에 상수 부분들을 전부 분리하셨네요 👍

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/catalina/Session.java
>      }
Session이 Application에서 만든 객체인 User를 알고 있는 것이 어색하네요~

세션은 서버가 클라이언트의 보통 이전 상태를 기억하기 위해서 있는 개념인데요. 여기에는 Application에서 만든 객체를 알면 안된다고 생각해요. 위브의 생각은 어떠신가요?

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/RequestHandlerMapping.java
> +        }
LMS 3단계 "3. Controller Interface 추가"에 이런 말이 있네요.
> HTTP 요청, 응답을 다른 객체에게 역할을 맡기고 나니까 uri 경로에 따른 if절 분기 처리가 남는다.
if절 분기는 어떻게 리팩터링하는게 좋을까?

이 부분에 대해서 한 번 생각해주세요! (저도 어떤 것이 좋은 방법인지는 모르겠습니다...)

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java
> +    }
메서드 사이 간격 1칸으로 줄여주세요~

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java
> +    }
[사소한 의견]
static method로 하신 이유가 있나요?
`httpRequest.getMethod().isGet()` 형식으로 사용해도 되지 않나요?

2024-09-11 04:28 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/handler/LoginRequestHandler.java
이전에 POST 요청과 GET 요청을 분리하지 않았을 때 아래와 같이 이야기해 주었죠.

> 사실 분리를 했다가. 이건 너무 과하다 싶어서 지웠습니다.
핸들러 분리를 어디까지 해야 좋을지도 애매하더라고요.

그러면 이번에는 핸들러를 분리한 위브만의 기준이 있을까요?

2024-09-11 08:16 UTC, jimi567 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java
> +    }
request 클래스에 isGet() 메소드를 추가해도 좋을 것 같네요.
그런식으로 바꿔보겠습니다.

2024-09-11 08:20 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/Session.java
>      }
조금 고민해보니 맞는 것 같습니다.
무작정 리팩터링하다보니 was와 어플리케이션 간의 경계가 흐려졌네요. 이전 코드로 수정하겠습니다.!

2024-09-11 08:22 UTC, jimi567 commented on tomcat/src/test/java/org/apache/coyote/http11/SignupRequestHandlerTest.java
일단 테스트가 절대적으로 부족해서 꾸준히 작성을 해야하는데..
당장 3단계가 리팩터링인 만큼 변경된 코드가 여전히 1,2단계의 기능적 요구사항을 만족하고 있는지를 
직접 돌려보지 않고도 확인할 수 있도록 최소한의 테스트만 작성했습니다.
리뷰받으며 꾸준히 테스트 작성하겠습니다.

2024-09-11 08:23 UTC, jimi567 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java
> +            String cookieValue = cookiePair.split(COOKIE_NAME_VALUE_DELIMITER)[COOKIE_VALUE_INDEX];
헤더 name 정도는 따로 열거형으로 빼 볼만한 것 같습니다.
중복되는 상수가 몇 개 있어서..

2024-09-11 08:34 UTC, jimi567 commented on tomcat/src/main/java/org/apache/coyote/RequestHandlerMapping.java
> +        }
요구사항을 제대로 못 봤네요..

2단계까지 방식처럼 컬렉션에 모아두고, 필터링을 하게 되면 위 코드처럼 무지성 if절 난사는 없앨 수 있을 것 같아요.
다만, lms Controller 인터페이스가
```java
public interface Controller {
    void service(HttpRequest request, HttpResponse response) throws Exception;
}
```
위 형태라서 구현체마다 컨트롤러가 request를 핸들링할 수 있는지에 대한 메소드를 빼게 됐습니다.
그렇다 보니 그냥 아무 생각 없이 편하게 if절로 분기하게 된 것 같아요.

뭔가 저 인터페이스 형식을 지키면서 이전과 같은 방식으로 필터링할 수 있게 만들려면, 
당장 떠오르는건 함수형 인터페이스랑 Map정도 활용하면 될 것 같기도 한데, 좀 더 고민해보고 리팩터링 해보겠습니다.

요구사항 제대로 안보고 pr 제출하게 돼서 죄송합니다 .

2024-09-11 12:18 UTC, jimi567 commented on tomcat/src/main/java/org/apache/coyote/RequestHandlerMapping.java
> +        }
내부에 mapper Map을 두고, Path를 통해 Controller를 매핑할 수 있도록 변경했습니다.

2024-09-11 12:28 UTC, jimi567 commented on tomcat/src/main/java/org/apache/coyote/handler/LoginRequestHandler.java
요청 받은 경로별로 컨트롤러를 분리했습니다.
착안점은  제가 Spring에서 Controller를 분류할 때,
@RequestMapping의 base url 경로별로 분류를 했었는데, 이 부분에서 착안해서 분류했습니다.

저희가 프레임워크를 개발하는건 아니지만 was에서도 리소스의 위치별로 컨트롤러를 분류하는게 적절하지 않을까? 라는 생각 기준으로 분류를 했었던 것 같아요.

2024-09-11 15:58 UTC, jimi567 commented
안녕하세요. 커찬
커찬의 리뷰를 보고 나름의 기준이지만 고쳐야 될 부분이 더 보여서 꽤나 많은 변경사항이 생겼네요.
바쁜 기간에 정말 죄송합니다..

리뷰 반영 +
전체적인 패키지 구조 변경했고 request, response 클래스에 대한 테스트도 작성했습니다.

2024-09-12 01:24 UTC, leegwichan approved these changes
위브 반영해주신 코드 잘 봤습니다!
코멘트 확인해주시고, 리뷰 반영 or 코멘트는 다음 단계 PR에 남겨주세요!

2024-09-12 01:24 UTC, leegwichan commented on tomcat/src/main/java/org/apache/coyote/handler/LoginRequestHandler.java
저는 Spring Framework 를 기준으로 생각했는데요. `@PostMapping("/login")` `@GetMapping("/login")`를 따로 메서드로 쓰다 보니까, 따로 Controller를 만들어주어야 한다고 생각했습니다.

LMS 3단계 "Controller 인터페이스 추가하기"를 참고하니 위와 같은 코드가 나오겠네요 ^^
"리소스의 위치별로 컨트롤러를 분류"하는 것도 좋은 기준이네요! 👍

2024-09-12 01:25 UTC, merged