[3 단계 Tomcat 구현하기] 레디(최동근) 미션 제출합니다.
woowacourse/java-http pull request #626
Opened 2024-09-11 16:17 UTC by reddevilmidzy

제제 안녕하세요오 
오랜만입니다 :)

리팩터링 하면서 객체 분리하고 메서드 분리하다보니 이 녀석들의 패키지 구조를 어떻게 가져가야 할지 고민이 됐습니다. 😥
자바 웹 개발 워크북을 읽고 계신거 같던데 얻은 인사이트들 공유해주세요!! (_ _)

(var 없애기로 했었지만 없애는 것보다 제제 설득해보는게 빠를 것 같아서 남겨두었습니다 ㅎ.ㅎ 이녀석은 블로그 글로 남겨볼게요)

2024-09-12 04:49 UTC, JINU-CHANG requested changes
안녕하세요 레디 이번단계도 잘 진행해주셨네요 😃

꼼꼼하게 작업해주셔서 코드보면서 많이 배웠습니다 ㅎㅎ
보면서 궁금했던 부분 남겨두었으니 확인부탁드려요~

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +        response.putHeader(HttpHeaderField.CONTENT_TYPE.getValue(), request.getContentTypeToResponseText());
왜 이부분이 필요한지 이해하기 어려워요 🥲 필요한 곳으로 옮겨주세요!

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final RequestMapping requestMapping = new RequestMapping();
RequestMapping 객체를 꼭 생성해서 사용해야 할까요? 내부 메서드를 static으로 만드는 것과 비교하면 어떤 차이점이 있을까요?

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +    public void service(final HttpRequest request, final HttpResponse response) throws IOException {
HttpResponse를 반환하는 것이 아닌 파라미터로 받은 이유가 있을까요?

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/Controller.java
> +public interface Controller {
Controller 패키지 내부에 두지 않은 이유가 궁금해요

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    private final HttpHeaders headers = new HttpHeaders();
StatusLine과 Responsebody는 존재하지 않는 건가요?? 어떻게 처리되고 있나요?? 🤔

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    private final Map<String, String> body;
requestBody는 항상 Map 형태로 저장될 수 있나요?

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/component/Path.java
> +    }
꼼꼼하게 작업해주셨네요 👍👍👍

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +        if (httpCookie.containsKey("JSESSIONID")) {
지금껏 상수화잘해주셔서 JSESSIONID는 상수화하지 않은 이유가 궁금해요.

2024-09-12 04:49 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +    }
더 깔끔하게 리팩토링해볼 수 있을것 같아요!

2024-09-12 15:36 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/Controller.java
> +public interface Controller {
interface를 패키지 상위에 위치시키고 구현체를 패키지 안에 위치시킨다면 Controller 인터페이스를 사용하는 친구들은 controller 패키지 안을 바라보는게 아니라 controller 패키지 밖을 바라보게 됩니다! 우리가 인터페이스를 사용하는 이유는 내부 구현은 알바아니고 추상화된 것에 의존하기 위함인데, 만약 controller 인터페이스를 controller 패키지에 안에 위치시킨다면 controller 인터페이스를 사용하는 클래스의 import 문에는 `import org.apache.coyote.controller.*;` 가 포함됩니다. 
열심히 인터페이스 사용해가며 추상화했지만 import 로 그 구현체들이 있는 패키지를 바라본다면 구현체를 숨긴거라고 볼 순 없을 것 같아요! 

그래서 인터페이스를 밖으로 꺼냈습니다 :)

톰캣 이친구도 인터페이스는 상위로 꺼내놓고 구현체들은 패키지 안으로 담는 형태인 것을 확인할 수 있어요! 


![image](https://github.com/user-attachments/assets/9a683138-3b73-440c-9038-624788434ac3)

![image](https://github.com/user-attachments/assets/b3b38baf-c78f-4779-9b29-00c425cb9c80)

2024-09-12 15:38 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/Controller.java
> +public interface Controller {
ProtocolHandler는 상위 패키지(org.apache.coyote)에 있고 구현체들은 하위 패키지(org.apache.coyote.http11 혹은 .ajp) 에 있는 걸 확인할 수 있어요

2024-09-12 15:38 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +        if (httpCookie.containsKey("JSESSIONID")) {
놓침 이슈... ㅎㅎ

2024-09-12 15:44 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +        if (httpCookie.containsKey("JSESSIONID")) {
변경해주었습니다! 
[커밋내역](https://github.com/woowacourse/java-http/pull/626/commits/dccc7823b9b10d11dd91942c4ea7082d0a458099)

2024-09-12 16:43 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +    public void service(final HttpRequest request, final HttpResponse response) throws IOException {
요청응답을 위한 여러 필터가 생기는 경우, 한 요청에 대해  각 필터마다 여러 설정 값들이 붙게될텐데, 이러면 response를 반환하는 형태로 구현하기가 까다롭지 않을까요?

2024-09-12 16:53 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +public class LoginController extends AbstractController implements Controller {
아앗! 예리하십니당,, 무언갈 실험하다가 놓친 부분입니다! 제거해주었습니다

2024-09-12 16:57 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +        response.putHeader(HttpHeaderField.CONTENT_TYPE.getValue(), request.getContentTypeToResponseText());
저도 어렵네요 ㅜㅜ

2024-09-13 05:11 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    private final Map<String, String> body;
아하ㅏ! text/plain 혹은 json으로 올때 Map으로 매핑할 수 없겠네요 ,,

2024-09-13 05:56 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    private final Map<String, String> body;
반영하였습니다 ! 

[커밋](https://github.com/woowacourse/java-http/pull/626/commits/7090200d2e94351c0bb692673cc017fd27025e56)

2024-09-13 06:00 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    private final HttpHeaders headers = new HttpHeaders();
toHttpResponse 메서드에서 request의 정보를 가져옵니다!

2024-09-13 06:08 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +        response.putHeader(HttpHeaderField.CONTENT_TYPE.getValue(), request.getContentTypeToResponseText());
[변경커밋](https://github.com/woowacourse/java-http/pull/626/commits/dae363de942897ffd3edeccb38db957702a1fe7e) 반영하였습니다!

2024-09-13 06:28 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final RequestMapping requestMapping = new RequestMapping();
오 객체 생성하지 않고 static method를 사용하는 것이 더 깔끔해보이네요 
Mapping 클래스는 여러개 생성될 필요가 없어 보여 private으로 생성자를 막고 static method를 사용하는 방식으로 변경했습니다 

만약 RequestMapping 도 추상화 해야하는 경우라면 객체를 만들 것 같아요오

2024-09-13 06:34 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final RequestMapping requestMapping = new RequestMapping();
좋은 의견인 것 같네요 👍

2024-09-13 06:36 UTC, JINU-CHANG commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +    public void service(final HttpRequest request, final HttpResponse response) throws IOException {
생각지 못했던 부분이네요. 확실히 필터가 생기면 Response를 파라미터로 받는게 구현하기 좋을 것 같네요!

2024-09-13 06:42 UTC, reddevilmidzy commented on tomcat/src/main/java/org/apache/coyote/controller/LoginController.java
> +    }
얍얍 반영하였습니다ㅏㅏㅏㅏ!

2024-09-13 07:06 UTC, JINU-CHANG approved these changes
레디 모두 잘 반영해주셨네요! 
생각지 못했던 부분에서 답변을 해주셔서 새로웠습니다 👍
사소한 부분에 있어 코멘트를 남겨놓았는데 4단계 미션에서 반영해도 좋을 것 같아요. 
수고많으셨습니다~!

2024-09-13 07:06 UTC, merged