[2단계- Tomcat 구현하기] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-http pull request #630
Opened 2024-09-11 19:46 UTC by slimsha2dy

안녕하세요 니코로빈.
이번 미션은 나름대로 리팩토링과 같이 진행해보고자 했는데 시간에 쫓기다보니 결국은 읽기 쉽지 않은 코드가 되어버렸네요..ㅎㅎ
그래서 이번 미션은 학습이나 동작과 관련된 리뷰 위주로 해주시면 좋을 것 같습니다!
이번에도 잘 부탁드려요 🙇

2024-09-12 07:40 UTC, robinjoon requested changes
안녕하세요 알파카!  몇가지 질문성 리뷰 남겼습니다! 구현 자체는 잘 동작하는 것 같은데, 단위테스트가 빈약한 것 같아 RC 드립니다.

2024-09-12 17:37 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Session.java
> +public class Session {
나중에 패키지를 옮기려고 했는데 놓친 부분이네요 죄송합니다ㅜ
세션은 전체 애플리케이션의 상태와 관련되어 있다고 생각해 `catalina`로 패키지를 변경했습니다.

2024-09-12 18:10 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
만들어놓고 활용하지 못하고 있었네요 😢 적용 완료 했습니다

세션 쿠키는 현재 값 외에도 만료시간, 경로 등의 정보를 추가적으로 갖고 있는 것으로 알고 있었지만 과제 요구사항에서 필수는 아니라 시간 관계 상 추가하지 못했습니다..
lms에서도 Map 형태로 구현하는 것으로 힌트를 줬기 때문에 가장 단순한 형태를 의도하셨다고 생각하기도 했구요..
아마 해당 정보들을 넣기 위해선 `Cookie` 객체의 형태가 바뀌어야 하겠네요 🙇

2024-09-12 18:24 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            response.setContentType(resourceExtension);
저도 실제 HTTP  스펙을 온전히 구현하는 것이 미션의 목표가 아니라고 생각해요. 하지만, 실제로는 어떻게 되는지 알고 구현하지 않은 거랑 모르는거랑은 다르다고 생각해서 남긴 코멘트였어요.

실제 HTTP 스팩에서는 [콘텐츠 협상](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation)이라는 과정을 통해서 제공할 리소스가 결정됩니다. 말씀하신 대로 Accept 헤더도 이것에 관여해요.

2024-09-12 19:02 UTC, robinjoon requested changes
고생 많으셨습니다 알파카! **테스트가 동작하지 않아서 RC**를 드렸어요 ㅠㅠ 이것부터 확인해주세요!

그런 김에 몇가지 학습 관점에서 생각해볼만한 포인트(제가 생각했던 포인트 + 옆 크루가 만난 문제들)을 코멘트로 남겨봤어요.

2024-09-13 02:00 UTC, slimsha2dy commented on study/src/test/java/study/FileTest.java
>      }
제 컴퓨터에선 성공했어서 몰랐는데 파일 경로에 한글이 들어가는 등의 이유로 인코딩 문제가 발생할 수도 있네요.
`Paths.get(resource.toURI())`를 활용하면 해결이 가능해 수정했습니다

2024-09-13 03:34 UTC, robinjoon approved these changes
테스트 동작하는 것 확인해서 승인합니다! 다음단계 진행하면서 코멘트 반영해주시면 될 거 같아요.

2024-09-13 03:42 UTC, merged

2024-09-13 05:41 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java
> +                });
코드 수정 했습니다~!

2024-09-13 05:41 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java
> +                .forEach(data -> parseData(data, queryString));
마찬가지로 수정했습니다!

2024-09-13 05:52 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      public void process(Socket connection) {
오.. 저도 생각 못 했던 부분인데 확인해보니 이미 미션 코드에 구현되어 있던 `Connector.stop()`에 소켓을 close하는 로직이 있었네요. 그러므로 제가 따로 추가로 관리할 필요는 없어 보이네요.

2024-09-13 05:55 UTC, slimsha2dy commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +            response.redirectPage("/index.html");
항상 일관적으로 응답에 상태 코드를 지정해주는 편이 더 직관적이라고 생각했습니다!
물론 휴먼 에러가 발생할 가능성이 있겠지만 어떤 응답을 보낼 때는 지정하지 않고 지정해야 한다면 더 헷갈릴 것 같아서요 ㅎㅎ
이에 대해선 어떻게 생각하시나요?

2024-09-14 10:32 UTC, robinjoon commented on study/src/test/java/thread/stage0/SynchronizationTest.java
>          }
syncronized 키워드를 걸 수 있는(실제로 의도대로 동작하는지와 무관하게) 선택지는 3개가 있었을 것 같아요.
- calculate 메서드
- getSum 메서드
- setSum 메서드
왜 이곳에 이 키워드를 사용했나요? 다른 사용 방식은 없을까요?

2024-09-14 10:32 UTC, robinjoon commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
>          final int expectedQueueSize = 0;
왜 이런 값으로 설정하면 테스트가 통과하나요? 각 변수들은 어떤 의미인가요?

2024-09-14 13:10 UTC, robinjoon commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +            response.redirectPage("/index.html");
302 found 응답을 내려줄때는 무조건 리다이렉트를 어디로 보낼지 같이 알려줘야 해서

response.found();
response.redirectPage("/index.html");

두 메서드는 항상 같이 호출될 거 같아요. 
response.found("/index.html");
그러면 이런 식으로 할 수 있으면 좋을 것 같네요.

2024-09-14 13:11 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      public void process(Socket connection) {
InputStream 과 OutputStream 은 꼭 닫아줘야 할까요? 🤔

2024-09-14 13:15 UTC, robinjoon commented on study/src/test/java/thread/stage1/UserServlet.java
> +    private final List<User> users = new CopyOnWriteArrayList<>();
1. 이 구현체만 사용하고 아래 작업하신 `synchronized`를 제거하면 어떻게 되나요?
2. 반대로 구현체는 원래대로 쓰고, `synchronized`만 제거하면 어떻게 되나요?

2024-09-16 16:41 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            response.setContentType(resourceExtension);
오.. 단순히 콘텐츠 타입 뿐만 아니라 여러 언어나 인코딩 등까지도 콘텐츠 협상을 통해 결정되는군요.
덕분에 좋은 공부 하고 가네요 😄 갑사합니다!

2024-09-16 17:02 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>              outputStream.flush();
`flush()`는 스트림 버퍼를 비우는 명령이므로 이미 비워져 있는 상태에서 `flush()`를 호출해도 아무런 일이 일어나지 않을 것 같네요.
실제로 코드로 실행해서 확인해봐도 변화가 없는 것으로 확인돼었는데 혹시 제가 놓친 부분이 있을까요?

2024-09-16 17:17 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      public void process(Socket connection) {
로빈의 말을 듣고 찾아보니 전혀 몰랐던 사실들이 있었네요 😮 
`InputStream`과 `OutputStream`의 경우 api를 확인해보면 `The close method of InputStream does nothing.`. 즉 아무 일도 하지 않는다고 하므로 굳이 닫을 필요는 없어 보입니다.
하지만 이 InputStream, OutputStream의 하위 클래스인 `FileInputStream` 등은 실제로 자원을 반납하는 행동이 `close()`에 있으므로 이를 고려해 항상 사용하는 편이 실수 방지에도 더 좋을 것 같습니다.

2024-09-16 17:25 UTC, slimsha2dy commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +            response.redirectPage("/index.html");
오.. 더 깔끔해지고 실수도 방지할 수 있겠네요. 해당 부분도 반영했습니다!

2024-09-16 17:36 UTC, slimsha2dy commented on study/src/test/java/thread/stage0/SynchronizationTest.java
>          }
각 스레드는 `getSum()`으로 sum의 현재 값을 확인한 후, `setSum()`으로 값을 1 더하고 있습니다.
근데 만약 이 두 메서드가 원자적으로 이루어지지 않을 경우 문제가 발생하게 되는데요.
`getSum()`, `setSum()` 메서드가 각각 동기화되어 있다고 해도, A 스레드의 두 메서드 사이에 B 스레드가 `getSum()`을 통해 값을 가져올 경우 2가 더해지지 않고 1만 더해진 잘못된 값이 나오게 됩니다.
마찬가지로 두 메서드 사이에 다른 스레드가 `setSum()` 메서드를 호출해도 같은 문제가 발생하게 되겠죠?
그래서 해당 테스트 상황에서 `synchronized` 키워드를 적용해서 해결하는 방법은 `calculate` 메서드에 적용하는 것이 일반적일 것 같습니다. 혹시 제가 놓친 부분이 있을까요?

2024-09-16 17:40 UTC, slimsha2dy commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
>          final int expectedQueueSize = 0;
변수명 그대로 스레드 풀 사이즈와 대기 큐의 사이즈를 뜻합니다.
해당 테스트에서는 `CachedThreadPool`을 사용하므로 스레드 풀의 사이즈는 메모리가 허용하는 범위 내에서 들어오는 요청만큼 늘어나게 되는데요.
테스트에선 3개의 스레드가 생성됐으므로 스레드 풀의 크기가 3이 되고, 위에서 설명했던 것처럼 대기 큐는 사용하지 않으므로 0이 될 것입니다.

2024-09-16 17:55 UTC, slimsha2dy commented on study/src/test/java/thread/stage1/UserServlet.java
> +    private final List<User> users = new CopyOnWriteArrayList<>();
2번의 `제거`를
> 반대로 구현체는 원래대로 쓰고, synchronized만 사용하면 어떻게 되나요?

라고 `사용`으로 바꿔서 설명해보겠습니다.
1. 위의 리뷰에서 설명한 것과 동일한 문제가 발생하겠네요. `join()` 메서드는 유저가 존재하는지 확인하고 나서 유저를 추가하는 기능을 하고 있는데 이를 원자적으로 실행하지 않을 경우 동일한 두 유저가 생기는 문제가 발생할 수 있게 됩니다.
2. 사실 이미 `join` 메서드에 대한 동기화가 되어 있으므로 `ArrayList`를 사용해도 정상적으로 동작이 될 것입니다. `CopyOnWriteArrayList`는 각 메서드에 대한 동기화를 지원하는 구현체이므로 해당 테스트에선 굳이 사용할 필요가 없었네요.

2024-09-16 19:24 UTC, slimsha2dy commented on study/src/test/java/study/FileTest.java
> +        final String actual = getClass().getClassLoader().getResource(fileName).getPath();
클래스 로더는 자바에서 **동적**으로 **클래스의 정보**를 `.class` **바이트코드**에서 **jvm으로** 가져오기 위한 클래스입니다.
자바는 실제로 클래스의 모든 데이터를 미리 메소드 영역에 올리는 것이 아닌, 필요할 때 메소드 영역에 올리도록 동작하는데요. 이 때 사용되는 것이 클래스 로더입니다.
클래스 로더는 필요할 때 해당 클래스를 찾아 메소드 영역에 로드하고 링크하는 기능을 합니다.
해당 코드에서는 `getClassLoader`를 통해 해당 클래스를 로드한 클래스 로더를 갖고온 후 해당 클래스패스에  존재하는 리소스를 찾아 url을 반환하고 있습니다.
클래스로더도 처음 접해봐서 선행 지식을 공부하는데 꽤나 애먹었네요.. 특히 클래스로더의 getResource는 실제 클래스 로더의 동작 방식과 연관이 되어 있는 것 같아 꽤나 딥한 내용인 것 같은데 로빈이 이에 대해 좀 더 알고 계신 부분이 있다면 공유 부탁드릴게요! 😆

2024-09-17 03:58 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>              outputStream.flush();
> `flush()`는 스트림 버퍼를 비우는 명령이므로 이미 비워져 있는 상태에서 `flush()`를 호출해도 아무런 일이 일어나지 않을 것 같네요. 실제로 코드로 실행해서 확인해봐도 변화가 없는 것으로 확인돼었는데 혹시 제가 놓친 부분이 있을까요?

아 제 말이 조금 모호했네요.

코드상의 버그로 인해서 
outputStream.write(data);
outputStream.flush();

이런 코드가 한번의 요청을 처리하는 과정에서 여러번 수행되면 무슨 일이 벌어지는지 여쭤본거였어요. 첫번째로 위 코드를 호출했을 때 전달한 데이터가 문제 없다면 클라이언트에서 이를 처리할 겁니다. 그러면 두번째 그 이후의 호출에서 어떻게 될지 다음 두가지 상황을 생각해 볼 수 있을 것 같아요.

1. 데이터가 클라이언트에 전달이 되고 무시하는지
2. 데이터가 클라이언트에 전달 자체가 되지 않는지

한발 더 나아가서 생각해보면,응답할 데이터의 크기가 매우 크거나 데이터를 생성하는데 시간이 걸리면 데이터의 일부를 미리 전송하는게 효율적이에요. 이러한 경우에는 어떻게 대응할 수 있을지 생각해볼 수 있을 것 같아요.

2024-09-17 04:05 UTC, robinjoon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      public void process(Socket connection) {
> 로빈의 말을 듣고 찾아보니 전혀 몰랐던 사실들이 있었네요 😮 `InputStream`과 `OutputStream`의 경우 api를 확인해보면 `The close method of InputStream does nothing.`. 즉 아무 일도 하지 않는다고 하므로 굳이 닫을 필요는 없어 보입니다. 하지만 이 InputStream, OutputStream의 하위 클래스인 `FileInputStream` 등은 실제로 자원을 반납하는 행동이 `close()`에 있으므로 이를 고려해 항상 사용하는 편이 실수 방지에도 더 좋을 것 같습니다.

![image](https://github.com/user-attachments/assets/bf058166-2564-4f9e-ba14-46df924bdb78)

Socket 클래스의 close 메서드의 설명을 보면 이렇게 써있어요.

> Closing this socket will also close the socket's InputStream and OutputStream.

따라서 Socket만 제대로 닫아주면 내부의 InputStream 과 OutputStream 을 자동으로 닫아줘요. 하위 객체에서 이를 잘못 오버라이딩 했을 경우도 고려한다면 알파카처럼 해주는게 조금 더 안전할 수는 있겠네요.

2024-09-17 04:11 UTC, robinjoon commented on study/src/test/java/thread/stage0/SynchronizationTest.java
>          }
좋은 말씀 해주셨네요.

현재 코드에서 얼핏 잘못 생각하면 setSum에 동기화 처리를 해주면 될 것 같지만, getSum이 먼저 호출되기 때문에 여전히 문제가 발생해요! 그리고 굳이 `synchronized`블록을 사용할 이유도 없죠. 메서드 전체가 임계영역이니까요.

 `synchronized` 키워드 말고도 자바에서 동기화를 지원하기 위한 여러 수단이 있으니까 함께 학습하시면 좋을 것 같아요. 알파카의 테크니컬 라이팅 주제인 가상 스레드와도 밀접한 관련이 있으니까요~