[3단계 - Tomcat 구현하기] 포케(이무송) 미션 제출합니다.
woowacourse/java-http pull request #643
Opened 2024-09-12 05:45 UTC by fromitive

안녕하세요 프람! 포케입니다 😄 

[1,2 단계 리뷰](https://github.com/woowacourse/java-http/pull/592) 관련해서 코멘트 남겼습니다. 주신 리뷰 중 대부분은 반영 완료했으니 확인 부탁드립니다 🙏 

패키지 구조가 엉망입니다... 이는 리뷰 반영 후 한 번에 해보겠습니다. 😃 

리뷰는 이전 단계처럼 리뷰 해주시면 될 것 같습니다 🔥 

감사합니다 🙇

2024-09-12 12:25 UTC, koust6u requested changes
안녕하세요 포케😄

1~2단계 반영한것 잘 읽어봤습니다. 
열심히 하셨네요.

우선 포케가 구현한 애플리케이션이 정상 작동하지 않습니다. 
한번 확인해주시고 다시 요청해세요.

그리고 몇가지 단순한 질문 남겨봤어요.

2024-09-12 12:25 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> -    private String body;
[질문]
필드들을 가변하게 만든 이유가 있나요? 불변 객체로 만들면 어떤 이점이 있을까요?

2024-09-13 01:35 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +    private Map<String, MethodHandler> methodMapping = new HashMap<>();
hashMap은 seperate chaining 방식으로 해시 충돌을 완화한다고 하네요

키 충돌이 발생하게 되면 , 충돌된 키를 같은 버킷 안에 연결리스트 구조로 저장한다고 합니다~~

key와 key2가 해시 함수 충돌이 발생했다면, 조회 과정은 아래와 같이 이루어 진다고 합니다~
   1. get("key") 또는 get("key2")를 호출하면, 먼저 해시 함수를 통해 둘 다 같은 버킷(인덱스)을 가리키게 됩니다
   2. 리스트의 각 노드를 순차적으로 확인하면서, 저장된 키(key 또는 key2)와 조회한 키가 일치하는지 비교하고 값을 획득합니다

2024-09-13 06:18 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java
>      private void validateRequestPartLength(String[] requestPart) {
배열을 공변성을 가지고 있어 상위 타입으로 초기화가 가능하지만 컬렉션은 상위 타입으로 초기화할 때 컴파일 단에서 오류를 쉽게 찾을 수 있다는 이점을 가지고 있습니다..! 해당 배열을 컬랙션으로 변경 하겠습니다 😃

2024-09-13 06:24 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequestHandler.java
>  import org.slf4j.Logger;
반영 완료했습니다!!

2024-09-13 06:33 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> -    private String body;
불변객체로 만들어주면 값을 예측할 수 있기 때문에, 어플리케이션의 안정성이 높아지는 이점이 있으나, 미션 요구사항 중 메서드 타입이 고정되어 있어 HttpRequest에서 HttpResponse를 만들어주지 못합니다. (`void handle(HttpRequest rerquest, HttpResponse respone)`)

따라서 HttpResponse는 사전에 생성되기 때문에 MethodHandler에서 처리된 결과값을 받기 위해서 불변하게 만들 수 없었습니다.

2024-09-13 06:48 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
>      }
미션 요구사항에 따라 HttpResponse를 먼저 생성해줘야만 했고, 가독성을 위해 세터를 설정하기보다. 체이닝을 채택하게 되었습니다 😃 
미션 요구사항의 메서드 타입으로 인해 HttpResponse를 바로 생성하진 못했습니다 ..

2024-09-13 06:56 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/RequestReader.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
inputstream을 닫게 되면 socket까지 닫히는 상황이 있어 프로그램에 오류가 발생했습니다 try-with-resource는 `Http11Processor`에만 적용시킨 상태입니다 😭

2024-09-13 07:00 UTC, fromitive commented
안녕하세요 프람..! 포케입니다 😃 

리뷰 코멘트에 대한 답변 드렸으나 반영은 많이 하지 못했습니다. 😢 

자세한 건 코멘트를 확인해주시면 될 것 같습니다..!

또한 오늘 진행한 학습 테스트 리뷰도 부탁 드리겠습니다

[feat: thread 학습 테스트](https://github.com/woowacourse/java-http/pull/643/commits/67a5bbb91f9bde8880f39c135fcefb91dc9223bc)

화이팅이에요 🔥

2024-09-13 07:04 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/AbstractController.java
> +    private Map<String, MethodHandler> methodMapping = new HashMap<>();
네~ 잘 알아보셨네요.
정확하게 Java util hashMap은 버킷이 8개 이상으로 늘어나면 RB tree로 구조를 변경시켜서 해결합니다.
 알쓸크자(**알**아**두**면 **쓸**데있가 있을지도  모르는 **자**바 지식) 😅

2024-09-13 07:12 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> -    private String body;
아하! 좋습니다. 스펙이 정해져있으면 따라야하죠👍

2024-09-13 07:38 UTC, koust6u requested changes
안녕하세요. 포케 거의 마지막까지왔네요.
바쁘다 바뻐!! 🏃‍♂️
조금만 더 힘냅시다.

마감 얼마 안남아서 피드백 주기 짧게 가져갈게요.
피드백 주시면 빠르게 확인하겠습니다.

2024-09-13 07:38 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        if (!sessionId.isEmpty()) {
[요청]
이 친구 때문에 어떤 버그가 애플리케이션에서 발생하는지 찾아주세요

2024-09-13 07:38 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        if (!sessionId.isEmpty()) {
[질문]
쿠키는 뭐고 
세션은 어떻게 관리될까요?

2024-09-13 07:38 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +public class LoginController extends AbstractController {
[요청]
전반적으로 Controller에 대한 테스트가 부족하네요. 몇가지 케이스라도 추가해주세요. 혹시 어려움이 있다면 DM으로 비동기 통신합시다 🔥

2024-09-13 07:38 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +public class LoginController extends AbstractController {
[질문]
Controller들이 왜 Coyote 패키지에 있을까요?
Coyote와 Catalina 역활은 뭘까요?

2024-09-13 07:38 UTC, koust6u commented on tomcat/src/main/java/org/apache/coyote/http11/exception/RequestException.java
> +public class RequestException extends RuntimeException {
[질문]
요 친구는 request 과정에서 생기는 모든 예외를 의미할까요?

2024-09-13 07:39 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        if (!sessionId.isEmpty()) {
이부분 때문에 Null일경우에도 로그인이 성공하네요 수정하겠습니다!!

2024-09-13 07:40 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +public class LoginController extends AbstractController {
Catalina가 Socket 커넥션을 담당하는 녀석이고

Coyote가 Http요청을 분석하고 Controller를 처리하는 역할이라고 생각합니다..! 

테스트 5시까지 보강해보겠습니다..!

2024-09-13 07:42 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/exception/RequestException.java
> +public class RequestException extends RuntimeException {
Client 요청에서 발생하는 예외로 정의했으나, 네이밍을 좀 더 디테일하게 가져가겠습니다!

2024-09-13 07:56 UTC, merged