[3단계 - Tomcat 구현하기] 테니(나아연) 미션 제출합니다.
woowacourse/java-http pull request #644
Opened 2024-09-12 06:18 UTC by ay-eonii

안녕하세요 위브! 테니입니다 ☺️

4단계는 금요일 강의를 듣고 수행하는 게 좋을 것 같아 3단계 먼저 진행 후 리뷰 요청드립니다. :)
Cache 테스트를 포함해 지난 리뷰에서 빠진 File/IOStream 테스트를 포함했습니다.

**지난 리뷰를 반영 사항**
- 항상 OK를 내려주던 StatusMessage를 Code에 따라 변경했습니다.
- try-with-resource로 BufferedReader 자동 반납

**미션 3 요구사항**
- reponse 리팩토링
  - 분산되어 있던 response 생성 역할 Controller 로 변경
  - response에서 사용되는 객체 분리 (StatusLine, Content-Type...)

잘 부탁드립니다🙇‍♀️

2024-09-13 05:57 UTC, jimi567 requested changes
테니 고생하셨어요.
테스트 코드도 많이 작성해주셨네요~
 반영 or 답변 주시고 다시 리뷰 요청 주세요~
최대한 빠르게 보겠습니다.

많이 바쁠텐데 화이팅입니다.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/Cookie.java
> +    }
response message 만들기 위해서 override하신 것 같습니다.
전 httpResponse의 형태로 만드는 것도 기능의 하나라고 생각해서 따로 메서드를 만드는 편이고, toString은 디버깅 용도로만 사용합니다.
테니는 이 부분 어떻게 생각하시나요? 


"=", "," 이 각 문자열이 무얼 의미하는지, http response msg 형태를 잘 모르는 사람이라면 이해하기 어려울 것 같아요.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/HelloWorldController.java
> +public class HelloWorldController extends MappingController {
controller 구현체 위치가 웹 서버 내부에 있는건 어떻게 생각하시나요?

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +public class RegisterController extends MappingController {
컨트롤러가 웹 서버 내부에 있는 것은 위 코멘트 참고해주시고..
컨트롤러가 웹 서버에서 관리된다면, db나 User같은 어플리케이션에 의존성이 생기면 안될 것 같아요.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/response/ContentType.java
> +    HTML("text/html;charset=utf-8"),
text/html MimeType에 대해서는 무조건 인코딩 방식이 utf-8이 되겠네요?

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/response/HttpResponse.java
> +        }
파일을 읽는 책임을 response 객체에 두게 된 이유가 궁금합니다.

2024-09-13 05:57 UTC, jimi567 commented on study/src/test/java/study/IOStreamTest.java
> +            }
테스트 코드긴한데 이왕이면, 뎁스 2 미만으로 유지해야 된다는 습관은 길들이면 좋을 것 같네요.
(저한테도 하는 소리입니다.)

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +import org.apache.catalina.session.SessionManager;
저도 Session은 웹 서버에 있어야되나, 애플리케이션에 있어야 되나 고민이 엄청 되더라고요.
테니는 어떤 근거를 가지고 웹 서버에 두게 되었나요?

그리고 SessionManager는 저의 경우 어플리케이션에서 세션 저장하는 일종의 db같은거라고 생각했습니다.
테니의 생각이 궁금합니당

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/HandlerAdapter.java
>      );
해당 was를 사용하는 어플리케이션은 Map에 key에 해당하는 각 요청에 대해 정해진 핸들러대로 동작하겠네요.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/Controller.java
> +    void service(HttpRequest request, HttpResponse response);
왜 LMS에서 service 시그니처를 이렇게 두었을까요?
저도 미션하면서 이 부분이 의문이 였습니다.
여기에 대한 테니의 식견이 궁금합니다.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +        response.forward("/login.html");
세션이 있다면 /index.html로 리다이렉트 해주고...
아니라면 login.html을 내려준다. 라는 기능은 요구 사항에 따라 바뀔 수 있다고 생각합니다.
이런 문자열 상수로 빼면 좋을 것 같아요.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +    }
메서드 길이 잘하면 줄일 수 있을 것 같기도...?

"JSESSIONID"..?

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/response/ContentType.java
> +}
위 코멘트 참고해주세요.

2024-09-13 05:57 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/response/ContentType.java
> +    }
Http Request에 오는 Accept 헤더는 뭘 의미할까요?

2024-09-13 08:28 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/Cookie.java
> +    }
맞아요.. 사실 작성하면서 좀 망설인 부분이었습니다. 따로 메서드를 작성하는 게 좋겠네요! 감사합니다

2024-09-13 08:28 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/response/ContentType.java
> +    HTML("text/html;charset=utf-8"),
넵 ㅎ..ㅎ 현재에 집중하다보니 mimeType은 후순위가 되었습니다...

2024-09-13 08:43 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/response/ContentType.java
> +    }
공부해보겠습니다

2024-09-13 08:49 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +public class RegisterController extends MappingController {
저도 처음에 application의 controller 를 생각하고 패키지를 분리하여 웹 서버와는 의존성이 생기지 않도록 했어요. 그런데 지금 공부하는 건 저희가 보통 구현하는 controller 가 아니기에 servlet 을 생각하면서 이 곳에 두었습니다. 여기에 의존성이 생기지 않으면 application에서는 저희가 사용하던 방식의 
```java
 HttpResponse execute(HttpRequest httpRequest) throws IOException;
```
위 처럼 작성해야할 것 같아요. 이렇게 된다면 application의 controller 를 위한 DTO 를 또 만들어야 할 것 같고.. 공수가 너무 많을 것 같아 의존성이 있더라도 이렇게 작성했습니다.

2024-09-13 08:51 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +import org.apache.catalina.session.SessionManager;
위에서 servlet으로서의 controller 를 말씀드린 대로, 웹 서버에 집중해서 여기에 두었습니다. 그리고 apache 패키지를 보니 catalina에 session이 있길래 ㅎㅎ... 여기두었습니다.

2024-09-13 08:52 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/controller/Controller.java
> +    void service(HttpRequest request, HttpResponse response);
Servelt의 포맷이라 그런 거라 생각하고 저는 그냥 받아들였습니다. .. ㅋㅋ ㅠㅠ
만약 response를 반환하고 싶으면 application에서 controller 를 또 만들었을 것 같아요!

2024-09-13 08:52 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/controller/HelloWorldController.java
> +public class HelloWorldController extends MappingController {
아래오ㅏ 같은 맥락이라고 생각해요!

2024-09-13 08:54 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/response/HttpResponse.java
> +        }
파일을 읽으면서 repsonse에 세팅되는 값이 많아 response가 가져도 이상하지 않다고 생각했어요 ㅎ..ㅎ

2024-09-14 20:40 UTC, jimi567 commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +public class RegisterController extends MappingController {
저 또한 테니처럼 저희가 구현하는건 컨트롤러가 아닌 서블릿이라고 생각해요.
그래서 왜 LMS에서 컨트롤러라는 이름으로 해당 시그니처를 제공 했는지 좀 궁금하긴 하네요..(내가 잘못 알고 있나?)

하지만, 서블릿이라고 생각해도 구현체의 위치에 대한 생각은 좀 다른데요.
지금 구조는 해당 was를 통해 어플리케이션을 개발하게 될 경우 모든 어플리케이션이 정해진 경로에 대해서("/login" 등) 테니가 구현해주신 서블릿대로 동작할 것 같습니다. 물론 홈 디렉터리에 대한 요청이나, 클라이언트 개발자가 정한 경로에 없는 요청에 대한 응답처리는 was가 해줘도 될 것 같다 생각합니다.

하지만 /login 이나 /register 같은건 좀 얘기가 다르지 않을까 싶네요.
애초에 서블릿이라는 것이 톰캣이 정한 HttpServlet 스펙대로 클라이언트 개발자가 구현하는거 아닐까요?
was는 개발자가 구현한 서블릿의 생명 주기나 경로에 대한 서블릿의 매핑 등을 해주는 것이고요.

테니가 구현해주신 서블릿이 was 내부에 있어서 was가 어플리케이션의 db나 모델을 의존하게 되는 상황이 발생하게 되는 것 같아용.

2024-09-15 00:52 UTC, ay-eonii commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +public class RegisterController extends MappingController {
아아 제가 위에서 드린 시그니처에 대해 설명을 빈약하게 했네요😢 시그니처는 **반환값이 있다**는 것에 초점을 두었던 것이고, 실제 의존성을 해결하는 방법은 위에서 언급했던 **DTO**를 적용한 모습인 아래를 생각하면서 의견 드렸어요 ㅠㅠ
```java
ResponseDto execute(RequestDto requestDto) throws IOException;
```

---
이와는 별개로 
> 물론 홈 디렉터리에 대한 요청이나, 클라이언트 개발자가 정한 경로에 없는 요청에 대한 응답처리는 was가 해줘도 될 것 같다 생각합니다.
하지만 /login 이나 /register 같은건 좀 얘기가 다르지 않을까 싶네요.
애초에 서블릿이라는 것이 톰캣이 정한 jakarta의 HttpServlet 스펙대로 클라이언트 개발자가 구현하는거 아닐까요?
톰캣은 개발자가 구현한 서블릿의 생명 주기나 경로에 대한 서블릿의 매핑 등을 해주는 것이고요.

위브의 말씀대로 서블릿을 구현한다고 해서 비즈니스 로직까지 서블릿 단에 있는 게 더 이상한 것 같네요. application단에서 개발자가 HttpServlet 스펙대로 구현하면서 DB 나 도메인에 대한 의존성은 분리해주는 게 적절한 절충안이라고 생각해요.

위브 의견 많은 도움이 되었어요! 정말 감사합니다 😊

2024-09-15 01:06 UTC, jimi567 approved these changes
3단계 고생하셨어요 테니~ 
덕분에 저도 식견이 넓어진 것 같습니다.
4단계에서 뵙겠습니다.

2024-09-15 01:06 UTC, merged