[3단계 - Tomcat 구현하기] 도도(김도선) 미션 제출합니다.
woowacourse/java-http pull request #649
Opened 2024-09-12 08:14 UTC by ehtjsv2

안녕하세요 카고~! 3단계 마무리했습니다
리뷰 잘 부탁드립니다!

2024-09-12 12:51 UTC, devhoya97 requested changes
안녕하세요 도도~ 
클래스의 책임 분리가 전체적으로 잘 되어 있어서, 객체들의 협력이 잘 드러나는 것 같아요 👍
클래스 분리하신 것 보고 많이 배웠습니다!
간단한 코멘트 몇 개 남겼는데 확인해주시면 감사하겠습니다!

추가로,
1. 이전 리뷰에서 제가 학습테스트를 확인하지 못했어요. FileTest와 IOStreamTest가 통과하지 못하고 있는데, 확인 부탁드릴게요!
2. 클래스를 분리했기 때문에 기존 Http11ProcessorTest라는 큰 단위의 테스트에서 모든 예외 케이스를 검증할 필요 없이, 각 클래스에서 단위테스트로 여러 시나리오를 테스트해볼 수 있을 것 같아요. 다만 당장 내일이 미션 마감일이기 때문에 어느 정도로 테스트 코드를 추가할 것인지는 도도의 선택에 맡기겠습니다!! (저도 시간에 쫓겨서 미처 작성하지 못한 테스트가 엄청 많네요 🥲)

다음 리뷰 요청 주시면 빠르게 Approve 드릴게요!

2024-09-12 12:51 UTC, devhoya97 commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +                        () -> loginFail(response)
loginSuccess와 loginFail은 processLogin 바로 뒤에 두는게 더 찾기 쉬울 것 같은데 어떻게 생각하시나요?!

2024-09-12 12:51 UTC, devhoya97 commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +                .ifPresentOrElse(
if 문 depth도 줄고, 가독성도 엄청 좋네요 👍

2024-09-12 12:51 UTC, devhoya97 commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +    private final String JAVA_SESSION_ID = "JSESSIONID";
질문 : LoginController에도 똑같은 상수가 지정되어 있던데, AbstractController에 protected로 상수를 모아주는건 어떨까요?!

2024-09-12 12:51 UTC, devhoya97 commented on tomcat/src/test/java/org/apache/coyote/http11/processor/Http11ProcessorTest.java
> +        assertThat(socket.output()).contains(ROOT_LOCATION);
POST /login 요청이 성공했을 때, output에 "http://localhost:8080/\r\n"라는 문자열이 포함되어 있는지만 확인하는 것 같아요.

가능하다면,
1. Set-Cookie 헤더가 JSESSION값을 셋팅해주고 있는지
2. default 페이지의 내용이 response에 포함되어 있는지

를 확인할 수 있다면 좋을 것 같아요!

2024-09-12 23:51 UTC, ehtjsv2 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestBody.java
> +package org.apache.coyote.http11.request;
리팩토링 하면서 contentType을 이상하게 명시해버렸네요,, test작성해서 리팩토링후에도 확실하게 확인되도록 하겠습니다

2024-09-12 23:56 UTC, ehtjsv2 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestBody.java
> +    }
음 저는 해당 메세지를 받으면 정해진 FormUrlEncoded양식이 무엇인지 검색해볼 것 같아요! 보통 저희가 에러를 마주치면 검색부터 하는 것처럼!
어떤 양식인 지까지 알려줘야한다면, 너무 많은 정보를 줘야할 것 같기도해요!
좋은 의견 감사합니다~!

2024-09-13 00:00 UTC, ehtjsv2 commented on tomcat/src/test/java/org/apache/coyote/http11/processor/Http11ProcessorTest.java
> +        assertThat(socket.output()).contains(ROOT_LOCATION);
테스트가 좀 더 다양해지면 좋겠네요!
저는 해당 테스트는 redirect가 잘하는가에 대한 테스트이기때문에, 요청하신 두개의 테스트를 따로 만드는 것이 더 좋을 것 같아요!

2024-09-13 00:07 UTC, ehtjsv2 commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +                        () -> loginFail(response)
저조차도 다시 보니 찾기 어려웠네요. 바로 밑에두면 흐름대로 읽기 좋을 것 같아 위치 수정했습니다!

2024-09-13 00:08 UTC, ehtjsv2 commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +    private final String JAVA_SESSION_ID = "JSESSIONID";
좋은 생각인 것 같아요!
둘 다 특정 Controller의 종속된 상수가 아니기에, 모아도 좋을 것 같네요~!

2024-09-13 00:34 UTC, ehtjsv2 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeader.java
> +    }
이 부분은 확실히 명확한 메세지가 사용자에게 더 친절하네요! 변경하겠습니다!

2024-09-13 00:36 UTC, ehtjsv2 commented
카고 다양하고 좋은 리뷰 감사합니다~! 재밌게 리뷰반영할 수 있었습니다!

2024-09-13 01:00 UTC, devhoya97 approved these changes
반영된 것 확인했습니다!! 마지막 단계로 가보시죠!!!

2024-09-13 01:01 UTC, merged