[톰캣 구현하기 3단계] 트레 미션 제출합니다.
woowacourse/java-http pull request #650
Opened 2024-09-12 08:17 UTC by takoyakimchi

안녕하세요 포케!

### 3단계에서는 아래와 같은 부분들에 집중하여 구현했어요.
- 2단계 마지막 리뷰 반영
- `org.apache` 패키지가 `com.techcourse` 패키지에 의존하지 않도록 리팩터링
- 애플리케이션의 구현이 달라져도 톰캣 코드를 그대로 사용할 수 있도록 변경
- 문자열과 매직 넘버 상수화
- 예외가 발생할 수 있는 부분을 더 견고하게 처리
- E2E 테스트 추가

리뷰 잘 부탁드립니다!

2024-09-12 15:32 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java
> +        return headers.keySet().stream().map(key -> key + DELIMITER + " " + headers.get(key))
[반영하지 않으셔도 됩니다]
`keySet`을 사용하셨군요 😄 `entrySet`을 사용해보는건 어떻게 생각하시나요?

```suggestion
        String RESPONSE_HEADER_FORMAT = "%s: %s";
        // ... 중략 ...
        return headers.entrySet().stream()
                .map(entry -> RESPONSE_HEADER_FORMAT.formatted(entry.getKey(), entry.getValue()))
                .collect(Collectors.joining(CRLF));
```

2024-09-12 16:34 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java
> +        return headers.keySet().stream().map(key -> key + DELIMITER + " " + headers.get(key))
hoxy genius?

2024-09-13 00:01 UTC, fromitive commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +        sessionManager.add(sessionId, session);
sessionManager 가 저장한 sessionId를 반환해주면 어떨까요?
```suggestion
        String sessionId = sessionManager.storeSession(session);
```

2024-09-13 00:05 UTC, fromitive commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +        String password = requestBody.get(PASSWORD_FIELD_NAME);
이것까지는 굳이,, 매직 변수로 뺄 필요는 없어보이긴 합니다. 매직변수로 뺀 이유가 있을까요?
---
requestBody.get 하기 보다는 `파라미터`를 뜻하는 객체를 반환해보는건 어떨까요?

2024-09-13 00:06 UTC, fromitive commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +            String sessionId = saveSessionAndGetSessionId(user);
single responsibility principle 원칙을 지켜볼까요 😃

2024-09-13 00:08 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/controller/DefaultController.java
> +    private static final String EMPTY_PATH = "/";
빈 값을 뜻하는 `EMPTY_PATH` 보다는, 최상단을 뜻하는 `ROOT_PATH` 가 적절해보여요!

2024-09-13 00:16 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/controller/DefaultController.java
> +            fileName += HTML_SUFFIX;
이 부분만 보면 봐서는 static 자료(`js`,`css`)도 html_suffix가 적용되는 것처럼 해석이 됩니다 

실제로 localhost:8080/404 하면 404페이지도 나오구요
parseFilename 부분과, setStaticResource 부분을 static 자료까지 처리하도록 변경하는 건 어떨까요?

2024-09-13 00:19 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private HttpRequest readRequest(BufferedReader reader) throws IOException {
`readRequest` 부터 `readRequestBody`는 객체로 묶어도 되겠는데요?

2024-09-13 00:23 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java
> +            throw new CoyoteException("쿠키의 이름은 중복될 수 없습니다.");
의도는 명확해서 좋았습니다 😄  그러나, 쿠키의 이름이 중복된다고 해서 웹서버가 오류를 반환하진 않습니다 😃

2024-09-13 00:28 UTC, fromitive commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java
> +        }
HttpRequest에선 [`Date` 헤더가 있습니다](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date)

Delimiter에 `:` 존재여부를 검증하기 보다는 일단 쪼갠 후 적절한 값이 들어 있는지 확인하는 로직을 작성해보는 건 어떨까요?

Rfc2616 문서에 message-header 부분 참고 해보시죵 ㅎㅎ

2024-09-13 00:34 UTC, fromitive commented on tomcat/src/test/java/org/apache/coyote/http11/HttpCookieTest.java
> +                .hasMessage("쿠키의 이름은 중복될 수 없습니다.");
테스트에서 예외가 발생하는 것 보다, 쿠키가 중복되었을때 `a`, `b` 중 어떤 것이 반환된다는 걸 전달해보는건 어떻게 생각하나요? 😄

2024-09-13 00:40 UTC, fromitive requested changes
안녕하세요 트레 🏃,  포케입니다. 😄 

테스트를 꼼꼼히 작성해주셨고 검증하는 로직이 구체적이라 많이 배울 수 있었습니다 😄 

몇 가지 코멘트 남겼으니 확인 부탁드립니다. 코멘트 중 생각이 다르다면 반박 부탁드립니다. 😄 

감사합니다 🙇

2024-09-13 01:24 UTC, takoyakimchi commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +        sessionManager.add(sessionId, session);
다시 보니 외부에서 세션의 동작을 너무 많이 알고 있었네요.

2024-09-13 01:37 UTC, takoyakimchi commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +        String password = requestBody.get(PASSWORD_FIELD_NAME);
문자열 관리 포인트가 한 곳에 밀집되어서 변경에 용이하고, 다른 개발자가 문자열을 하드코딩하다가 오타를 내면 동작에 문제가 생기기 때문에 이것을 미연에 방지하는 효과도 있다고 생각해요.

2024-09-13 05:44 UTC, takoyakimchi commented on tomcat/src/main/java/com/techcourse/controller/RegisterController.java
> +            String sessionId = saveSessionAndGetSessionId(user);
세션 말씀하시는 거면 sessionManager가 처리하도록 옮겼습니다!

2024-09-13 05:50 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/catalina/controller/DefaultController.java
> +            fileName += HTML_SUFFIX;
js, css 파일은 Request URI에 `.`이 포함되어 있기 때문에 html suffix가 적용되지는 않습니다.
그렇다고 하더라도 말씀하신 대로 `/404` -> `/404.html` 응답은 어색한 것 같네요.

2024-09-13 05:52 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private HttpRequest readRequest(BufferedReader reader) throws IOException {
`HttpRequest` 안에서 BufferedReader를 의존하게 하는 건 어색할 것 같아요...!

2024-09-13 06:13 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/catalina/controller/DefaultController.java
> +            fileName += HTML_SUFFIX;
반영했습니다!

2024-09-13 06:17 UTC, takoyakimchi commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java
> +        }
substring을 사용하여 처음에 등장하는 `:`를 기준으로 field-name과 field-value를 파싱하고 있기 때문에 Date가 들어와도 크게 상관 없을 것 같아요. `:`이 없으면 invalid 하기도 하구요!

2024-09-13 06:18 UTC, takoyakimchi commented on tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
> +    void defaultPath_RedirectToIndex() {
리다이렉트하는 게 자연스러운 것 같아서 이렇게 구현했어요~~!
예시로는 hello world가 나오기는 했지만 레벨1, 2 때처럼 판단에 맞게 구현하면 될 거라고 생각했어요 ㅎㅎ

2024-09-13 07:32 UTC, fromitive commented on tomcat/src/test/java/org/apache/coyote/http11/HttpCookieTest.java
> +        assertThat(httpCookie.buildMessage()).containsOnlyOnce("=");
a 나  b중어떤게 나올까요 😄

2024-09-13 07:33 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +        return id;
👍

2024-09-13 07:34 UTC, fromitive requested changes
트레 거의 다왔어요~ 

쿠키 값이 중복될 경우 어떤 값을 추출하는지만 테스트 해주세요

화이팅입니다 🔥

2024-09-13 07:46 UTC, takoyakimchi commented on tomcat/src/test/java/org/apache/coyote/http11/HttpCookieTest.java
> +        assertThat(httpCookie.buildMessage()).containsOnlyOnce("=");
가장 나중에 써있는 쿠키만 사용하는 방식을 채용했는데 테스트가 부실했네요~~!!

2024-09-13 07:47 UTC, merged

2024-09-13 07:47 UTC, fromitive commented
트레 고생 많으셨습니다!

나머지 이야기는 다음 단계에서 진행하시죠!!