[4단계 - Tomcat 구현하기] 시소(신지송) 미션 제출합니다.
woowacourse/java-http pull request #682
Opened 2024-09-13 05:50 UTC by shin-jisong

안녕하세요 레모네! 🍋
시간상의 이유로 리팩토링과 테스트를 완전하게 작성하지 못했어요
레모네와 리뷰를 주고받으며 보충해 나가겠습니다
(오늘 저녁에 보충 예정입니다 😖)

레모네도 미션 마감 파이팅입니다!

2024-09-14 05:51 UTC, JiHyeonL requested changes
안녕하세요 시소!!
추석 잘 보내고 계신가요~😎
이번 단계에서는 피드백 드릴 부분이 많지 않았어요. 고생 많으셨네요 👍👍

테스트 추가해 주시고, 3단계 때 드렸던 피드백 & 4단계 피드백 반영해 주신 뒤 
다시 리뷰 요청 부탁드립니다!

2024-09-14 05:51 UTC, JiHyeonL commented on study/src/test/java/thread/stage2/AppTest.java
> +        assertThat(count.intValue()).isEqualTo(10);
시소가 어떤 스레드 테스트를 하셨는지 궁금한데요?!ㅎㅎ

2024-09-14 05:51 UTC, JiHyeonL commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +            response.setPath("/index.html");
현재 `SessionManager` 클래스에서 `Session` 컬렉션에 여러 스레드가 동시에 접근할 수 있는 것 같아요.
동시성 보장을 위해 `동시성 컬렉션(Concurrent Collections)`을 적용해 주세요.

2024-09-14 05:51 UTC, JiHyeonL commented on study/src/main/resources/application.yml
> +      max: 10
각 속성의 의미가 무엇인지 시소만의 언어로 설명해 주세요!😀

2024-09-14 05:51 UTC, JiHyeonL commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +            final int checkedAcceptCount = checkAcceptCount(Connector.ACCEPT_COUNT);
acceptCount 인자값을 사용하는 대신,
상수값  `ACCEPT_COUNT = 25` 을 사용하신 이유가 궁금해요!
+) ACCEPT_COUNT를 25로 설정하신 이유는 무엇일까요?

2024-09-14 05:51 UTC, JiHyeonL commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(final int port, final int acceptCount, int maxThreads) {
사소하지만, maxThreads 파라미터에도 final을 붙여주세요!

2024-09-14 18:21 UTC, shin-jisong commented on study/src/test/java/thread/stage2/AppTest.java
> +        assertThat(count.intValue()).isEqualTo(10);
혹시 App Application을 실행하고 실행해 보셨나요?!
제 환경에서는 문제가 없어서 여쭤 봅니다 ㅎㅎ

2024-09-14 18:24 UTC, shin-jisong commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +            response.setPath("/index.html");
ConcurrentHashMap을 사용해 주는 것으로 변경해 주었습니다 👍

2024-09-14 18:26 UTC, shin-jisong commented on study/src/main/resources/application.yml
> +      max: 10
```
server:
  tomcat:
    accept-count: 10 // 대기열에 있을 수 있는 개수
    max-connections: 10 // 최대 요청을 보낼 수 있는 개수
    threads:
      min-spare: 1 // 연결하지 않고 예비로 둘 최소 스레드 개수
      max: 10 // 최대 스레드 수
```

로 이해하고 테스트를 진행해 보았습니다!

2024-09-14 18:28 UTC, shin-jisong commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +            final int checkedAcceptCount = checkAcceptCount(Connector.ACCEPT_COUNT);
설정에 관련된 정보는 상수로 관리하는 것이 좋겠다 판단하였습니다!
MAX_THREAD와 ACCEPT_COUNT 모두 톰켓에서 사용한 값을 참고하여 사용했는데요,
 application의 성능을 유지할 수 있는 정상 동작의 범위라고 생각하였습니다!

2024-09-14 18:30 UTC, shin-jisong commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(final int port, final int acceptCount, int maxThreads) {
반영하였습니다!

2024-09-15 18:46 UTC, shin-jisong commented
안녕하세요 레모네!
남겨 주신 리뷰에 대한 코멘트 및 반영 진행하였습니다 👍
지난 리뷰에서 시간상 반영하지 못한 리뷰 혹은 리팩토링도 진행하였어요 😊
어느덧 새로운 미션을 시작하는 요일이 다가왔네요 파이팅... 입니다!

2024-09-16 06:54 UTC, JiHyeonL commented on study/src/test/java/thread/stage2/AppTest.java
> +        assertThat(count.intValue()).isEqualTo(10);
아핫.. 제가 실수했네요 죄송합니다😢

2024-09-16 06:54 UTC, JiHyeonL approved these changes

2024-09-16 06:55 UTC, JiHyeonL commented
시소 이번 미션 수고 많으셨고, 이만 머지하겠습니다!
다음 미션도 화이팅이에요 👍👍

2024-09-16 06:55 UTC, merged