[4단계 - 동시성 확장하기] 배키(백은희) 미션 제출합니다.
woowacourse/java-http pull request #688
Opened 2024-09-13 06:27 UTC by ehBeak

알파카 안녕하세요~~🦙

마지막 단계 제출합니다~ 편하게 리뷰해 주세요!

미션하시느라 고생 많으셨고, 추석 연휴 즐겁게 보내세요~!!😊

2024-09-16 15:39 UTC, slimsha2dy requested changes
안녕하세요 배키!
이번 리뷰에선 나눠보고 싶은 주제에 대해 남겨봤습니다.
학습 테스트 및 테스트 코드 전부 잘 돌아가는 것 잘 확인했고 다음 리뷰 보내주시면 approve 하겠습니다.
이번 미션 진행하시느라 수고 많으셨습니다!

2024-09-16 15:39 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/catalina/servlet/http/SessionManager.java
> +    private static final Map<String, Session> session = new ConcurrentHashMap<>();
`ConcurrentHashMap`을 통해 동시성을 해결하셨네요.
어떤 방법을 통해 `HashMap`과는 달리 thread-safe한지 알고 계신가요?

2024-09-16 15:39 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/catalina/servlet/http/SessionManager.java
> +    public static synchronized SessionManager getInstance() {
동시에 접근해서 여러 인스턴스가 생길 수 있는 부분을 방지해 주셨네요. 👍 
그런데 혹시 `synchronized` 키워드를 사용했을 때의 단점은 무엇이 있을까요?

2024-09-16 15:39 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREADS_COUNT = 200;
200개로 정하신 이유가 있으실까요?

추가질문) lms 생각해보기 항목인 `최대 ThradPool의 크기는 250, 모든 Thread가 사용 중인(Busy) 상태이면 100명까지 대기 상태로 만들려면 어떻게 할까?`를 해결하기 위해선 값을 어떻게 조정해야 할까요?(반영할 필요는 없고 질문입니다)

2024-09-16 15:39 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int DEFAULT_ACCEPT_COUNT = 100;
acceptCount는 어떤 의미를 갖고 있나요?

2024-09-17 04:41 UTC, ehBeak commented on tomcat/src/main/java/org/apache/catalina/servlet/http/SessionManager.java
> +    private static final Map<String, Session> session = new ConcurrentHashMap<>();
`HashMap`은 동시성을 보장하지 않습니다. `HashMap`을 동기화된 맵으로 감싸서(`Collections.synchronizedMap()`) 동시성을 해결할 수도 있지만, 모든 메서드에 `synchronized` 키워드를 붙이면 하나의 스레드만이 map에 접근할 수 있어 성능이 안 좋습니다.

반면에 `ConcurrentHashMap`은 데이터를 읽을 때는 락을 걸지 않고 쓸 때 버킷 단위 별로 락을 걸기 때문에 성능을 높일 수 있습니다. 즉, 서로 다른 스레드가 동시에 다른 버킷에 접근했을 때 동시에 작업이 가능합니다!

2024-09-17 05:17 UTC, ehBeak commented on tomcat/src/main/java/org/apache/catalina/servlet/http/SessionManager.java
> +    public static synchronized SessionManager getInstance() {
`synchronized` 키워드를 사용하면, 성능 저하 문제가 발생할 수 있습니다.
하나의 스레드만 해당 메서드에 접근할 수 있기 때문에 병목현상이 발생합니다.

이 단점을 해결할 수 있는 법이 없나 살펴봤는데, double-checked locking 방식이 있더라고요..! 그래서 모든 싱글톤 객체에 위 방식을 적용했습니다.

`double-checked locking` 방식
* `instance`가 `null`이 아닌 경우 생성 되어있는 인스턴스를 반환 -> 동기화 적용 X
* `instance`가 `null`인 경우, 동기화 블록에 진입하여 새로운 인스턴스를 생성하여 초기화
* 변수에 `voliatile` 키워드를 적어, 가시성 문제 해결

2024-09-17 05:32 UTC, ehBeak commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int DEFAULT_ACCEPT_COUNT = 100;
요청이 들어왔을 때, 스레드 풀의 모든 스레드가 작업을 처리하고 있어서 요청에 대한 작업을 처리할 수 없을 때 작업 대기 큐에 저장합니다. 이때 작업 대기 큐의 크기를 의미합니다~

2024-09-17 05:35 UTC, ehBeak commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREADS_COUNT = 200;
톰캣의 기본 스레드 크기가 200이라서 그렇게 했습니다..😅
`ThreadPool`의 크기는 250이니까 스레드의 풀의 크기를 나타내는 `DEFAULT_MAX_THREADS_COUNT`를 250으로 두고 100명까지 대기 상태로 만들기 위해서는 작업 대기 큐의 사이즈르 말하는 `DEFAULT_ACCEPT_COUNT`를 100으로 두면 됩니다!

```java
private static final int DEFAULT_PORT = 8080;
private static final int DEFAULT_ACCEPT_COUNT = 100;
private static final int DEFAULT_MAX_THREADS_COUNT = 250;
```

2024-09-17 09:16 UTC, slimsha2dy commented on tomcat/src/main/java/org/apache/catalina/servlet/http/SessionManager.java
> +    public static synchronized SessionManager getInstance() {
`double-checked locking` 방식에 대해서는 알고 있었지만 `volatile` 키워드가 최적화로 인한 재배치를 막는 용도로 사용할 수 있는 줄은 몰랐네요.
실제로 해당 키워드를 붙이지 않을 경우 재배치로 인한 오류가 얼마나 발생할 수 있는지는 잘 모르겠어서 테스트를 한 번 해보고 싶네요 👍

2024-09-17 09:17 UTC, merged