[3단계 Tomcat 구현하기] 잉크(이예찬) 미션 제출합니다
woowacourse/java-http pull request #691
Opened 2024-09-13 06:34 UTC by yechop

안녕하세요 아톰

3단계 리팩토링 제출합니다.
4단계 마감시간이 얼마 남지 않아 일단 머지부탁드리고 4단계 진행 후 리뷰 해주시면 감사하겠습니다!

2024-09-14 08:28 UTC, le2sky requested changes
잉크 안녕하세요. 아톰입니다.
이전 코드들이 함께 있어서, 제 인텔리제이에서 확인하기 어렵네요. 🥲
다음 요청 시에는 불필요한 파일들 제거하고, 현재 남긴 피드백 반영하여 요청 부탁드립니다.
질문 주신 내용은 이후에 답변 드릴게요. 고생하셨습니다. 👍

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/com/techcourse/controller/LoginController.java
> +            response.addHeader(HttpHeader.LOCATION, "/401.html");
메서드 길이 수와 if else 분기를 제거해주세요. 그리고, 상수를 추출하거나 LoginRequest를 포장해주세요.

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/com/techcourse/controller/NotFoundPageController.java
> +    }
static 메서드일 필요는 없어 보입니다!

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        }
request.isGet()은 어떨까요?

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        }
변경을 바라는 것은 아니고, 단순 질문입니다. 이곳에서 request mapping 정보를 하드 코딩해놓으면 어떤 문제가 발생할 수 있을까요?

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            bufferedReader.read(buffer, 0, contentLength);
해당 작업을 하는 이유는 무엇인가요?

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/util/ContentTypeResolver.java
> +        final int lastDotIndex = resourceUri.lastIndexOf(".");
마지막 점이 의미하는 바가 무엇인가요?

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/util/StaticResourceReader.java
> +                .getResourceAsStream("static" + resourceUri);
여기 스트림은 안닫은 이유가 있을까요?

2024-09-14 08:28 UTC, le2sky commented on tomcat/src/test/java/org/apache/coyote/http11/util/ContentTypeResolverTest.java
> +    void resolve() {
👍👍 이전보다 테스트가 많아져서 좋네요.
해당 테스트의 DisplayName이 누락됐네요.

2024-09-19 01:33 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        }
내부에 httpMethod를 확인하는 메서드를 만들어 놓을 수 있겠군요!

2024-09-19 01:45 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            bufferedReader.read(buffer, 0, contentLength);
Post 요청일 때 body를 읽기 위해 사용하고 있습니다.
bufferedReader 로 contentLength만큼의 길이를 읽어 char 배열 buffer에 저장합니다.

아톰이 주신 질문의 의도에 맞는 답변일까요~?

2024-09-19 01:50 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/util/ContentTypeResolver.java
> +        final int lastDotIndex = resourceUri.lastIndexOf(".");
해당 메서드는 파일의 확장자를 구분하기 위해 만든 메서드입니다.
resourceUri에 "."이 여러개 있어도 파일의 확장자를 찾기 위해 가장 마지막에 있는 "."을 int lastDotIndex 로 선언했습니다.
lastDotIndex 이후 문자열이 파일의 확장자입니다.

2024-09-19 01:59 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/util/StaticResourceReader.java
> +                .getResourceAsStream("static" + resourceUri);
스트림을 닫아줘야 한다는 생각을 하지 못했습니다.
InputStream이 변수로 나와있는것도 뭔가 이상해보이긴 하네요.

아래처럼 리팩토링했을땐 스트림이 자동으로 닫히나요?
```
public static String read(String resourceUri) throws IOException {
        return new String (
                StaticResourceReader.class
                .getClassLoader()
                .getResourceAsStream("static" + resourceUri)
                .readAllBytes()
        );
    }
```

2024-09-19 02:28 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        }
모두 if 문으로 메서드 길이가 너무 길어지니 api가 많아졌을 때 관리가 힘들것 같습니다.
uri 별 Controller를 미리 매칭해놓을 수 있겠네요.

하드코딩 했을 때 또 다른 문제가 있을까요?

2024-09-19 10:38 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        }
👍👍 좋습니다. 말씀주신 부분도 문제겠네요. 기본적으로 잉크가 현재 만들고 있는 것은 톰캣입니다. 톰캣은 우리의 코드를 알지 못해요.
예를 들어, apache/coyote/http11/controller/RequestMapping에서 사용자 애플리케이션의 경로를 알 수 없습니다. 관련해서 고민해보시면 좋겠다고 생각하여 질문 드렸습니다. MVC 미션에서 RequestMapping과 관련된 고민들이 이어질 것 같네용.

2024-09-19 10:41 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            bufferedReader.read(buffer, 0, contentLength);
제가 질문을 더욱 명확하게 해야 했는데 혼란을 드려 죄송합니다. 🙇🏻‍♂️
질문의 의도는 header는 readLine으로 받고, body는 read(buffer, 0, contentLength)로 받아야 하는가? 였습니다.
관련해서는 다음 링크를 확인하면 좋을 것 같아서 공유드립니다. 

https://hudi.blog/woowacourse-level4-tcp-troubleshooting/

2024-09-19 10:43 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/util/ContentTypeResolver.java
> +        final int lastDotIndex = resourceUri.lastIndexOf(".");
네 맞습니다! 잉크가 해당 메서드를 구현한 이유는 이해할 수 있었어요. 하지만, 다른 개발자가 봤을 때, lastDotIndex 보다는 extensionStartIndex 가 가장 명확한 변수명이지 않았을까 생각했어요.

2024-09-19 10:52 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/util/StaticResourceReader.java
> +                .getResourceAsStream("static" + resourceUri);
알기론 GC에 수거되는 시점에 닫힐 것 같은데요? Connection, Statement, ResultSet도 마찬가지에요. 사실 이 친구들은 GC에 의해 수거되는 경우 close 처리됩니다. 그럼에도 불구하고 왜 이런 친구들은 close를 닫아줘야하는걸까요? 
우선 질문드린 의도는 close 하는 습관을 가지자라는 의도로 말씀 드렸습니다. 😀

2024-09-19 10:52 UTC, le2sky commented on tomcat/src/main/java/org/apache/coyote/http11/util/StaticResourceReader.java
> +                .getResourceAsStream("static" + resourceUri);
추가로 GC가 무엇인지도 학습해보면 좋을 것 같아요.

2024-09-19 12:05 UTC, le2sky approved these changes
잉크 안녕하세요. 아톰입니다.
피드백 잘 반영해주셨네요. 3단계는 마무리 지을게요. 
4단계 요청 주실 때는 몇 가지 요청 사항 반영해주시고, 4단계 재요청 부탁 드립니다. 🙇🏻‍♂️

- 기존 열려있는 4단계 브랜치 베이스를 현재 스쿼시 머지 커밋으로 변경해주세요.
- 간헐적으로 테스트가 깨지는 문제를 해결해주세요. (Http11ProcesssorTest, HttpResponseTest)
- HttpResponseTest의 단언을 바이트로 비교하지 말고 문자열로 비교해주세요. 바이트 배열이라면 어디가 틀렸는지 알기 어렵습니다. 잉크도 잘 아시겠지만 단언의 기본은 틀렸을 때 무엇이 틀렸는지 정확하게 알려주는 역할입니다.
    - as-is) `assertThat(httpResponse.serializeResponse()).isEqualTo(expected.getBytes())`  
    - to-be) ?

> HttpResponse의 header 를 HashMap에 담았습니다. 테스트에서 순서가 보장이 안돼 성공했다 실패했다 합니다.
테스트를 위해 LinkedHashMap을 사용하는게 좋을까요? 아니면 테스트의 문자열을 다 한줄씩 분리하여 contains()로 검증하는게 좋을까요?

말씀 주신 부분은 헤더를 담는 자료형을 말하시는 걸까요?
저는 현재 상황에서 LinkedHashMap을 사용할 것 같네요. 단순 테스트 코드를 성공 시키기 위해서 자료형을 변경하는 것은 나쁘진 않지만 근거가 부족하다고 생각해요. 말씀해주신 것처럼 contains도 대안이니까요. 

다만 http 헤더 순서가 매번 달라진다면 클라이언트 개발자가 불편할 것 같아요. 비슷한 유형의 헤더들은 함께 모여있는 것이 가독성이 좋으니까요. HTTP 헤더에는 비슷한 유형의 헤더들이 있어요. 가령, 컨텐츠 협상 헤더나 캐시 관련 헤더나.. 엄청 많을 것 같네요.

추가로 코멘트에 학습할만한 키워드 남겨놨어요. 키워드들과 더불어서 http 헤더 종류와 servlet, java io stream에 대해서 학습해보면 좋을 것 같아요. 고생하셨습니다. 😀

2024-09-19 12:05 UTC, merged

2024-09-20 05:36 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            bufferedReader.read(buffer, 0, contentLength);
처음에 lines() 로 시도하다가 무한루프에 빠지는 증상을 겪고 read(buffer, 0, contentLength)로 변경했습니다.
이유를 정확하게 찾지 못했었는데 링크 감사합니다!

2024-09-20 05:38 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        }
톰캣을 직접 구현하다보니 우리의 프로덕션 코드를 알지 못한다는 생각을 하지 못했네요.
다음 미션 진행하면서 고려해보겠습니다!

2024-09-20 06:13 UTC, yechop commented on tomcat/src/main/java/org/apache/coyote/http11/util/StaticResourceReader.java
> +                .getResourceAsStream("static" + resourceUri);
IO Stream 은 Collection Stream과 다르게 GC가 관리해주지 않는다고 하네요.
try-with-resources 로 닫아주도록 리팩토링했습니다