[4단계 - 톰캣 구현하기] 명오(김형호) 미션 제출합니다.
woowacourse/java-http pull request #693
Opened 2024-09-13 06:36 UTC by HyungHoKim00

안녕하세요 호티! 4단계를 마치고 돌아왔습니다.
의견이 궁금한 내용이 두 가지 있습니다.
1. 어떤 thread pool을 사용할지
cacheThreadPool, fixedThreadPool, scheduledThreadPool 등을 Executor를 통해 만들 수 있습니다. 저는 이 중 max-thread를 설정할 수 있는 fixedThreadPool을 선택했는데요, 호티의 선택이 궁금합니다.
2. 어떤 기준으로 max-thread를 설정할지
찾아본 결과, 아래와 같은 공식을 찾을 수 있었습니다.
Thread 개수 = CPU 코어 수 * (1 + (대기 시간 / 처리 시간))
이 공식을 바탕으로 22*(1 + 800/600) = 대략 50개로 설정했는데요,
다른 기준이 있는지 궁금합니다.

2024-09-14 13:54 UTC, Ho-Tea requested changes
고생하셨습니다 명오! 💩
벌써 마지막 미션이네요.. 명오와 리뷰를 해서 많은 것을 얻을 수 있었고, 
더 딥다이브 할 수 있었던 것 같습니다 감사합니다 🙇‍♂️
마지막 미션이니 만큼 더 열심히 리뷰해드릴게요!!
몇가지 코멘트 남겨드렸으니 확인 부탁드립니다!
행복한 주말과 추석되세요~~

+) 추가로 `PR Comment`로 남겨주신 질문에 대한 제 의견은 아래 `Comment`로 남겨놓겠습니다!

+) 테스트를 수행하는 과정에서 기존에 실패하지 않았던 테스트가 실패하는 것을 확인했습니다!
<img width="801" alt="image" src="https://github.com/user-attachments/assets/a9aab039-0eb9-4119-81ea-cbe0532244cb">

2024-09-14 13:54 UTC, Ho-Tea commented on study/src/main/resources/application.yml
>        max: 2
연결 가능한 `connection`은 2개이고 가용 쓰레드의 개수 또한 2개이므로, 대기 큐에 들어가는 경우는 없을 것 같은데
`accept-count`를  1로 설정한 이유가 있을까요? 명오의 의견이 궁금해요!

2024-09-14 13:54 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      }
현재 `Connector`는 아래의 역할을 수행하고 있다고 생각합니다.
- 서버 소켓 생성 및 초기화
- 스레드 풀 관리
- 클라이언트 연결 처리

저는 `Connector`가 요청을 적합한 프로토콜로 연결되어지게 하는 역할을 수행하는 것으로 충분하다 생각되어,
쓰레드 풀 크기와 같은 것들은 몰라도 된다고 생각하며, 쓰레드 풀 관리에 대한 역할을 `Connector`가 하게 되면 많은 역할을 하고 있다고 생각됩니다.
쓰레드 풀 관리 책임을 다른 객체에게 부여하면 어떨까요?

아래는 실제 Tomcat `Connector` 클래스이며, `protocolHandler.setUtilityExecutor(service.getServer().getUtilityExecutor());` 를 통해 타고(x100) 들어가면 `endPoint` 에서 쓰레드 풀을 관리하는 것을 확인 할 수 있습니다.

톰캣 구조를 똑같이 따라가야 한다는 뜻은 절대 아닙니다!

톰캣의 구조가 정말정말 복잡해 구조를 모두 따라할 수도 없을 뿐더러 미션의 의도는 톰캣을 클론코딩하라는 것도 아니라 생각됩니다.
톰캣의 구조 또한 이러하고 구조가 이렇게 구성되어진 이유를 생각해보면 `Connector`의 역할을 분리하고자 했던 이유이지 않을까 생각되어 말씀드립니다!

<img width="849" alt="image" src="https://github.com/user-attachments/assets/3dac3960-e0b9-422f-b696-b227144ea84b">
<img width="891" alt="image" src="https://github.com/user-attachments/assets/d5e847d7-4340-4953-a218-3b5dfd0cf157">
<img width="617" alt="image" src="https://github.com/user-attachments/assets/894dab1b-6471-43a4-8fd8-9812f400a873">

<img width="801" alt="image" src="https://github.com/user-attachments/assets/01eb83d1-d7d7-40bc-a0f1-22d3cdfa9429">

2024-09-14 13:54 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor.submit(processor);
결과를 추적하기 위해 `Future<?>` 객체를 반환하는 `submit` 함수를 사용하셨는데, 작업 결과를 이용하는 부분이 현재 코드에서는 없다고 생각됩니다. 
`execute()` 가 아닌 `submit()`을 선택하신 이유가 있을까요?

2024-09-15 17:10 UTC, Ho-Tea commented
> 어떤 thread pool을 사용할지
cacheThreadPool, fixedThreadPool, scheduledThreadPool 등을 Executor를 통해 만들 수 있습니다. 저는 이 중 max-thread를 설정할 수 있는 fixedThreadPool을 선택했는데요, 호티의 선택이 궁금합니다.

사실 `thread pool`을 직접 생성하고 사용하는 것이 처음이라 저도 명오와 같이 `Max-Thread`를 설정할 수 있는 `FixedThreadPool`을 선택하게 되었습니다. 
`cacheThreadPool`은 학습테스트를 통해 처음 알았구요..ㅎ
명오가 질문주신 부분에 대해서 찾아봤는데 정리한 내용은 아래와 같습니다.

### FixedThreadPool

**장점**
- 고정된 스레드 수로 자원을 예측 가능하게 관리.
-  CPU, 메모리 등의 리소스를 초과하지 않게 하려는 경우에 효과적

**사용 상황**
- 고정된 양의 작업을 지속적으로 처리할 때, 과도한 스레드 생성으로 인한 리소스 낭비를 방지하고자 할 때 사용

### CachedThreadPool

**장점**
- 필요한 만큼 스레드를 동적으로 생성하므로 일시적인 부하가 급증할 때 유용. 
- 다만 스레드가 너무 많이 생성되면 리소스 관리가 어려울 수 있음.

**사용 상황**
- 작업의 수나 부하가 일정하지 않거나, 짧은 시간 동안 대규모 병렬 처리가 필요한 상황에서 사용. 
- 하지만 리소스 관리가 필요하므로 제한이 없는 환경에서는 신중히 사용해야 함.

### ScheduledThreadPool:

**장점**
- 주기적으로 실행되거나 지연된 작업을 처리할 때 적합. 
- 일정한 간격으로 발생하는 작업을 안정적으로 처리할 수 있음.

**사용 상황**
- 타이머나 예약 작업(예: 데이터 동기화, 상태 체크)처럼 일정한 시간 간격으로 작업을 수행해야 하는 상황에서 사용.

### 결론

안정성과 리소스 관리가 중요하다면? -> `FixedThreadPool`을 선택. 
- 최대 스레드 수를 명확히 설정하고, 서버 리소스를 관리하는 데 유리. 특히 서버가 과부하되는 상황을 방지하는 데 유용.

작업 부하가 크게 변동된다면? -> `CachedThreadPool`을 사용할 수 있겠지만, 리소스 관리 측면에서 신중해야 함.

주기적 작업이 있다면? -> 백그라운드에서 주기적으로 처리해야 하는 작업이 있다면 `ScheduledThreadPool`도 고려
- 아직 `ScheduledThreadPool`이 사용되어야 할 상황이 아직은 현실적으로 다가오지는 않지만.. 이 부분은 알람과 같은 기능이 필요한 곳에서 사용할 것 같네요

2024-09-15 17:21 UTC, Ho-Tea commented
> 어떤 기준으로 max-thread를 설정할지
찾아본 결과, 아래와 같은 공식을 찾을 수 있었습니다.
Thread 개수 = CPU 코어 수 * (1 + (대기 시간 / 처리 시간))
이 공식을 바탕으로 22*(1 + 800/600) = 대략 50개로 설정했는데요,
다른 기준이 있는지 궁금합니다.

공식을 기준으로 명오만의 적합한 설정 기준을 세우신 점이 멋있습니다 👍👍👍

> +) 사실 저는 생각해보기 🤔에서 지정한 max-thread 설정을 따라갔습니다..ㅎ

찾아본 결과 명오가 말씀해주신 기준은 굉장히 합리적인 기준이라고 하네요!
다른 기준을 제시하는 것 보다는 저의 의견을 말씀드리자면 제공하는 서비스의 성격마다 다 다르게 설정되어야 한다고 생각되어서 
우선 명오의 기준으로 `max-thread`를 설정한 후에 애플리케이션의 실행 중 스레드 풀의 상태를 실시간으로 모니터링하고, 
필요에 따라 동적으로 스레드 수를 조정하는 것이 좋을 것 같습니다.

- 스레드 풀 모니터링: 스레드의 현재 사용률과 처리 대기 시간을 주기적으로 모니터링하여 병목 현상이 있는지 확인.
- 동적 튜닝: 시스템이 계속해서 변동할 수 있기 때문에, 트래픽이 높은 시간대에는 스레드 수를 늘리고, 트래픽이 낮을 때는 스레드 수를 줄이는 방법을 사용.

2024-09-17 08:35 UTC, HyungHoKim00 commented on study/src/main/resources/application.yml
>        max: 2
accept-count 숫자를 정한 기준은 없습니다. 하지만, 호티의 말에 실제와 다른 점이 있는 것 같아 말씀드립니다.

현재 학습 테스트에서 요청이 10개가 전송되고 있습니다. 요청 중 두개는 connect되고, 남는 8개 중 하나만 대기 큐에 들어가게 되어 있습니다. 즉, 대기 큐에 들어가는 경우가 존재하는 것이죠.
아래는 테스트를 돌렸을 때 로그입니다.
![image](https://github.com/user-attachments/assets/0168a70c-b6f8-46dc-97de-290bd5847e54)

2024-09-17 08:38 UTC, HyungHoKim00 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor.submit(processor);
execute() 메서드의 존재를 몰랐습니다... execute()를 쓰는 것이 더 올바르게 보이네요. 감사합니다!

2024-09-17 08:58 UTC, HyungHoKim00 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      }
쓰레드 풀 관리 책임을 다른 객체가 가지는 게 좋아 보이네요 ㅎㅎ. 기본적인 부분일 수 있는데 잘 짚어주셔서 감사합니다.
구조 분석력이 뛰어나시네요.

2024-09-17 09:00 UTC, HyungHoKim00 commented
돌아왔습니다 호티~
정성 리뷰의 신이시네요. 예상치 못한 부분이나 학습하지 못한 부분을 많이 배울 수 있었습니다.
앞으로도 공부할 때 호티가 리뷰해준 pr을 자주 볼 것 같네요 ㅎㅎ.
정말 감사했습니다~!! (마지막이 아닐 수도 있긴 하죠..)

2024-09-18 12:33 UTC, Ho-Tea approved these changes
정말 고생많으셨습니다! 명오 💩💩💩
벌써 마지막 코멘트가 됐네요 🥲
명오와 의견공유를 통해 많은 것을 배웠고, 딥다이브할 수 있었던 시간이였던 것 같습니다. 
다음에도 꼭 같이 리뷰 진행했으면 좋겠어요 🙇‍♂️
남은 연휴 행복하게 보내시고, 다음 미션도 파이팅입니다!!!

2024-09-18 12:33 UTC, Ho-Tea commented on study/src/main/resources/application.yml
>        max: 2
제가 `accept-count`와 `workQueue`를 같은 개념으로 잘못 판단했던 것 같습니다..하핳
`accept-count`의 경우 네트워크 소켓 대기 큐를 의미하고, `workQueue`의 경우 스레드 풀에서 작업 처리 대기를 위한 큐 를 의미한다는 것을 다시한번 상기시킬 수 있었습니다 👍

2024-09-18 12:34 UTC, merged