[STEP 2] 최승준(이든) 미션 제출합니다.
woowacourse/java-http pull request #715
Opened 2024-09-13 08:03 UTC by PgmJun

안녕하세요 메이슨 
어쩌다보니, STEP1과 STEP3를 함께 해버려서 이번에 STEP2를 구현했습니다.
STEP1을 구현하면서 만들어진 STEP3는 제대로 구현된 것은 아니어서 일단은 STEP2 + STEP3 느낌의 PR로 봐주시면 감사하겠습니다!

리뷰 잘 부탁드립니다!

### 체크포인트
- Thread 미션 코드가 함께 포함된 점 인지 부탁드리겠습니다!
- 테스트코드는 지금 작성중이니 빠르게 작성해서 함께 올리겠습니다! 우선 프로덕션 코드만 확인 부탁드려요!
- Controller라는 네이밍은 MVC 패턴의 3-Layered Architecture 에서 나온 것으로 알고 있는데 지금 단계에서 Controller라는 네이밍이 나오는 것이 굉장히 어색해서 Servlet이라는 네이밍으로 구현하게 되었다는 점 참고 부탁드립니다!

2024-09-15 09:56 UTC, masonkimseoul requested changes
안녕하세요 이든!
미션 진행하느라 고생하셨습니다.

코드가 작동하지 않는 줄 알았는데 제 실수였네요 ㅎㅎ...
전반적으로 잘 작동하고, 405 예외처리도 해주셨네요. 추가로 길이가 긴 메서드들을 분리하는 방향으로도 리팩토링 해주시면 더 좋을 것 같습니다. 테스트 코드도 추가해주시고 리뷰 요청해주세요~

감사합니다. 행복한 추석이 되길 바랍니다!

2024-09-15 09:56 UTC, masonkimseoul commented on tomcat/src/main/java/com/techcourse/servlet/RegisterServlet.java
> +            String email = req.getBodyValue(EMAIL);
세 값 중 하나라도 안들어온다면 어떻게 되나요?

2024-09-15 09:56 UTC, masonkimseoul commented on tomcat/src/main/java/com/techcourse/servlet/LoginServlet.java
> +        String password = req.getBodyValue(PASSWORD);
이 부분도 RegisterServlet에서 구현한 것처럼 예외를 처리해주면 좋을 것 같습니다!

2024-09-15 09:56 UTC, masonkimseoul commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
>  //TODO: getAccept에서 text/html 등 리턴하도록 만들
완료된 TODO라면 지워주세요~

2024-09-18 16:05 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +        message.add("Content-Type: %s;charset=utf-8 ".formatted(mimeType));
오왓.. 확인감사합니다!!

2024-09-18 16:06 UTC, PgmJun commented on tomcat/src/main/java/com/techcourse/servlet/IndexServlet.java
> +        } else {
이 부분은 3단계 요구사항과 관련이 있어서 3단계에서 처리해도 될까요~!?

2024-09-18 16:07 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +            this.httpStatus = httpStatus;
동일한 의견입니다! 우선 빠르게 구현하고 STEP3가 Request Response 리팩토링 단계여서 그부분에서 처리할까하는데 괜찮으실까요?!

2024-09-18 16:17 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            }
동의합니다 빠르게 구현하다보니 신경쓰지 못했습니다 ㅠ

```java
    private static Cookies getHttpCookies(Map<String, String> headers) {
        if (headers.containsKey("Cookie")) {
            String[] cookieLine = headers.get("Cookie").split("; ");
            return new Cookies(cookieLine);
        }
        return new Cookies();
    }
```

이 부분은 Cookies에게 책임을 넘겨보았습니다.

2024-09-18 16:19 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            }
```java
private static final String COOKIE_DELIMITER = "=";
```
Cookies 객체에서 위와 같이 처리하였습니다!

2024-09-18 16:25 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +                != -1) {
대부분의 HTTP 요청에는 1024 바이트 (1KB)의 버퍼가 적당하다는 글을 보고 위와 같이 설정해주었습니다
평균적인 웹 요청 본문 크기에 대해 효율적이고, 메모리와 성능 사이의 균형을 잘 맞추는 값이라고 하더라구요!
이번에 구현하는 서버는 대용량 요청은 존재하지 않기때문에 평균적인 경우를 바탕으로 buffer 크기를 선택해주었습니다.

2024-09-18 16:33 UTC, PgmJun commented on tomcat/src/main/java/com/techcourse/servlet/RegisterServlet.java
> +            String email = req.getBodyValue(EMAIL);
현재는 예외를 발생시키는데 404 페이지로 이동 시키는 로직까지 추가 구현해보겠습니다!

2024-09-18 16:33 UTC, PgmJun commented on tomcat/src/main/java/com/techcourse/servlet/LoginServlet.java
> +        String password = req.getBodyValue(PASSWORD);
처리하였습니다!

2024-09-18 16:33 UTC, PgmJun commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
>  //TODO: getAccept에서 text/html 등 리턴하도록 만들
구현이후 전부 제거하겠습니다!

2024-09-19 02:04 UTC, masonkimseoul approved these changes
안녕하세요 이든!
남겨주신 코멘트 잘 봤습니다.
구현하신 기능들도 잘 작동하고 테스트 코드도 추가해주셨군요.
남은 변경사항은 다음 단계에서 다시 확인하겠습니다.

2024-09-19 02:05 UTC, merged