[4단계 - Tomcat 구현하기] 포케(이무송) 미션 제출합니다.
woowacourse/java-http pull request #722
Opened 2024-09-13 08:18 UTC by fromitive

안녕하세요 프람 😄 포케입니다.

4단계 미션 제출합니다..! 

리뷰하실 때 오늘 수행한 학습테스트 리뷰도 [feat: thread 학습 테스트](https://github.com/woowacourse/java-http/pull/643/commits/67a5bbb91f9bde8880f39c135fcefb91dc9223bc) 부탁드립니다 🙏

2024-09-13 08:19 UTC, koust6u commented
고생하셨습니다. 내일까지 확인하고 코멘트 달겠습니다. 🔥

2024-09-14 04:01 UTC, koust6u requested changes
안녕하세요 포케 
즐거운 연휴네요.
시간 나실때 천천히 커멘트에 대한 의견 말씀해주시고 
시간 관계상  반영하지 못하셨던 것 까지 같이 반영해서 다시 리뷰 요청주세요

2024-09-14 04:01 UTC, koust6u commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
[질문] 
ExecutorService에서 Thread pool size와 accept Count는 어떤 차이가 있을까요? 
또 fixedThreadPool 말고 어떤 식으로 쓰레드풀을 만들 수 있을까요?

2024-09-16 02:56 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    private static final SessionManager sessionManager = new SessionManager(new ConcurrentHashMap<>());
기존 HashMap은 thread-safe 하지 않아요. java documentation을 살펴보면 HashMap은 아래와 같이 thread-safe하지 않기 때문에 Collections.SyncrhonizedMap로 wrapping해야 한다고 합니다. 😢 

[HashMap 문서](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html) 중
> 
> **Note that this implementation is not synchronized.** If multiple threads access a hash map concurrently, and at least one of the threads modifies the map structurally, it must be synchronized externally.
> (..중략..)
> This is typically accomplished by synchronizing on some object that naturally encapsulates the map. If no such object exists, the map should be "wrapped" using the Collections.synchronizedMap
>

그러나 sychronizedMap으로 감쌌다고 해서 쓰레드 동기화가 보장되지 않는다고 합니다. syncrhonizedMap의 역할은 멀티 쓰레딩 환경에서 Map이 수정이나 삭제 와 같이 구조적으로 변경되면 `ConcurrentModificationException`로 문제의 원인을 빠르게 찾을 수 있게 도와줍니다(fail-fast) 즉, 문제의 원인을 빨리 파악하는 용도이지 thread-safe한 Map으로 바꿔주진 않는다는 것이죠.

---

thread-safe한 Map은 `HashTable`을 사용하면 됩니다. 단, `HashTable`은 thread-safe함에도 불구하고 성능 문제가 존재하는데요, 검색을 수행할 때나 한 테이블의 key-value를 접근할 때 전체 테이블에 lock을 건다고 합니다. 동시성 처리를 좀 더 바란다면 `ConcurrentHashMap`을 사용하라고 java문서에서 권고하고 있습니다.

[HashTable 문서 중](https://docs.oracle.com/javase/8/docs/api/java/util/Hashtable.html)
>
> Unlike the new collection implementations, `Hashtable` is synchronized. If a thread-safe implementation is not needed, it is recommended to use `HashMap` in place of `Hashtable`. If a thread-safe highly-concurrent implementation is desired, then it is recommended to use `ConcurrentHashMap`in place of `Hashtable`.
> 

[ConcurrentHashMap문서 중](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html)

>
>  This class obeys the same functional specification as `Hashtable`, and includes versions of methods corresponding to each method of `Hashtable`. **However, even though all operations are thread-safe, retrieval operations do not entail locking, and there is  not any support for locking the entire table in a way that prevents all access.** This class is fully interoperable with `Hashtable` in programs that rely on its thread safety but not on its synchronization details.
>

---

그 밖에 쓰레드 동기화를 하는 컬랙션은 [concurrent collection](https://docs.oracle.com/javase/tutorial/essential/concurrency/collections.html) 에 아래와 같이 소개하고 있어요 😃 
* BlockingQueue : 큐가 가득 차거나, 빈 큐를 요청할 때 쓰레드가 block이 되거나 타임아웃을 일으키는 방식으로 쓰레드를 동기화 한다고 합니다.
* ConcurrentMap : `쓰레드 동기화를 하기 위한 메서드를 정의`한 **인터페이스** 입니다. 구현체는 ConcurrentHashMap이라고 합니다.
* ConcurrentNavigableMap : ConcurrentMap의 서브 인터페이스라고 합니다. NavigableMap과 같이 정렬된 키 값을 다루며, 특정 키를 기준 가까운 키 값을 찾아서 사용하는 용도의 Map이라고 합니다.

---

**결론:** 쓰레드 동기화 하기 위한 Map은 ConcurrentMap으로 변경해야 하며 전체 테이블에 lock을 거는 HashTable 보다는 ConcurrentHashMap을 선택해야 합니다.  또한, 동시성 보장을 위해 `put`을 `putIfAbsent`로 변경해야 합니다 😄

2024-09-16 03:32 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
> ExecutorService에서 Thread pool size와 accept Count는 어떤 차이가 있을까요?

Thread pool size는 현재 유지할 쓰레드의 개수를 설정합니다. 쓰레드 풀을 이용하지 않고 쓰레드를 사용하게 되면 쓰레드 생성 및 종료 시 메모리 할당에 대한 오버헤드가 발생합니다.
이를 쓰레드 풀을 통해 쓰레드를 미리 생성하여 오버헤드 발생을 최소화 시킵니다 (마치 분식집에서 라면을 동시에 끓일 때 물을 미리 끓여놓는 것 처럼 말이죠)

accept Count는 HttpClient에서 온 요청을 몇 건이나 수용할 것인지에 대한 값입니다. accept Count가 10이고 클라이언트 측에서 100건을 동시에 요청할 때 다음과 같이 처리합니다.

1. 100건 중 1건을 accept() 합니다.
2. 나머지 99건 중 10건을 대기열에 저장합니다.
3. 나머지 89건의 요청은 무시됩니다.

대기하고 있는 10건은 운영체제의 Backlog Queue에서 관리하고 있습니다.

Accept된 요청 들은 thread pool size만큼 동시에 처리할 수 있습니다.

요약하자면 아래와 같습니다.

accept count : 요청이 동시에 올때 몇 개까지 대기시킬 것인가?
thread pool size : 요청을 동시에 몇 개 처리할 것인가?

> fixedThreadPool 말고 어떤 식으로 쓰레드풀을 만들 수 있을까요?

[thread pools - java documentation](https://docs.oracle.com/javase/tutorial/essential/concurrency/pools.html)에서 fixedThreadPool 말고도 2가지 방식이 이 있다고 합니다.
1. newCachedThreadPool : 고정되어 있지 않고 유동적으로 확장 시킬 수 있게 생성됩니다. 짧게 수행하고 종료되는 task에 적합하다고 합니다.
2. newSingleThreadExecutor: 한 번에 한 개의 스레드를 처리하는 스레드풀입니다. 여러 요청이 동시에 오게 되면 한 개의 쓰레드만 처리되고 나머지 쓰레드는 실행되지 않습니다. 즉, 스레드 동기화 문제를 threadPool을 통해 통제할 수 있도록 생성할 수 있습니다.

2024-09-16 04:14 UTC, fromitive commented
안녕하세요 프람 😄 포케입니다

즐거운 추석 보내고 계신가요? 😃  

아래의 3단계에 반영하지 못한 부분 push했고, 리뷰 주신 부분에 대해 코멘트를 달았습니다.

급한게 아니니 천천히 확인 부탁드려요~~~ 🙏 

```
- controller test 추가
- requestException 네이밍 변경
```

감사합니다 🙇

2024-09-16 04:15 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    private static final SessionManager sessionManager = new SessionManager(new ConcurrentHashMap<>());
반영 완료했습니다~~~
[refactor: 쓰레드 동기화를 제대로 하도록 변경](https://github.com/woowacourse/java-http/pull/722/commits/ebb59d407a0241610067880b2280214e9c1644a4)

2024-09-16 04:16 UTC, fromitive commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
thread pool을 공부하면서 추가로 적용하면 좋은 부분들 적용했습니다 🙇 

[feat: thread pool execute의 확정버전 적용 및 shutdown() 적용](https://github.com/woowacourse/java-http/pull/722/commits/49758893cb788c366417cd238b118627c4557396)

PS: 확정버전이 아니라, 확장버전 입니다 😅

2024-09-17 05:36 UTC, koust6u commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
열심히 알오보셨군요. 포케 덕분에 저도 많이 배워갑니다.

2024-09-17 05:37 UTC, koust6u approved these changes
포케 이번 미션 고생많으셨습니다.
남은 추석연휴도 잘 보내세요 🖐️

2024-09-17 05:49 UTC, merged