[4단계 - 동시성 확장하기] 상돌(이상진) 미션 제출합니다.
woowacourse/java-http pull request #726
Opened 2024-09-13 08:24 UTC by pricelees

프린 안녕하세요~ 

아직 쓰레드와 동시성에 대한 이해가 부족하여 일단 기능 구현 완료 -> 정상 작동 여부 확인 후 제출드립니다..ㅎㅎ
테스트도 어떻게 처리할지 애매해서 아직 작성하지 못했는데, 연휴 기간동안 최대한 보완해보도록 할게요.

행복한 명절 보내세요😄

2024-09-17 06:19 UTC, GIVEN53 requested changes
안녕하세요 상돌, 추석은 잘 보내고 계신가요?
더욱 즐거운 추석이 되었으면 하는 마음에 질문 몇 가지 남겼습니다 😁

함께 고민해보는 시간이 되었으면 좋겠네요 편하게 답변주세요 마지막까지 파이팅~

2024-09-17 06:19 UTC, GIVEN53 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +			processor.run();
직접 `run()`을 호출하는 것이 꼭 필요할까요?

2024-09-17 06:19 UTC, GIVEN53 commented on tomcat/src/main/java/org/apache/coyote/http11/http/session/SessionManager.java
> +	private static final Map<String, Session> sessions = new ConcurrentHashMap<>();
Map이라면 HashTable 선택지도 있을 것이고, 다른 thread safe한 collection을 선택할 수도 있을텐데, `ConcurrentHashMap`을 선택한 이유가 궁금해요!

2024-09-17 06:19 UTC, GIVEN53 commented on study/src/test/java/thread/stage0/SynchronizationTest.java
> +        public synchronized void calculate() {
synchronized 키워드의 단점은 무엇이 있을까요?

2024-09-17 06:19 UTC, GIVEN53 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +		executorService.execute(() -> {
`submit()`이 아닌 `execute()`를 호출한 이유가 궁금합니다

2024-09-21 09:39 UTC, pricelees reviewed
프린 안녕하세요~ 최근에 이런 저런 일이 있다보니 요청이 조금 늦었습니다..ㅠㅠ

남겨주신 댓글에 모두 답 남겨놨으니 한번 확인 부탁드리고요! 행복한 주말 보내시길 바랍니다 ㅎㅎ

2024-09-21 09:39 UTC, pricelees commented on study/src/main/resources/application.yml
> +    max-connections: 10
> 10으로 설정하신 이유가 있을까요??

max-connections를 2 이상으로만 하면 테스트는 통과하긴 하는데, 테스트에서는 10개의 쓰레드를 이용하고 있어 10으로 지정했어요 ~!

2024-09-21 09:39 UTC, pricelees commented on study/src/test/java/thread/stage0/SynchronizationTest.java
> +        public synchronized void calculate() {
> synchronized 키워드의 단점은 무엇이 있을까요?

성능이나 데드락 문제가 발생한다는 건데.. 이번 테스트에서 체감할 부분은 아니었던 것 같네요!

2024-09-21 09:39 UTC, pricelees commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +		executorService.execute(() -> {
> `submit()`이 아닌 `execute()`를 호출한 이유가 궁금합니다

지금 코드에서 submit을 사용하고 Callable을 지정했을 때 반환값을 유의미하게 사용할 수 있을 것 같지 않았습니다..ㅎㅎ

2024-09-21 09:39 UTC, pricelees commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +			processor.run();
> 직접 `run()`을 호출하는 것이 꼭 필요할까요?

Http11Processor가 Runnable을 상속받으니 필요 없겠네요! 바로 수정할게요 ㅎㅎ!!

2024-09-21 09:39 UTC, pricelees commented on tomcat/src/main/java/org/apache/coyote/http11/http/session/SessionManager.java
> +	private static final Map<String, Session> sessions = new ConcurrentHashMap<>();
> Map이라면 HashTable 선택지도 있을 것이고, 다른 thread safe한 collection을 선택할 수도 있을텐데, `ConcurrentHashMap`을 선택한 이유가 궁금해요!

사실 동시성 처리에 대한 경험이 없어서 요구사항에 제시된 대로 구현하였습니다..🥲
물론 그대로 복붙한거는 아니고.. ConcurrentHashMap이 다른 thread safe collection과 락을 거는 방식이 다르다 정도는 파악했는데 이 부분은 실제 사용하면서 겪어봐야할 것 같아요..ㅎㅎ

2024-09-21 16:02 UTC, GIVEN53 approved these changes
이번 미션동안 고생 많으셨습니다 상돌~
다음 미션도 화이또 😊

2024-09-21 16:02 UTC, merged