[4단계 - Tomcat 구현하기] 콜리(김건우) 미션 제출합니다.
woowacourse/java-http pull request #737
Opened 2024-09-13 08:41 UTC by coli-geonwoo

안녕하세요 카키! 4단계 미션 제출합니다.

지난 미션으로부터 추가 변경사안은 다음과 같습니다.

---
LMS servlet 구조 반영 : Controller < (implements) < AbstractController < (extends) < XXXController
StatusCode enum화
HeaderContent enum화
Optional 필드 삭제
Adapter 패턴 삭제
정적 팩터리 메서드를 통한 Response 생성 : HttpResponse.ok
상수 분리
HttpResponseHeader에서 statusCode와 statusMessage 관리하도록 책임 이전
---

2024-09-14 15:43 UTC, hyeon0208 requested changes
무사히 완주했네요 고생했어요 콜리 ~ 
테스트 꼼꼼하게 작성하려고 노력하신 것 같네요 👍 

몇 가지 간단한 리뷰 남기고 추가로 아래와 같은 문제가 있어요
문제가 발생하는 상황을 정리하면 다음과 같습니다.

로그인 GET -> 로그이인POST 성공 -> 홈 화면으로 리다이렉션 -> 애플리케이션 재실행 -> 로그인 GET -> 401 에러
<img width="1815" alt="image" src="https://github.com/user-attachments/assets/b219c5f2-e4af-4fcc-882b-1fe7b9570b10">

현재로는 한 번 로그인한 이력이 있는 회원들은 서버가 재 실행되면 쿠키에 있는 세션 값을 삭제하지 않는 이상 계속 401에러를 반환해요
정상적인 흐름은 아니라고 생각하는데 한 번 해결해봅시다 브로콜리 🥦!

2024-09-14 15:43 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/Cookie.java
> +        Map<String, String> tempCookies = new LinkedHashMap<>();
[질문]
구현체를 HashMap -> LinkedHashMap 으로 변경한 이유가 있나요 ?

2024-09-14 15:43 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpRequestHeader.java
> +                        split -> split[HEADER_VALUE_INDEX].strip()
상수화 👍

2024-09-14 15:43 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpRequestHeader.java
[필수]

학습 테스트 중 2 테스트가 터지고 있어요
학습 테스트 완료도 조건이니 확인해주세요 !
<img width="532" alt="image" src="https://github.com/user-attachments/assets/bd893086-b188-40c2-a824-5042165be9ed">

2024-09-14 15:43 UTC, hyeon0208 commented on tomcat/src/test/java/org/apache/coyote/http11/controller/UserControllerTest.java
> +class UserControllerTest {
[제안]
이번 단계 파일체인지에 해당 클래스가 없어서 여기다 코멘트 남깁니다

org.apache.coyote는 was 패키지인데
콜리가 직접 작성하신 xxxController들은 Service를 의존하고 이는 Spring의 MVC와 유사해요
그렇다면 이 xxxController에 있는 클래스들의 패키지 위치가 적절할까요 ??
패키지 위치에 대해 우리 한 번 고민해봐요 !

2024-09-15 19:46 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/Cookie.java
> +        Map<String, String> tempCookies = new LinkedHashMap<>();
test를 할 때 원래 raw Text를 serialize한 이후 같은 값으로 직렬화가 되는지를 검증하려 했는데 Map의 특성상 순서가 보존이 안되어 test가 깨졌다 통과했다 하는 일이 있었어요.

ex)
어쩔때는 A=a; B=b; 순으로 직렬화되고 어쩔땐 B=b; A=a; 순으로 직렬화됨

순서를 보장해주는게 낫겠다 싶어서 한 리팩터링인데 지금보니 테스트 로직이 애플리케이션에 영향을 준 케이스가 되어버렸네요. 

순서에 영향을 받았던 기존의 테스트를 수정해주고 다시 HashMap으로 바꾸어 주었습니다!

[기존]
```java
@DisplayName("쿠키를 직렬화 할 수 있다")
    @Test
    void serialize() {
        String serializedText = "yummy_cookie=choco; tasty_cookie=strawberry; JSESSIONID=656cef62-e3c4-40bc-a8df-94732920ed46";

        Cookie cookie = Cookie.read(serializedText);
        CookieSerializer cookieSerializer = new CookieSerializer();

        assertThat(cookieSerializer.serialize(cookie)).isEqualTo(serializedText);
    }
```

[개선]

```java
@Test
    void serialize() {
        String serializedText = "yummy_cookie=choco; tasty_cookie=strawberry; JSESSIONID=656cef62-e3c4-40bc-a8df-94732920ed46";

        Cookie cookie = Cookie.read(serializedText);
        CookieSerializer cookieSerializer = new CookieSerializer();

        String actual = cookieSerializer.serialize(cookie);

        assertAll(
                ()-> assertThat(actual).contains("yummy_cookie=choco;"),
                ()-> assertThat(actual).contains("tasty_cookie=strawberry;"),
                ()-> assertThat(actual).contains("JSESSIONID=656cef62-e3c4-40bc-a8df-94732920ed46")
        );
    }
```

2024-09-15 20:02 UTC, coli-geonwoo commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpRequestHeader.java
FileTest 는 수정 완료했습니다!

AppTest의 경우 Application 구동 후 수행해야 해서 터지는 것 같아요! 제 로컬에서는 잘 동작하는데 한번 확인 부탁드립니다 😄

2024-09-15 20:13 UTC, coli-geonwoo commented
> 현재로는 한 번 로그인한 이력이 있는 회원들은 서버가 재 실행되면 쿠키에 있는 세션 값을 삭제하지 않는 이상 계속 401에러를 반환해요 정상적인 흐름은 아니라고 생각하는데 한 번 해결해봅시다 브로콜리 🥦!

오.. 꼼꼼한 리뷰 감사합니다 카키! 애플리케이션이 재구동하는 상황에 대해 깊게 고민하지 못했네요.... 세션값이 일치하지 않으면 loginView를 반환하도록 개선해주었습니다!

2024-09-15 20:18 UTC, coli-geonwoo commented on tomcat/src/test/java/org/apache/coyote/http11/controller/UserControllerTest.java
> +class UserControllerTest {
[질문]

오!! 안그래도 이부분 꼭 카키한테 물어보고 싶었는데 먼저 이야기를 꺼내주어서 반갑네요 😄 

우선 service의 경우 apache가 아니라 techcourse에 있어야 한다는 사실에는 동의해요. login이나 user라는 도메인 로직이 깊게 들어가있다고 판단했거든요.

그런데 controller의 경우는 techcourse로 옮기는 것이 조금 망설여져요.
- 첫째로, 저는 이번 미션의 controller가 MVC 패턴 상의 controller가 아닌 웹의 요청을 바탕으로 응답을 구성하는 servelet의 일종이라고 보고 있어요
- 둘째로, AbstractController의 하위 구현 클래스가 다른 패키지에 있는게 부자연스러웠던 것 같아요.


그래서 우선 service 만 techcourse 쪽으로 옮기고 controller는 그대로 유지하는 걸 택했는데요. 카키는 혹시 어떻게 패키지를 나누었나요? 저도 잘 모르겠어서 카키의 선택과 그 판단 근거가 무엇인지 궁금합니다!

2024-09-16 01:58 UTC, hyeon0208 commented on tomcat/src/main/java/org/apache/coyote/http11/Cookie.java
> +        Map<String, String> tempCookies = new LinkedHashMap<>();
구체적인 설명 감사해요 !
"테스트 로직이 애플리케이션에 영향을 준 케이스"라는 점에서 깊게 생각해서 변경해주셨네요 👍

2024-09-16 02:59 UTC, hyeon0208 commented on tomcat/src/test/java/org/apache/coyote/http11/controller/UserControllerTest.java
> +class UserControllerTest {
저는 Controller가 Service를 의존하고 있다는 점에서 MVC로 바라봤어요
coyote 패키지에 있는 Controller가 우리가 직접 정의한 코드가 있는 techcourse에 있는 Service를 의존한다면
이 톰캣은 우리의 서비스에만 종속적인 was가 된다고 생각했거든요
콜리가 생각되는데로 자유롭게 반영해주세요 👍

2024-09-16 03:01 UTC, hyeon0208 commented
콜리 미션 요구사항들은 충분히 만족하신것 같아 이만 apporve합니다 ~ 👍 
세션처리 관련해서도 잘 해결해주셨네요 😄
즐거운 추석 보내시고 목요일날 봐요 ~ 다음 미션도 화이팅입니다 😎

2024-09-16 03:01 UTC, merged