[4 단계 Tomcat 구현하기] 제리(김민정) 미션 제출합니다.
woowacourse/java-http pull request #741
Opened 2024-09-13 08:44 UTC by mzeong

2024-09-14 16:40 UTC, shin-jisong requested changes
안녕하세요 제리!
시간 상의 이슈가 있었어서 지난 리뷰는 빠르게 마감했었는데요, 지난 리뷰에 해당하는 것을 여기에 보충해서 달았어요 
따라서 코드와 매칭되는 리뷰가 아님을 감안해 주세요 🥲
더불어 월요일이 새로운 미션의 시작인데요!
제리는 일요일까지는 머지가 되는 것을 선호하는지,  그 이후에도 진행하는 걸 희망하는지 묻고자 해요
일정을 고려하여 편하게 답변 주세요 👍

2024-09-14 16:40 UTC, shin-jisong commented on study/src/main/resources/application.yml
>  server:
코드 Http 안에 Request 폴더가 있고 또 따로 Http11 패키지 안에 HttpRequestXXX 명명의 클래스가 있는데 구분 기준이 무엇일까요?

2024-09-14 16:40 UTC, shin-jisong commented on study/src/main/resources/application.yml
>      accept-count: 1
테스트 코드를 조금 더 보충해 보는 건 어떨까요? 스레드 관련 테스트도 해 보면 더 좋을 듯해요~

2024-09-14 16:40 UTC, shin-jisong commented on study/src/test/java/thread/stage0/SynchronizationTest.java
> +        public synchronized void calculate() {
HttpHeader에 속하는 정보에 대한 Class가 많이 생긴 것 같아서 해당 클래스들을 패키지로 묶으면 좀 더 보기 수월할 수도 있겠어요!

2024-09-14 16:40 UTC, shin-jisong commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
Http 내에 getXX 명명으로 단순 getter가 아닌 계산이 들어가는 로직들이 있더라고요! 
해당 부분을 class로 추출해서 필드값을 return하는 것과 호출할 때마다 parsing 과정을 거치는 것 중 제리가 후자를 선택한 이유가 궁금해요

2024-09-14 16:40 UTC, shin-jisong commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
> +import org.slf4j.Logger;
SessionService가 현재는 techcourse 내부의 service 패키지 내에 UserService와 함께 있던데요,
SessionService는 그 특성이 조금 다르다는 생각이 들어서 해당 위치로 둔 이유가 궁금해요!
(UserService는 프로그램 내의 로직이고 Session의 경우에는 톰캣 구현하기에서 사용하는 로직이니 org/apache 내에 배치하는 것이 어떨까? 생각이 들었어요)

2024-09-14 16:40 UTC, shin-jisong commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
> + * <p>
추가적으로 저의 경우에는 시간상의 문제로 apache, catalina, coyote, tomcat 등을 제대로 학습하지 못하고 구현한 것 같아 아쉬웠어요
제리의 경우에서는 이번 미션에서 무엇을 가장 우선시하고 작업하였는지 궁금해요!
(책임과 분리, 구조, 구현, 톰캣 학습 등의 목적이 있었을 거라 생각합니다 👍)
혹시나 여유가 있다면 위 사항을 학습해 보면 좋을 것 같아요~

2024-09-20 16:21 UTC, mzeong commented on study/src/test/java/thread/stage0/SynchronizationTest.java
> +        public synchronized void calculate() {
[반영] 아래에도 패키지 관련 코드 리뷰를 남겨주어 함께 반영했습니다! [5b8d7fe](https://github.com/woowacourse/java-http/pull/741/commits/5b8d7fe680f40f67b493941c0c272db43738c33f)

2024-09-20 16:22 UTC, mzeong commented on study/src/main/resources/application.yml
>      accept-count: 1
[반영] 4단계 관련한 테스트 코드를 추가했습니다 [6f64001](https://github.com/woowacourse/java-http/pull/741/commits/6f64001a5c456c132a0465f8d8a785ab864a7691)

2024-09-20 16:29 UTC, mzeong commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
request body 부분에서 후자의 구현을 했었는데, 추후 request body를 별도의 클래스로 분리할 것을 염두해두고 (getter 내 로직을 그대로 생성자 로직으로 쓰려고) 선택했어요

2024-09-20 16:35 UTC, mzeong commented on study/src/main/resources/application.yml
>  server:
[반영] 잘못된 패키지라 제거했습니다...! [de93469](https://github.com/woowacourse/java-http/pull/741/commits/de934695a06b41b9ec26a66361f150e6c31abee8)

2024-09-21 07:12 UTC, shin-jisong approved these changes
일정이 바쁘셨던 것 같은데 잘 마무리해 주셨네요! 👍
보면서 저도 많이 배워갑니다 🙇‍♂️
이만 머지할게요 다음 미션도 파이팅입니다 👊

2024-09-21 07:12 UTC, merged