[4단계 - Tomcat 구현하기] 우주(김성현) 미션 제출합니다.
woowacourse/java-http pull request #746
Opened 2024-09-13 08:46 UTC by tsulocalize

안녕하세요, 리니.
시간이 부족해 테스트는 작성하지 못했고, 곧 추가할 예정입니다!!
천천히 리뷰해주시면 감사하겠습니다...!

2024-09-15 10:05 UTC, linirini requested changes
우주, 안녕하세요🖐️
4단계 관련해서는 코드 변경 사항이 많지 않아서 코멘트를 남길 게 많진 않았어요 ㅎㅎ

이번 리뷰에서는 학습 테스트 관련해서도 코멘트를 좀 남겨보았습니다. 수정 사항보다는 질문 위주로 남겨보았어요!

톰캣 구현 관련해서는 몇 가지 테스트 추가 요청과 코드에서 개선해볼만한 부분을 좀 남겨보았어요!

반영 후, 리뷰 요청 부탁드려요! 마지막까지 화이팅입니다 🙌

2024-09-15 10:05 UTC, linirini commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMimeType.java
> +    IMG_SVG("image/svg+xml", null),
MimeType도 테스트를 작성하면 좋을 것 같아요!

2024-09-15 10:05 UTC, linirini commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMimeType.java
만약, 적절한 content-type을 찾을 수 없다면 null 대신 사용할 수 있는 형식이 없을까요?

참고: https://www.rfc-editor.org/rfc/rfc2616#section-7.2.1

2024-09-16 12:23 UTC, tsulocalize commented on study/src/test/java/study/FileTest.java
> +        URL url = ClassLoader.getSystemClassLoader().getResource(fileName);
`ClassLoader.getSystemClassLoader()`는 Application을 구동하기위해 필요한 클래스를 불러오는 클래스 로더로, 일반적으로 Application ClassLoader입니다.
`getClass().getClassLoader()`는 해당 클래스를 불러오기 위해 사용된 클래스 로더도 일반적으로 개발자가 작성한 클래스의 경우 Application ClassLoader를 반환합니다.

2024-09-16 12:30 UTC, tsulocalize commented on study/src/test/java/study/FileTest.java
> +        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
`getClass().getClassLoader()`는 위에 기술하였고 `Thread.currentThread().getContextClassLoader()`는 해당 스레드의 컨텍스트 클래스 로더를 반환합니다. 특별히 해당 스레드를 설정하지 않은 경우 부모 class loader를 반환하며, 일반적으로 Application ClassLoader입니다.

2024-09-16 12:34 UTC, tsulocalize commented on study/src/test/java/study/IOStreamTest.java
> +            outputStream.close();
반영했습니다!

2024-09-16 12:44 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = Executors.newFixedThreadPool(maxThreads);
일정한 스레드 수로 작업을 처리하는지, 작업마다 스레드를 생성하거나 유휴 스레드를 제사용하는 방식으로 처리하는지에 따라 FixedThreadPool과 CachedThreadPool로 나뉩니다.

2024-09-16 13:02 UTC, tsulocalize commented on study/src/main/resources/application.yml
> +    max-connections: 10
max-connections : 서버에서 연결할 수 있는 최대 커넥션 수입니다.
accept-count : 연결된 커넥션 수가 max-connections에 도달했을 때의 연결 대기열(queue) 길이입니다.
thread.min-spare : 스레드 풀의 최소 스레드 수입니다.
thread.max : 스레드 풀에서 동시에 사용할 수 있는 최대 스레드 수입니다.

2024-09-16 13:18 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      public void stop() {
반영했습니다!

2024-09-17 06:40 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11RequestHeaders.java
>              String[] keyValue = headerLine.split(": ");
반영했습니다!
그랬었군요... 새롭게 알게된 사실이에요!!

2024-09-17 07:01 UTC, tsulocalize commented on tomcat/src/test/java/org/apache/coyote/http11/controller/LoginControllerTest.java
> +public class LoginControllerTest {
테스트 추가했습니다!

2024-09-17 07:07 UTC, tsulocalize commented on tomcat/src/test/java/org/apache/coyote/http11/controller/RegisterControllerTest.java
> +                .contains("Set-Cookie");
RegisterController가 아닌 LoginController로 잘못 쓰고 있었네요...
수정했습니다!

2024-09-17 07:13 UTC, tsulocalize commented on tomcat/src/test/java/org/apache/coyote/http11/request/Http11RequestHeadersTest.java
> +public class Http11RequestHeadersTest {
테스트 추가 및 코드 수정했습니다!
확실히 실패 테스트가 있는 편이 버그 잡아내기에 좋네요...!

2024-09-17 07:33 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11ResponseHeaders.java
테스트 추가했습니다!

2024-09-17 07:34 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
테스트 추가했습니다!

2024-09-17 07:43 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMimeType.java
> +    IMG_SVG("image/svg+xml", null),
테스트 추가했습니다!

2024-09-17 13:17 UTC, linirini requested changes
우주, 리뷰 반영하시느라 수고많으셨습니다.!
마지막! RC를 남기려고 합니다 ㅎㅎ
[코드 반영 요구사항 1개](https://github.com/woowacourse/java-http/pull/746#discussion_r1760011458)랑(제가 모르는 사이에 resolved 되어있던 코멘트가 있어서 우주도 놓친 것 같아요😅) 몇가지 학습 질문 남겨보았습니다!
확인해보시고, 재리뷰요청 부탁드려요!
즐거운 추석 보내세요🙌

2024-09-17 13:17 UTC, linirini commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = Executors.newFixedThreadPool(maxThreads);
그렇다면 우주는 어떤 이유로 `newFixedThreadPool`을 선택하셨나요?

2024-09-17 13:17 UTC, linirini commented on tomcat/src/main/java/org/apache/catalina/SessionManager.java
> +    private static final Map<String, Session> sessions = new ConcurrentHashMap<>();
ConcurrentHashMap은 HashMap과 무엇이 다르며, 어떻게 동시성 문제를 해결하나요?

2024-09-20 05:26 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = Executors.newFixedThreadPool(maxThreads);
스레드 생성 비용이 크다고 알고 있고, 스레드가 많아질수록 컨텍스트 스위칭이 많아질거라 생각해 FixedThreadPool을 선택했습니다!

2024-09-20 05:33 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMimeType.java
"application/octet-stream" 추가했습니다!

2024-09-20 05:41 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executorService.submit(processor);
execute()는 결과가 필요 없을 때, submit() 결과가 필요할 때 사용합니다! (그렇다고 하네요...!)
현재 제 코드 상에서는 결과가 필요 없으므로 execute로 수정했습니다!

2024-09-20 05:49 UTC, tsulocalize commented on tomcat/src/main/java/org/apache/catalina/SessionManager.java
> +    private static final Map<String, Session> sessions = new ConcurrentHashMap<>();
Concurrent Collections는 동시성 문제를 해결한 컬렉션 자료구조입니다.
ConcurrentHashMap의 경우, 값을 넣을 때 synchronized를 통해 여러 스레드에 의한 동시 쓰기 작업을 방지합니다.
그 대신, 값을 가져올 때는 synchronized와 같은 제한을 두지 않아 성능 문제가 없습니다.

2024-09-20 06:04 UTC, linirini commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executorService.submit(processor);
참고: https://www.baeldung.com/java-execute-vs-submit-executor-service

2024-09-20 06:08 UTC, linirini approved these changes
우주~ 고생 많으셨어요!!
반영해주신 부분이랑 코멘트 확인했습니다! 충분히 학습하신 것같아서  저번에 말씀드렸듯, 이만 merge하도록 하겠습니다.
이번 MVC 미션도 화이팅입니다🙌

2024-09-20 06:08 UTC, merged