[4단계 - Tomcat 구현하기] 호티(윤주호) 미션 제출합니다.
woowacourse/java-http pull request #749
Opened 2024-09-13 08:51 UTC by Ho-Tea

안녕하세요 아토! 마지막 미션으로 뵙네요 🙇‍♂️
`Connector` 가 쓰레드 생성, 관리의 역할을 가지는 것이 어색해 보여 분리를 시도해보았는데 아직 미흡한 것 같습니다..
미션 진행하면서 더 공부하고 리팩토링해볼게요!

2024-09-14 14:49 UTC, hyxrxn requested changes
호티 안녕하세요~ 아토입니다!

이번엔 역시 남길 게 많지 않네요~~
천천히 답변/반영 해주시죠.

pr description을 보니 테스트를 추가해주신다고 하시길래...
일단은 rc 드립니다 ㅋㅋㅋㅋㅋ
저도 어떻게 해야할지 꽤나 고민인데 혹시 어렵다면 함께 얘기해보든지 해요!

마지막까지 화이팅입니다 😄

2024-09-14 14:49 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      public Connector(final int port, final int acceptCount) {
lms의 예시 코드를 보면 `Connector`의 생성자에서 `maxThreads`를 받고 있는데요,
호티는 이 값을 정해주는 역할이 `Connector`가 아닌 `StandardThreadExecutor`네요!
`Connector`는 아예 관련 정보를 알지도 못하구요.
그렇게 보신 이유가 궁금합니다.

```java
// maxThreads를 추가했다.
public Connector(final Container container, final int port, final int acceptCount, final int maxThreads) {
    // 생성자에서 스레드 풀 생성
}
```

2024-09-14 14:49 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/core/StandardThreadExecutor.java
> +    private static final int DEFAULT_MAX_THREADS = 250;
클래스 첫 줄...
띄우기로 컨벤션을 정했다면 맞춰봅시다 ㅎㅎ

2024-09-14 14:49 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +import org.slf4j.LoggerFactory;
저번 리뷰 마지막에 남겼었는데, 혹시 못보셨을까 해서 다시 한 번 남겨요!

[구글 자바 컨베션 관련](https://github.com/woowacourse/java-http/pull/651#discussion_r1758263031)

2024-09-14 14:49 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    };
중괄호는 오타일까요?!

2024-09-14 14:49 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/core/StandardThreadExecutor.java
> +    public void execute(Runnable command) {
인텔리제이가 상위 클래스에 `@NotNull`이 있으니 여기도 붙이는 것이 어떻냐는 제안을 해주네요.
다른 개발자들에게 알려주기도 해야하고, 혹시 모르는 상황에 대비도 할 수 있으니 추가해주는 게 어떨까요?

2024-09-15 18:41 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +import org.slf4j.LoggerFactory;
반영하였습니다! 감사합니다 🙇‍♂️

2024-09-15 18:42 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/core/StandardThreadExecutor.java
> +    public void execute(Runnable command) {
해당 메서드는 리팩토링하면서 삭제되었지만, 좋은 의견인 것 같아요!

2024-09-15 18:50 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      public Connector(final int port, final int acceptCount) {
현재 `Connector`는 아래의 역할을 수행하고 있다고 생각합니다.
- 서버 소켓 생성 및 초기화
- 스레드 풀 관리
- 클라이언트 연결 처리

저는 `Connector`가 요청을 적합한 프로토콜로 연결되어지게 하는 역할을 수행하는 것으로 충분하다 생각되어,
쓰레드 풀 크기와 같은 것들은 몰라도 된다고 생각하며, 쓰레드 풀 관리에 대한 역할을 `Connector`가 하게 되면 많은 역할을 하고 있다고 생각되었습니다
따라서 쓰레드 풀 관리 책임을 다른 객체에게 부여하면 어떨까? 라는 생각으로 이어지게 되었습니다.

아래는 실제 Tomcat `Connector` 클래스이며, `protocolHandler.setUtilityExecutor(service.getServer().getUtilityExecutor());` 를 통해 타고(x100) 들어가면 `endPoint` 에서 쓰레드 풀을 관리하는 것을 확인 할 수 있습니다.

톰캣 구조를 똑같이 따라가야 하는 것은 아니지만,
톰캣의 구조 또한 이러하고 구조가 이렇게 구성되어진 이유를 생각해보면 `Connector`의 역할을 분리하고자 했던 이유이지 않을까 생각되었습니다

> +) 실제 톰캣에서는 Connector 클래스가 직접적으로 ServerSocket을 accept() 하지 않고, 네트워크 연결을 관리하는 ServerSocket 관련 작업은 Connector가 아닌 ProtocolHandler와 Endpoint가 처리한다고 합니다.. 
지금 모든 구조를 톰캣처럼 하기에는 무리가 있다고 판단하기도 했으며, 최대한 분리할 수 있는 부분에 대해서만 고민했던 것 같습니다!

<img width="849" alt="image" src="https://github.com/user-attachments/assets/3dac3960-e0b9-422f-b696-b227144ea84b">
<img width="891" alt="image" src="https://github.com/user-attachments/assets/d5e847d7-4340-4953-a218-3b5dfd0cf157">
<img width="617" alt="image" src="https://github.com/user-attachments/assets/894dab1b-6471-43a4-8fd8-9812f400a873">

<img width="801" alt="image" src="https://github.com/user-attachments/assets/01eb83d1-d7d7-40bc-a0f1-22d3cdfa9429">

2024-09-16 09:41 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      public Connector(final int port, final int acceptCount) {
생각해보니 학습테스트에서도 yml로 값들을 설정해주네요!
어떤 이유인지 이해했습니다.

2024-09-16 09:54 UTC, hyxrxn requested changes
호티~~~ 코드 잘 확인했습니다!

질문이 몇 가지 있어 (아마도) 마지막 rc 드려요.
답변만 주시면 될 것 같아요~~~
DM도 확인 부탁드립니다!

2024-09-16 09:54 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/core/StandardThreadPoolExecutor.java
> +    }
값들의 설정 이유가 궁금합니다~~~

2024-09-16 09:54 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(final ExecutorService executorService, final int port, final int acceptCount) {
기존엔 `this.executor = new StandardThreadExecutor();`로 바로 생성했었는데,
코드를 수정하며 `ExecutorService`를 파라미터로 받는 생성자를 추가한 이유는 뭔가요?!
사용하는 객체를 수정한 이유도 궁금합니다.

2024-09-16 09:56 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    };
아직 수정이 안된 것 같아요 ㅠㅠ

2024-09-16 09:57 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
> +    };
아직 수정이 안된 것 같아요 ㅠㅠ

2024-09-16 13:02 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/core/StandardThreadPoolExecutor.java
> +    }
학습테스트에서 진행한 `newFixedThreadPool`에서 설정한 값들을 주로 사용하였고, 
- 가용 쓰레드와 max 쓰레드의 수가 같기에 `keepAliveTime`은 0으로 설정하였습니다.
- `max-thread` 수의 선정 기준은 `lms` 생각해보기에서 언급한 쓰레드 갯수를 사용하였고, `CPU Core` 수를 기준으로 적합한 `max-thread` 수를 찾는 공식을 적용하지는 않았습니다.

![image](https://github.com/user-attachments/assets/3ba1fef1-74bb-4d66-8a21-a987433a64fc)

2024-09-16 13:08 UTC, Ho-Tea commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(final ExecutorService executorService, final int port, final int acceptCount) {
`ThreadPool`은 여러 변화에 따라 사용될 수 있다고 생각되었습니다. 
`FixedThreadPool`, `CachedThreadPool`, `ScheduledThreadPool` 등과 같이 각 `Thread Pool` 마다의 성격이 다른데, 
이전 처럼 `FixedThreadPool`을 고정시켜 놓은 것은 변화에 유연하지 못하다고 생각되어 
기존에 사용되어지는 객체를 `ThreadPoolExecutor`를 상속받는 객체로 구현하였고, 
다형성을 위해 인터페이스를 인자를 통해 받게 되었습니다.

2024-09-16 13:12 UTC, Ho-Tea commented
> 마지막 동시성 컬렉션 사용 관련 테스트가 없네요!
테스트가 필요할지, 한다면 어떻게 할지... 관련해 생각해보시고 의견 주세요.

단순히 `HashMap`을 `ConcurrentHashMap`으로 변경했을 뿐이라 무엇을 검증하든
기존에 제공되는 `ConcurrentHashMap`의 기능을 검증하는 테스트가 될 것 같아 구성하지 않았습니다!

2024-09-16 13:38 UTC, hyxrxn approved these changes
답변들 잘 읽었습니다! 이만 approve 할게요.
이번 미션 정말 정말,,, 고생 많으셨어요,,,
새벽 두시에 리뷰 보냈는데 두시간만에 반영하셨던 게 아직도 기억에 남네요.
그 열정이 상당히 인상적이었습니다 ㅋㅋㅋㅋ

남은 연휴 잘 보내시길 바라고, 다음 미션도 화이팅입니다~~~ 💪

2024-09-16 13:39 UTC, merged