[Tomcat 구현하기 - 4단계] 아토(이혜린) 미션 제출합니다.
woowacourse/java-http pull request #763
Opened 2024-09-13 11:14 UTC by hyxrxn

망쵸 안녕하세요~~~
드디어 마지막 단계네요...!!!
천천히 리뷰 주시죠 ㅎ ㅎ

잘 부탁드립니닷 💪

2024-09-13 11:57 UTC, 3Juhwan requested changes
아토~ 마지막이네요! 
몇 가지 궁금한 점 코멘트로 남겼어요~~
고생했고, 연휴 잘 보내요!!

2024-09-13 11:57 UTC, 3Juhwan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        threadPool.submit(new Http11Processor(connection));
이 코드를 지운 이유는 무엇인가요?

2024-09-13 11:57 UTC, 3Juhwan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +                new ArrayBlockingQueue<>(acceptCount));
이러한 값들을 설정한 이유가 무엇인지 궁금해요!

2024-09-13 11:57 UTC, 3Juhwan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +                60L, TimeUnit.SECONDS,
상수로 분리하면 어떨까요?

2024-09-16 02:51 UTC, 3Juhwan commented
아토~ 제가 빠뜨린 부분이 있었네요. 구현 사항에 대한 테스트도 추가 부탁해요!

2024-09-16 08:15 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        threadPool.submit(new Http11Processor(connection));
급하게 하다보니 놓쳤네요.... 😅
다시 추가하겠습니다

2024-09-16 08:30 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +                new ArrayBlockingQueue<>(acceptCount));
> 최대 ThradPool의 크기는 250, 모든 Thread가 사용 중인(Busy) 상태이면 100명까지 대기 상태로 만들려면 어떻게 할까?

라는 lms를 읽고 이렇게 선택했습니다! 최대 크기와 대기열의 크기를 설정하기 위해서요.
`corePoolSize`를 `maximumPoolSize`를 같게 설정한 이유는 지금 상태에서 굳이 0개에서 스레드를 새로 생성할 필요가 없다고 생각했기 때문입니다! 자원이 부족한 게 아니니까요.
그런데 뒤쪽 공부를 제대로 안하고 구현했더니... 이 상태에서는 `KeepAliveTime`이 의미가 없군요. 0으로 변경해야겠습니다!
그리고 들어온 순서대로 처리하는 것이 적당한 어플리케이션 구성이라고 생각해 `ArrayBlockingQueue`를 사용했습니다.

2024-09-16 08:33 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +                60L, TimeUnit.SECONDS,
60L 관련해서 말씀 주신게 맞겠죠???
[위의 코멘트](https://github.com/woowacourse/java-http/pull/763#discussion_r1760735697)상의 이유로 0으로 변경했습니다... 현재 상황에서 0을 굳이 추출할 필요는 없다고 생각해요! 크게 의미를 담을 것이 없어 보여서요.

2024-09-17 05:40 UTC, 3Juhwan requested changes
아토~ 연휴에도 열심히 해주셨네요 👍 
코멘트 좀 남겼는데, 아토의 생각을 들려주세요! 
즐거운 한가위 되세요 😀

2024-09-17 05:40 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +        assertEquals(expectedSize, sessionManager.findAllSessions().size(), "세션 매니저에서 동시성 문제로 인해 세션이 유실되었습니다.");
엇... assertj가 아니네요? 아토는 assertj를 잘 사용하지 않는 건가요? 요구사항은 아니지만 언급 안하고 넘어갈 수가 없네요..😅

2024-09-17 05:40 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java
> +    @Test
테스트 꼼꼼하게 작성해 주셨네요 👍 
다만, 이 테스트는 ThreadPoolExecutor라는 자바 API를 테스트한 것 아닐까요?

2024-09-17 05:40 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +    public void testHashMapConcurrencyIssueInSessionManager() throws InterruptedException {
100개의 스레드에서 각 1000개의 세션을 생성하는 테스트로 보이네요 😀 
동시성을 테스트하는 것이 lms의 의도라고 생각했는데, 이 테스트는 동시성 테스트와 거리가 멀어보여요!

2024-09-17 05:40 UTC, 3Juhwan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    protected ExecutorService getThreadPool() {
테스트를 위해 열린 메서드가 좀 있네요 🥹

2024-09-19 12:37 UTC, hyxrxn commented on tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java
> +    @Test
이번단계 구현 요구사항이 스레드풀 적용이었기 때문에 적용이 잘 되었는지, 목표한대로 잘 동작하는지를 확인하려면 이런 테스트가 필요하다고 봤습니다! 
또한 동작 자체는 `ThreadPoolExecutor`와 동일하지만 내부 구현을 모르는 사람이 보았을 때 이 테스트만으로도 커넥터의 생성자에 넣는 인자들이 어떤 역할을 하는지 알 수 있다고 생각해요~~~

2024-09-19 12:39 UTC, hyxrxn commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    protected ExecutorService getThreadPool() {
마땅히 방법이 떠오르지 않아 부득이하게 열어두었습니닷...
그래도 최대한 보수적으로 잡기 위해 접근제한자를 좀 신경써보았어요!
실제로는 관련해 테스트를 짤 일이 없을 것 같았고... 그래서 학습을 위한 테스트를 짠다고 생각하고 구현했습니다 🥹
다른 방법이 있을까요???????

2024-09-19 12:53 UTC, hyxrxn commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +    public void testHashMapConcurrencyIssueInSessionManager() throws InterruptedException {
요구사항을 `SessionManager`의 `Session`컬렉션 (현재는 `Map<String, Session> SESSIONS`)의 스레드 안전성을 확인하는 것으로 이해했습니다!
컬렉션에 `HashMap`을 사용하면 여러 스레드가 동시에 add를 했을 때 유실되는 세션이 생길 수 있는데 `ConcurrentHashMap`을 사용하면 유실되지 않습니다!
그래서 저는 그 부분을 중심으로 테스트하려 했습니다.
어떤 부분에서 동시성 테스트와 거리가 멀어보이는지 조금 더 자세히 설명해주시면 이해가 쉬울 것 같아요....!!! 😹

2024-09-19 12:57 UTC, hyxrxn commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +        assertEquals(expectedSize, sessionManager.findAllSessions().size(), "세션 매니저에서 동시성 문제로 인해 세션이 유실되었습니다.");
테스트를 혼자 짜기 어려워서 도움을 좀 받았습니다만... (그래서 이해를 위한 주석도 달아놓았구요)
기존에 제가 주로 사용하던 `assertThat`이 아닌 `junit`으로 테스트가 작성되어 있는 것을 놓쳤군요...!!!

`assertThat`의 가독성이 더 좋다고 생각해 변경하도록 하겠습니다!

2024-09-20 10:53 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java
> +    @Test
아토 생각을 들려줘서 고마워요 😊

저는 ConnectorTest는 동시 요청 상황에서 1) 서버 소켓을 올바르게 생성하고 2) 연결을 적절히 수락하고 3) 연결된 클라이언트를 스레드 풀에서 처리하는지 등을 테스트해야 한다고 생각했어요!

현재 테스트도 충분하다고 생각해요!

2024-09-20 11:23 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +    public void testHashMapConcurrencyIssueInSessionManager() throws InterruptedException {
앗,, 죄송해요 🥲 제가 ConcurrentHashMap에 대해 잘못 알고 있는 부분이 있어서, 테스트를 제대로 파악하지 못했어요. 
충분히 잘 테스트되었습니다 👍

2024-09-20 11:23 UTC, 3Juhwan commented on tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
> +    public void testHashMapConcurrencyIssueInSessionManager() throws InterruptedException {
앗,, 죄송해요 🥲 제가 ConcurrentHashMap에 대해 잘못 알고 있는 부분이 있었네요. 
충분히 잘 테스트되었습니다 👍

2024-09-20 11:39 UTC, 3Juhwan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    protected ExecutorService getThreadPool() {
저도 아토 생각에 동의해요 😀 
테스트하기 쉬운 구조로 개선할 수 있겠지만, 미션에서는 가이드라인 코드가 주어지니까 쉽지 않을 것 같아요! 
고생하셨어요!

2024-09-20 11:41 UTC, 3Juhwan approved these changes
아토~~ 마지막까지 고생했어요 😀 
제가 드린 코멘트에 성실하게 답변해줘서 고마워요 
다음 미션으로 가시죠!

2024-09-20 11:41 UTC, merged