[톰캣 구현하기 - 4단계] 땡이(정지호) 미션 제출합니다.
woowacourse/java-http pull request #773
Opened 2024-09-18 11:41 UTC by J-I-H-O

리비 안녕하세요 🖐️
4단계로 돌아온 땡이입니다. 연휴 잘 보내셨나요?

이번 단계에서는 stage2 학습 테스트를 진행하면서 설정 값들을 이래저래 바꿔봤는데, 예상이랑 다른 결과가 나와서 이해하느라 머리를 꽁꽁 싸맸네요 😄
그럼 마지막까지 잘 부탁드릴게요! 감사합니당!!

2024-09-19 04:24 UTC, Libienz requested changes
안녕하세요 떙이~ 
4단계 구현 고생 많으셨습니다.

모든 테스트가 통과함과 애플리케이션 정상동작까지 확인했어요~ 학습테스트 열심히 진행해주신 것도 확인했습니다.

코멘트 남겨보았어요~ 
코멘트 확인해주시면 다음 리뷰 요청때는 Approve드리겠습니다!

2024-09-19 04:24 UTC, Libienz commented on tomcat/src/test/java/org/apache/catalina/SessionManagerTest.java
> +    }
동시성 테스트 작성해주셨군요

다만 현재 SessionManager를 안전하게 사용할 수 있다는 보장을 하는 테스트는 없네요~
ConcurrentHashmap이 안전한지에 대한 테스트만 작성되어 있는 것 같습니다.

그리고 여러번의 실행으로만 재현될까 말까 하는 테스트 코드가 그렇게 의미가 클지도 의문이네요 🤔

병렬 프로그래밍에서 thread-safe를 보장하는 테스트 코드 작성은 위처럼 작성하면 쉽게 완성할 수 있습니다.
다만 땡이가 주석처리해주신 것 처럼 그 경계를 완벽히 재현하기는 어렵죠.

땡이는 이 테스트 코드를 어떻게 하고 싶으신가요~? 
더 완벽하게 수정 할 수도 있을 것 같고 병렬 맥락에 대한 테스트를 아예 삭제하는 것도 답이 될 수 있겠어요.

다음 리뷰 떄 땡이의 결론과 그 근거를 알려주시면 좋을 것 같아요!

2024-09-19 04:24 UTC, Libienz commented on tomcat/src/main/java/org/apache/catalina/SessionManager.java
synchronized 키워드를 통해 동시성을 제어할 수도 있었겠네요!

대신 ConcurrentHashMap을 사용하신 이유가 있을까요~?

2024-09-20 02:02 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.threadPoolExecutor = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
현재는 ExecutorService 에 정의된 submit() 만 사용하고 있는데요, 구체 클래스에만 정의된 메서드를 사용하는게 아닌 이상 타입 캐스팅은 불필요한 것 같습니다.
리비 말대로 다형성이 주는 이점을 놓치고 있다는 생각이 드네요. 타입 캐스팅 제거했습니다!

2024-09-20 02:19 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/catalina/SessionManager.java
당시에 동시성 문제를 해결할 수 있는 Map 구현체들을 살펴보았습니다!

`Hashtable` 의 경우 메서드 레벨에 synchronized 키워드가 붙어있다고 알고있습니다. 이는 메서드 블록 전체가 임계 구역이 된다는 의미고, 한 번에 하나의 스레드만 해당 메서드에 접근할 수 있게 됩니다.

반면 `ConcurrentHashMap` 의 경우 읽기 작업에는 synchronized 키워드가 없고, 쓰기 작업 시에만 임계 구역을 설정하는 것으로 알고있습니다.
즉 읽기 작업 시에는 따로 block 하지 않고, 쓰기 작업 시에는 같은 element에 접근할 때만 block 하는 것으로 이해했습니다.

이같은 원리로 blocking으로 인해 스레드가 대기하는 시간을 최소화해준다고 하여 `ConcurrentHashMap`을 사용했습니다!

2024-09-20 04:33 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        threadPoolExecutor.submit(processor);
기존 방식은 요청이 들어올 때마다 새로운 스레드를 생성합니다.
매번 스레드를 생성하고 삭제해야 하기 때문에 그로인한 오버헤드가 생길 수 있고, 스레드가 무한정 생성될 수 있었기 때문에 자원 소진으로 인한 장애가 발생할 수도 있습니다.

변경된 방식은 정해진 수 만큼의 스레드를 미리 생성해두고 할당(스레드 풀)하는 방식입니다. 
기존 방식의 `요청마다 스레드를 생성하고 삭제하는 오버헤드`를 줄일 수 있고, 한정된 개수만큼의 스레드를 할당하는 방식이기 때문에 설정을 통해 시스템 부하를 조절할 수 있습니다.

2024-09-20 04:40 UTC, J-I-H-O commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREADS = 100;
큰 고민없이 톰캣의 기본 설정값을 따라가자고 결정한 부분이었습니다 (그마저도 잘못 알아봤는지 틀린 값이지만요 😅)

조금 더 찾아보니 적정 스레드 풀의 크기를 계산하는 공식도 있더라구요. 명확한 기준을 잡기 위해서는 성능 측정도 필요한 부분인 것 같은데, 참으로 어려운 부분인 것 같습니다.

혹시 리비는 어떤 기준으로 스레드 풀의 크기를 설정해주셨나요? 공유해주시면 도움 많이 될 것 같습니다 🥹

2024-09-20 05:05 UTC, J-I-H-O commented on tomcat/src/test/java/org/apache/catalina/SessionManagerTest.java
> +    }
멀티 스레드 환경에서 스레드 안정성을 테스트하기 위해서는 쓰기 작업 이후에 sessions의 크기를 검증해야 한다고 생각했어요.

하지만 sessions의 size를 알아내기 위해서는 새로운 public 메서드를 만들어주어야 할 것인데, 테스트를 위해 프로덕션 코드에 사용하지 않는 코드를 추가하는 것은 지양해야한다고 생각했습니다.

그에 대한 대안으로 SessionManager가 내부적으로 사용할 자료구조인 ConcurrentHashMap과 HashMap에 대한 스레드 안정성 테스트를 작성했습니다. 

사실상 SessionManager는 Map 구현체의 put(), get() 을 호출하는 정도의 역할만 수행해주고 있기 때문에, Map 구현체를 테스트 하는 것은 SesseionManager를 테스트 하는 것과 큰 차이가 없을 것이라고 생각했습니다.

정말로 ConcurrentHashMap을 사용하면 스레드 안정성을 보장해주는지 확인하고자 했던 것인데, 결과적으로 이미 잘 구현된 자바 컬렉션 프레임워크를 테스트하고 있는 모양이 되었네요.
학습 측면에서는 의미 있었지만, 프로덕션 코드와는 관계 없는 테스트가 된 것 같아요. 해당 테스트는 제거하도록 하겠습니다 😎

2024-09-20 05:11 UTC, J-I-H-O commented
리비 안녕하세요! 😊 
남겨주신 코멘트에 답변 달아두었습니다!
마지막까지 학습에 도움이 되는 글 남겨주셔서 감사합니다. 덕분에 학습한 내용을 되돌아보고, 더 깊게 생각해볼 수 있었어요.
그동안 리뷰 남겨주셔서 감사합니다. 남은 기간 마무리 잘 하시길 바랄게요! 🙇‍♂️

2024-09-20 14:33 UTC, Libienz approved these changes
땡이! 질문 드린 내용에 대해 너무 잘 답해주셨습니다 👍👍 첫번째 미션 고생 많으셨어요~
이만 approve 드릴려고 합니다 🎉🎉

땡이는 스스로 학습하고 결론을 내리는 역량이 매우 높은 사람이라고 생각해요! 
이어지는 미션에서도 이렇게 학습하시면 정말 좋은 개발자가 되실 것 같습니다..!

땡이와 여러 이야기를 나누면서 저는 동기부여도 받고 모르던 것을 알아가기도 하며 의미있는 시간을 보낼 수 있었어요~

땡이도 이번 미션에서 의미 있는 시간이 많았기를 바랍니다.

아프지 않게 몸조리 잘 하시구요..! 이어지는 미션도 화이팅입니다~

2024-09-20 14:33 UTC, Libienz commented on tomcat/src/main/java/org/apache/catalina/SessionManager.java
와우 꼼꼼히 학습해주셨네요~ 💯

말씀 주신 것처럼 synchronized 키워드는 스레드 경합 때문에 성능 측면에서 단점이 있습니다.
그런 이유로 현업에서는 synchronized 키워드보다 concurrent 패키지의 자료구조를 사용하는 편이 선호된다고 알고 있어요~

추가적으로 concurrent패키지의 특정 자료구조들은 락 분할이나 비 블로킹 알고리즘(CAS - Compare & Swap)으로 스레드 경합을 완화시키기도 한데요~

추가적으로 학습해보셔도 좋을 것 같습니다!

2024-09-20 14:33 UTC, Libienz commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREADS = 100;
공식이 있다는 것을 확인했지만 저도 기본 설정을 따랐습니다 ㅎㅎ..
사실 구구가 오늘 강의에서 말한 것 처럼 공식이 항상 맞을지는 잘 모르겠어요~

이런 노하우는 아마 짬에서 오는 걸까요~ 땡이의 결론도 저와 비슷한 것 같군요! 
땡이의 생각 들어보고 싶어 질문드린 코멘트였습니다~

같이 다양한 상황 만나보면서 짬을 채워보시죠ㅋㅋㅋ

2024-09-20 14:33 UTC, Libienz commented on tomcat/src/test/java/org/apache/catalina/SessionManagerTest.java
> +    }
땡이의 결론에 위화감이 없네요~
테스트를 위해서 프로덕션 코드에 나름의 오염이 발생한다면 저도 땡이와 마찬가지의 결론을 내렸을 것 같아요.

추가적으로 저는 다중 제어 흐름에서의 테스트가 중요할 수 있어도 저는 단일 제어 흐름에 대한 테스트가 우선이라고 생각해요~
기본에 맞추어 잘 구현해주셨다고 생각합니다 👍

다만 멀티 스레드 환경에서의 간섭 유무 테스트를 도와주는 다음의 도구를 소개드리니 혹 다음에 동시성이 정말 중요한 도메인을 개발하신다면 (ex: 금융, 예매 등등) 참고해보셔도 좋을 것 같습니다~

- CountDownLatch
- CyclicBarrier

2024-09-20 14:34 UTC, merged